// GENERATED by the lens-library import (K-261; curated K-264, verified and
// re-cut K-265) - regenerate rather than edit. Prescriptions are transcribed
// patent data (photonstophotos.net Optical Bench, via the FlareSim
// collection); each file cites its patent. Factual optical tables, embedded
// as text and parsed on selection.
//
// Twenty, chosen for maximally DIFFERENT flare characters and VERIFIED:
// every entry bakes a live ghost train and keeps flaring with the light
// well off-centre (the K-265 three-position probe), because the first
// curated cut shipped lenses that looked distinct in a centred montage and
// rendered nothing in the owner's hands. Wide-angle and fisheye
// prescriptions are deliberately absent: the trace's angular acceptance
// collapses off-axis for retrofocus designs (recorded limit, docs/impl/
// lens-flare.md), and a lens that only works with a centred light is a bug
// report, not a look. A user .lens file (the `lens_file` parameter) covers
// everything else.

/// One bundled lens prescription: display name, native f-number parsed
/// from the collection filename (0.0 = unknown, estimate from geometry),
/// and the .lens text.
pub struct LensFile {
    pub name: &'static str,
    pub native_fstop: f32,
    pub text: &'static str,
}

pub static LENS_LIBRARY: [LensFile; 20] = [
    LensFile { name: "7Artisans · 50mm F0.95", native_fstop: 0.95, text: include_str!("../../lens_files/7Artisans_50mm_F0.95_(7Artisans_APS-C_50mm_F0.95).lens") },
    LensFile { name: "Angenieux · DEM 180mm F2.3 APO", native_fstop: 2.30, text: include_str!("../../lens_files/Angenieux_180mm_F2.3_(Angenieux_DEM_180mm_F2.3_APO).lens") },
    LensFile { name: "Canon · 50mm f1.2 (1956)", native_fstop: 1.20, text: include_str!("../../lens_files/Canon_50mm_F1.2_(Canon_50mm_f1.2).lens") },
    LensFile { name: "Canon · 85mm f1.5 (1952)", native_fstop: 1.50, text: include_str!("../../lens_files/Canon_85mm_F1.5_(Canon_85mm_f1.5).lens") },
    LensFile { name: "Canon · EF 100mm f2.8 Macro", native_fstop: 2.89, text: include_str!("../../lens_files/Canon_100mm_F2.89_macro_(Canon_EF100mm_f2.8_Macro).lens") },
    LensFile { name: "Canon · EF 400mm f2.8L IS II", native_fstop: 2.90, text: include_str!("../../lens_files/Canon_392mm_F2.9_(Canon_EF400mm_f2.8L_IS_II_USM).lens") },
    LensFile { name: "Canon · EF 70-200mm f2.8L", native_fstop: 2.92, text: include_str!("../../lens_files/Canon_72-194mm_F2.923_IZ_(Canon_EF70-200mm_f2.8L_USM).lens") },
    LensFile { name: "Canon · FD 300mm f2.8 SSC Fluorite", native_fstop: 2.80, text: include_str!("../../lens_files/Canon_300mm_F2.8_(Canon_FD300mm_f2.8_SSC_Fluorite).lens") },
    LensFile { name: "Leica · Elmarit 90mm F2.8", native_fstop: 2.80, text: include_str!("../../lens_files/Leica_90mm_F2.8_(Leica_Elmarit_90mm_F2.8).lens") },
    LensFile { name: "Leica · Summilux 35mm f1.4", native_fstop: 1.40, text: include_str!("../../lens_files/Leica_35mm_F1.4_(Leica_Summilux_35mm_F1.4).lens") },
    LensFile { name: "Leica · Summilux-C 100mm T1.4", native_fstop: 1.40, text: include_str!("../../lens_files/Leica_100mm_(Leica_Summilux_C_100mm_T1.4).lens") },
    LensFile { name: "Meyer Görlitz · Kino Plasmat 100mm F2", native_fstop: 2.00, text: include_str!("../../lens_files/Meyer_100mm_F2_(Meyer_Optik_Gorlitz_100mm_F2_Kino_Plasmat).lens") },
    LensFile { name: "Meyer Görlitz · Orestor 135mm F2.8", native_fstop: 2.80, text: include_str!("../../lens_files/Meyer_135mm_F2.8_(Meyer_Optik_Gorlitz_135mm_F2.8_Orestor).lens") },
    LensFile { name: "Ross · F10 APO Process Xpres", native_fstop: 10.00, text: include_str!("../../lens_files/100mm_F10_(Ross_F10_APO_Process_Xpres).lens") },
    LensFile { name: "Voigtländer · Nokton 35mm F1.2 Asph", native_fstop: 1.24, text: include_str!("../../lens_files/Cosina_36mm_F1.24_(Cosina_Voigtlander_Nokton_35mm_F1.2_Aspherical).lens") },
    LensFile { name: "Voigtländer · Nokton 50mm F1.0 Asph", native_fstop: 1.00, text: include_str!("../../lens_files/Cosina_50mm_f1_(Cosina_Voigtlander_Nokton_50mm_F1.0_Aspherical).lens") },
    LensFile { name: "Zeiss · Arri Master Prime T1.3 50mm", native_fstop: 1.30, text: include_str!("../../lens_files/Zeiss_50mm_F1.3_(Arri_Zeiss_Master_Prime_T1.3_50mm).lens") },
    LensFile { name: "Zeiss · Biotar 50mm F1.4", native_fstop: 1.40, text: include_str!("../../lens_files/Zeiss_50mm_F1.4_(Zeiss_Biotar_50mm_F1.4).lens") },
    LensFile { name: "Zeiss · Tessar 100mm F4.5", native_fstop: 4.50, text: include_str!("../../lens_files/Zeiss_100mm_F4.5_Tessar.lens") },
    LensFile { name: "Zeiss · Ultra Prime Sonnar 135mm T1.9", native_fstop: 1.80, text: include_str!("../../lens_files/Zeiss_135mm_F1.8_(Zeiss_Ultra_Prime_Sonnar_T_135mm_T1.9).lens") },
];

/// The Lens dropdown's labels, derived from [`LENS_LIBRARY`] so the two can
/// never drift out of alignment.
pub static LENS_OPTIONS: [&str; LENS_LIBRARY.len()] = {
    let mut out = [""; LENS_LIBRARY.len()];
    let mut i = 0;
    while i < out.len() {
        out[i] = LENS_LIBRARY[i].name;
        i += 1;
    }
    out
};
