//! What an effect *is*, as a value rather than as a variant
//! (docs/impl/effect-registry.md §2.4, §2.6).
//!
//! **In plain terms.** Lumit used to know its effects the way a switchboard knows
//! its lines: one giant list written into the program, with a matching entry in
//! four other places, and no way for a line to exist that was not soldered in.
//! This module is the replacement — an effect is a **value** implementing
//! [`EffectDef`], and the catalogue is a list of those values. Looking an effect
//! up by name gives you something you can call, so the places that used to ask
//! "which of the thirty-four effects is this?" now simply ask the effect.
//!
//! The catalogue itself is deliberately an explicit list ([`catalogue!`] in
//! `catalogue.rs`) rather than something assembled before `main` runs: the
//! Add-effect menu, the command palette and the preset browser are all driven
//! from it in order (K-137), and an order that depended on link order would be a
//! visible defect. Effects that are *not* known at compile time — OFX plugins
//! (docs/12), and in time the user's own — arrive through the same trait object
//! at run time, which is the seam this arrangement exists for.

use super::params::Params;
use super::schema::EffectSchema;

/// One effect's behaviour: everything the engine needs of it that is not the
/// declaration itself.
///
/// Implemented once per effect, beside its declaration. The derive macro writes
/// [`schema`](EffectDef::schema) from the declared struct; the effect writes the
/// rest.
pub trait EffectDef: Sync + Send + 'static {
    /// The declaration: parameters, traits, category, version. Generated by
    /// `#[derive(Effect)]` from the parameter struct.
    fn schema(&self) -> &'static EffectSchema;

    /// The CPU reference implementation (docs/08 §1.6) — the oracle the WGSL
    /// kernel is tested against, and the degradation ladder's fallback rung
    /// (K-019).
    ///
    /// `rgba` is premultiplied scene-linear, four floats per pixel, row-major.
    /// The default is identity, which is correct for the orchestration-only
    /// effects (Posterize time, Accumulation motion blur) that have no image
    /// operation of their own.
    fn apply_cpu(&self, _rgba: &mut [f32], _w: u32, _h: u32, _p: Params<'_>) {}

    /// Whether this effect has an image operation at all. `false` for the
    /// orchestration-only effects, which the render path skips and the
    /// registry-agreement test excuses from needing a GPU entry.
    fn is_image_op(&self) -> bool {
        true
    }
}

/// The stable name an effect is looked up by, and the schema that answers to it.
///
/// A thin newtype over the catalogue slice so the lookup has one implementation
/// and one place to gain an index if 35 entries ever becomes 350. It is a linear
/// scan today, exactly as `fx::schema` was, and is called at edit time and once
/// per effect per frame — not per pixel.
pub struct Catalogue {
    defs: &'static [&'static dyn EffectDef],
}

impl Catalogue {
    /// Wrap a list of definitions. `catalogue!` calls this; nothing else should
    /// need to.
    pub const fn new(defs: &'static [&'static dyn EffectDef]) -> Self {
        Self { defs }
    }

    /// The definition named `match_name`, or `None` for a name this build does
    /// not know — an unknown effect is preserved as an inert placeholder, never
    /// an error (docs/08 §5, K-065).
    pub fn get(&self, match_name: &str) -> Option<&'static dyn EffectDef> {
        self.defs
            .iter()
            .copied()
            .find(|d| d.schema().match_name == match_name)
    }

    /// Every definition, in catalogue order.
    pub fn iter(&self) -> impl Iterator<Item = &'static dyn EffectDef> + '_ {
        self.defs.iter().copied()
    }

    /// How many effects this build knows.
    pub fn len(&self) -> usize {
        self.defs.len()
    }

    /// Whether the catalogue is empty (it never is; the method exists so `len`
    /// does not draw a clippy warning).
    pub fn is_empty(&self) -> bool {
        self.defs.is_empty()
    }
}

/// Build the built-in catalogue from a list of modules and their effect types.
///
/// The whole of registration: one line per effect, in menu order. Expands to the
/// `BUILTIN_DEFS` catalogue and the `BUILTINS` schema slice that the Add-effect
/// menu, the bridge and the preset paths have always read, so nothing downstream
/// changes shape.
#[macro_export]
macro_rules! catalogue {
    ($($def:expr),* $(,)?) => {
        /// Every built-in effect's definition, in menu order.
        pub static BUILTIN_DEFS: $crate::fx::Catalogue =
            $crate::fx::Catalogue::new(&[$(&$def),*]);
    };
}

/// The link between a declared parameter struct and its generated declaration.
///
/// `#[derive(Effect)]` implements this. `SCHEMA` is the declaration itself; the
/// behaviour lives on a small companion type implementing [`EffectDef`], written
/// beside the declaration, because an effect's CPU reference is real code and
/// generating it would only hide it.
pub trait EffectMetadata: Sized {
    /// The generated declaration.
    const SCHEMA: EffectSchema;

    /// Read this effect's parameters out of a resolved bag, filling each field
    /// from its declared default when the bag has no entry for it — which is
    /// what makes a project saved before a parameter existed load and render
    /// (K-258).
    fn read(p: Params<'_>) -> Self;
}
