//! lumit-bridge: the seam the Flutter frontend calls the Rust engine through
//! (docs/17-BRIDGE-CONTRACT.md).
//!
//! # In plain terms
//!
//! The Flutter application is written in Dart and cannot call Rust functions
//! directly. This crate is the translator between them. It compiles to a single
//! shared library (a `.dll` on Windows) that Dart loads at start-up. The whole
//! callable surface lives in [`api`]; `flutter_rust_bridge` generates the glue
//! on both sides from it (`frb_generated.rs` here, `lib/src/rust/` in
//! `flutter_ui` — regenerated, never edited). The hand-rolled v0 JSON seam this
//! crate started as is gone (deleted 2026-07-26).
//!
//! Dart holds opaque *reference handles* (a project, a composition, a layer)
//! and calls methods on them; errors come back as calm [`api::BridgeError`]
//! values, never a panic across the boundary.
//!
//! Engine crates never depend on this crate, and nothing depends on it — it is
//! a leaf over `lumit-core`, `lumit-project`, `lumit-render`, `lumit-audio`,
//! `lumit-eval` and (behind the default-on `media` feature) `lumit-media`
//! (docs/05-ARCHITECTURE.md).
//!
//! ## Module map
//!
//! - [`api`] — the frb surface: one module per panel-sized concern (project,
//!   composition, layer, effect, export, …) plus the render worker thread.
//! - [`edits`] — the layer and asset defaults shared by every add path.
//! - [`media`] — probing footage and decoding frames (`media` feature).
//! - `render` — the composited-comp Viewer path (`render` feature): turns
//!   `(comp, frame)` into an RGBA8 buffer through `lumit_render::headless`.
//! - [`framecache`] — the RAM tier of the three-tier frame cache (K-176, K-178):
//!   an LRU of finished frames named by a hash of their *content*, so an edit
//!   that cannot change a pixel throws nothing away and an undo is instantly
//!   valid. It also holds the cross-thread controls and mirrors for the two tiers
//!   the worker owns (the textures on the graphics card and the frames parked on
//!   disk), which back the Settings cache controls and the Timeline's cache bar.
//! - `profiling` — whether the worker is measuring per-layer and per-effect
//!   render times for the indicators (docs/13 §7.1).
//! - [`beats`] — the beat-detection worker: one analysis at a time, on a
//!   thread of its own, so a detection cannot sit on the pool every panel's
//!   reads share.
//! - [`peaks`] — the session's waveform peak cache: one multi-zoom summary per
//!   audio file, so a lane redraws at any zoom without decoding again (K-280).
//! - [`probe`] — the probe worker and the session's probe cache: footage is
//!   read for its vital statistics on a background thread, with a synchronous
//!   fallback so an op that needs the answer now still gets exactly the answer
//!   the prober gives.
//! - [`realtime`] — the adaptive playback tier decision core (K-171).
//! - [`audio`] — comp audio playback and the sample clock (`media` feature).
//! - [`export`] — the export runner and its progress reporting.

// flutter_rust_bridge's output, regenerated by `flutter_rust_bridge_codegen`
// whenever the `api` module changes — never edited by hand. It carries its own
// `#![allow(…)]` block for the style lints it trips, but not for the four panic
// lints this crate denies (docs/14 §4), so they are allowed here instead: an
// `#[allow]` on the `mod` item covers its contents, and putting it here rather
// than in the file means codegen cannot wipe it. The deny still applies in full
// to every hand-written module below.
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::unimplemented
)]
mod frb_generated;

// Pure defaults over lumit-core — no decoder, no GPU. It was gated on
// media+render when it also held the v0 ops that needed them.
#[cfg(feature = "media")]
mod audio;
mod beats;
mod edits;
mod export;
mod framecache;
mod media;
mod names;
mod peaks;
mod playback;
mod prefetch;
mod probe;
mod profiling;
mod proxy;
mod realtime;
mod render;

pub mod api;

use serde_json::json;

/// `{"ok":false,"error":"…"}`. serde escapes any control character, so the
/// resulting string never carries an interior NUL and always makes a `CString`.
pub(crate) fn err_json(message: impl AsRef<str>) -> String {
    json!({ "ok": false, "error": message.as_ref() }).to_string()
}
