// The engine's own words have to reach the translators too (K-303).
//
// Effect names, parameter names, choice options and the Add-effect menu's
// category headings are written in Rust, in `crates/lumit-core/src/fx/`, and
// come up over the bridge as plain English. `lib/l10n/engine_labels.dart` looks each
// one up by that English text. Nothing in the type system connects the two, so
// this test reads the engine's own label fixture (`crates/lumit-core/fx-labels.txt`,
// generated by the catalogue walk in `src/fx/labels.rs`) plus the keymap source,
// and fails if the engine can send a word the table has no entry for — which is
// what would otherwise leave a new effect shipping in English inside a
// translated application.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:lumit_flutter/l10n/engine_labels.dart';

/// Every user-facing string the effects schema can hand to the interface.
///
/// Read rather than imported: engine crates never depend on the frontend and the
/// frontend cannot call into `lumit-core` without the bridge, so the source text
/// is the only thing the two genuinely share.
Set<String> _engineLabels() {
  final labels = <String>{};

  // The effects schema's words come from the engine's own walk of the
  // catalogue, not from scraping source text: since the derive macro started
  // generating labels (K-381), most of them never appear as string literals
  // anywhere, so a scrape reads a fraction of the truth and cannot know it.
  // `crates/lumit-core/fx-labels.txt` is written by the catalogue itself and
  // `the_fx_label_fixture_matches_the_catalogue` keeps it honest; a schema
  // change fails that test until the fixture is regenerated, and then fails
  // this one until the table has the new word. Two tests, one chain.
  final fixture = File('../crates/lumit-core/fx-labels.txt');
  expect(fixture.existsSync(), isTrue,
      reason: 'run this from flutter_ui/, beside the crates/ tree; the '
          'fixture is generated by cargo test -p lumit-core '
          'regenerate_fx_label_fixture -- --ignored');
  for (final line in fixture.readAsLinesSync()) {
    if (line.isEmpty || line.startsWith('#')) continue;
    labels.add(line);
  }
  expect(labels.length, greaterThan(250),
      reason: 'the catalogue declares far more labels than this — the fixture '
          'has been truncated or hand-edited');
  // Settings -> Keymap: what each shortcut does, and the heading saying where
  // it is live. `"action.id" => "Play or pause"` and
  // `KeyContext::Global => "Anywhere"`.
  final keymap = File('../crates/lumit-keymap/src/lib.rs');
  expect(keymap.existsSync(), isTrue);
  final keymapSrc = keymap.readAsStringSync();
  for (final m
      in RegExp(r'"[a-z0-9._]+"\s*=>\s*"([^"]+)"').allMatches(keymapSrc)) {
    labels.add(m.group(1)!);
  }
  for (final m
      in RegExp(r'KeyContext::\w+\s*=>\s*"([^"]+)"').allMatches(keymapSrc)) {
    labels.add(m.group(1)!);
  }

  return labels;
}

/// Every reason the import report can raise, by the id it crosses the bridge
/// under (`lumit_import::Reason::key`, which is serde's own tag).
///
/// Read out of the Rust source the same way the keymap's descriptions are
/// above: nothing in either type system connects a variant here to a sentence
/// in `engine_labels.dart`, and the failure this catches is silent — a reason
/// added to the engine would simply show its English inside a translated
/// window, because the fallback is deliberately forgiving.
Set<String> _importReasonKeys() {
  final source = File('../crates/lumit-import/src/report.rs');
  expect(source.existsSync(), isTrue,
      reason: 'run this from flutter_ui/, beside the crates/ tree');
  final body = RegExp(r'pub enum Reason \{(.*?)\n\}', dotAll: true)
      .firstMatch(source.readAsStringSync())
      ?.group(1);
  expect(body, isNotNull, reason: 'the Reason enum has moved or been renamed');

  final keys = <String>{};
  for (final m
      in RegExp(r'^    ([A-Z]\w*)\s*[,{]', multiLine: true).allMatches(body!)) {
    // serde's `rename_all = "snake_case"`, which is what the engine sends.
    keys.add(m.group(1)!.replaceAllMapped(
        RegExp(r'(?<=.)([A-Z])'), (c) => '_${c.group(1)}').toLowerCase());
  }
  expect(keys.length, greaterThan(30),
      reason: 'the enum declares far more reasons than this — the scrape has '
          'stopped matching the source');
  return keys;
}

/// Every way the colour config can be refused, by the id it crosses the bridge
/// under (`lumit_colour::ColourError::key`, the variant's own name in snake
/// case), plus the one the renderer raises itself.
///
/// Read out of the Rust source the way the import reasons are, and for the same
/// reason: nothing in either type system connects a variant there to a sentence
/// in `engine_labels.dart`, and the failure is silent — a config refused for a
/// reason this build has no sentence for shows the engine's English inside a
/// translated window.
Set<String> _colourRefusalKeys() {
  final source = File('../crates/lumit-colour/src/error.rs');
  expect(source.existsSync(), isTrue,
      reason: 'run this from flutter_ui/, beside the crates/ tree');
  final body = RegExp(r'pub enum ColourError \{(.*?)\n\}', dotAll: true)
      .firstMatch(source.readAsStringSync())
      ?.group(1);
  expect(body, isNotNull,
      reason: 'the ColourError enum has moved or been renamed');

  final keys = <String>{};
  for (final m
      in RegExp(r'^    ([A-Z]\w*)\s*[,{]', multiLine: true).allMatches(body!)) {
    keys.add(m.group(1)!.replaceAllMapped(
        RegExp(r'(?<=.)([A-Z])'), (c) => '_${c.group(1)}').toLowerCase());
  }
  expect(keys.length, greaterThan(15),
      reason: 'the enum declares far more refusals than this — the scrape has '
          'stopped matching the source');

  // The one refusal that is not a ColourError: the file the project names was
  // not there to be parsed at all (`lumit_render::colour::load`).
  final renderer = File('../crates/lumit-render/src/colour.rs');
  expect(renderer.existsSync(), isTrue);
  expect(renderer.readAsStringSync().contains('"config_unreadable"'), isTrue,
      reason: 'the renderer no longer raises config_unreadable by that id');
  keys.add('config_unreadable');

  return keys;
}

void main() {
  test('every import report reason has a sentence to be translated', () {
    final missing = _importReasonKeys().where((k) => !hasImportReason(k)).toList()
      ..sort();
    expect(
      missing,
      isEmpty,
      reason: 'these are variants of lumit_import::Reason with no case in '
          "importReason() in lib/l10n/engine_labels.dart. Add each one's "
          'sentence there and the matching key to lib/l10n/app_en.arb, or the '
          'row ships in English inside a translated window.',
    );
  });

  test('a reason with no sentence says so, so the caller can fall back', () {
    expect(importReason('not_a_real_reason', const {}), isNull);
    expect(hasImportReason('blend_mode_unavailable'), isTrue);
  });

  test('every label the engine can send has a translation entry', () {
    final missing = _engineLabels().where((l) => !hasEngineLabel(l)).toList()
      ..sort();
    expect(
      missing,
      isEmpty,
      reason: 'these appear in the effects schema but not in '
          'lib/l10n/engine_labels.dart. Add each one to the table there, and add '
          'the matching key to lib/l10n/app_en.arb, or it ships untranslated.',
    );
  });

  test('a label with no entry comes back as it arrived', () {
    // The fallback is what keeps a schema change from blanking the panel between
    // the effect landing and this test being satisfied.
    expect(engineLabel('Not a real effect'), 'Not a real effect');
    expect(engineLabel(''), '');
  });


  test('every colour config refusal has a sentence to be translated', () {
    final missing =
        _colourRefusalKeys().where((k) => !hasColourProblem(k)).toList()..sort();
    expect(
      missing,
      isEmpty,
      reason: 'these are ways lumit-colour can refuse a config with no case in '
          "colourProblem() in lib/l10n/engine_labels.dart. Add each one's "
          'sentence there and the matching key to lib/l10n/app_en.arb, or the '
          'Colour row ships in English inside a translated window.',
    );
  });

  test('a colour refusal with no sentence says so, so the caller can fall back',
      () {
    expect(colourProblem('not_a_real_refusal', const {}), isNull);
    expect(hasColourProblem('unsupported_transform'), isTrue);
  });

  test('a config supplies the names, and its names are never translated', () {
    // "Alpha" is an effect parameter this application translates. A colour
    // space of that name in somebody's config file is not that word, and must
    // come back exactly as it arrived (K-303).
    expect(hasEngineLabel('Alpha'), isTrue);
    expect(
      colourProblem('unknown_colour_space', const {'name': 'Alpha'}),
      contains('Alpha'),
    );
    // And the space a refusal surfaced in wraps the sentence rather than
    // replacing it.
    final wrapped = colourProblem(
        'lut_file_not_found', const {'name': 'shot.spi3d', 'in_space': 'graded'});
    expect(wrapped, contains('shot.spi3d'));
    expect(wrapped, contains('graded'));
  });

  test('a known label resolves through the table', () {
    expect(hasEngineLabel('Gaussian blur'), isTrue);
    expect(engineLabel('Gaussian blur'), 'Gaussian blur');
  });
}
