// The engine's own words have to reach the translators too (K-303).
//
// Effect names, parameter names, choice options and the Add-effect menu's
// category headings are written in Rust, in `crates/lumit-core/src/fx/`, and
// come up over the bridge as plain English. `lib/l10n/engine_labels.dart` looks each
// one up by that English text. Nothing in the type system connects the two, so
// this test reads the engine's own label fixture (`crates/lumit-core/fx-labels.txt`,
// generated by the catalogue walk in `src/fx/labels.rs`) plus the keymap source,
// and fails if the engine can send a word the table has no entry for — which is
// what would otherwise leave a new effect shipping in English inside a
// translated application.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:lumit_flutter/l10n/engine_labels.dart';

/// Every user-facing string the effects schema can hand to the interface.
///
/// Read rather than imported: engine crates never depend on the frontend and the
/// frontend cannot call into `lumit-core` without the bridge, so the source text
/// is the only thing the two genuinely share.
Set<String> _engineLabels() {
  final labels = <String>{};

  // The effects schema's words come from the engine's own walk of the
  // catalogue, not from scraping source text: since the derive macro started
  // generating labels (K-381), most of them never appear as string literals
  // anywhere, so a scrape reads a fraction of the truth and cannot know it.
  // `crates/lumit-core/fx-labels.txt` is written by the catalogue itself and
  // `the_fx_label_fixture_matches_the_catalogue` keeps it honest; a schema
  // change fails that test until the fixture is regenerated, and then fails
  // this one until the table has the new word. Two tests, one chain.
  final fixture = File('../crates/lumit-core/fx-labels.txt');
  expect(fixture.existsSync(), isTrue,
      reason: 'run this from flutter_ui/, beside the crates/ tree; the '
          'fixture is generated by cargo test -p lumit-core '
          'regenerate_fx_label_fixture -- --ignored');
  for (final line in fixture.readAsLinesSync()) {
    if (line.isEmpty || line.startsWith('#')) continue;
    labels.add(line);
  }
  expect(labels.length, greaterThan(250),
      reason: 'the catalogue declares far more labels than this — the fixture '
          'has been truncated or hand-edited');
  // Settings -> Keymap: what each shortcut does, and the heading saying where
  // it is live. `"action.id" => "Play or pause"` and
  // `KeyContext::Global => "Anywhere"`.
  final keymap = File('../crates/lumit-keymap/src/lib.rs');
  expect(keymap.existsSync(), isTrue);
  final keymapSrc = keymap.readAsStringSync();
  for (final m
      in RegExp(r'"[a-z0-9._]+"\s*=>\s*"([^"]+)"').allMatches(keymapSrc)) {
    labels.add(m.group(1)!);
  }
  for (final m
      in RegExp(r'KeyContext::\w+\s*=>\s*"([^"]+)"').allMatches(keymapSrc)) {
    labels.add(m.group(1)!);
  }

  return labels;
}

void main() {
  test('every label the engine can send has a translation entry', () {
    final missing = _engineLabels().where((l) => !hasEngineLabel(l)).toList()
      ..sort();
    expect(
      missing,
      isEmpty,
      reason: 'these appear in the effects schema but not in '
          'lib/l10n/engine_labels.dart. Add each one to the table there, and add '
          'the matching key to lib/l10n/app_en.arb, or it ships untranslated.',
    );
  });

  test('a label with no entry comes back as it arrived', () {
    // The fallback is what keeps a schema change from blanking the panel between
    // the effect landing and this test being satisfied.
    expect(engineLabel('Not a real effect'), 'Not a real effect');
    expect(engineLabel(''), '');
  });

  test('a known label resolves through the table', () {
    expect(hasEngineLabel('Gaussian blur'), isTrue);
    expect(engineLabel('Gaussian blur'), 'Gaussian blur');
  });
}
