// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `flatten_runtime`, `flatten`, `refusal`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Where addons live, so Dart and Rust cannot disagree about the folder.
/// `None` only when the platform has no home directory.
String? addonsDir() => BridgeLib.instance.api.crateApiAddonsAddonsDir();

/// Every installed addon, by id, with the staging leftovers of a build that
/// died halfway swept on the way past.
List<BridgeAddon> addonList() =>
    BridgeLib.instance.api.crateApiAddonsAddonList();

/// Install an addon from its manifest and the files Dart fetched and verified,
/// one file per download of this platform's block, in the manifest's order.
///
/// Deliberately not `#[frb(sync)]`: unpacking the largest pack is a couple of
/// seconds, so it rides the frb worker pool the way `rescan_plugins` does
/// rather than holding the interface thread.
///
/// # Errors
///
/// [`BridgeError::AddonBusy`] while another install is running, and
/// [`BridgeError::AddonInvalid`] with the engine's own sentence for a manifest
/// this build will not take, a file that is not the size the manifest says, or
/// a download the unpack could not finish.
Future<void> addonInstall(
        {required String manifest, required List<String> files}) =>
    BridgeLib.instance.api
        .crateApiAddonsAddonInstall(manifest: manifest, files: files);

/// Delete an addon's folder. The row goes; nothing else is touched.
///
/// # Errors
///
/// [`BridgeError::AddonMissing`] when nothing of that id is installed, and
/// [`BridgeError::AddonInvalid`] when the folder will not delete.
void addonRemove({required String id}) =>
    BridgeLib.instance.api.crateApiAddonsAddonRemove(id: id);

/// What the runtime row reads right now, without asking the library for
/// anything.
BridgeRuntimeStatus addonRuntime() =>
    BridgeLib.instance.api.crateApiAddonsAddonRuntime();

/// Load the runtime library now and say what happened.
///
/// Not `#[frb(sync)]`: opening a shared library and initialising a provider is
/// disk and driver work, and it happens once per run.
Future<BridgeRuntimeStatus> addonRuntimeLoad() =>
    BridgeLib.instance.api.crateApiAddonsAddonRuntimeLoad();

/// One installed addon, as the page's row draws it.
class BridgeAddon {
  /// Its folder name, and what [`addon_remove`] takes.
  final String id;
  final BridgeAddonKind kind;

  /// What the row is titled.
  final String name;

  /// The addon's own version, beside the name.
  final String version;

  /// One line saying what it does.
  final String summary;

  /// An SPDX expression or a short name; shown with [`BridgeAddon::licence_url`].
  final String licence;
  final String licenceUrl;

  /// What the download was, in bytes, for the size on the description line.
  final BigInt sizeBytes;

  /// `synthesis`, `depth`, `matte` or `segmentation`, and empty for the
  /// runtime. A word the engine sends, so it has an `engine_labels` entry.
  final String task;

  /// A file the manifest lists is missing or the wrong size. The row stays,
  /// marked, because the fix is to install it again.
  final bool broken;

  const BridgeAddon({
    required this.id,
    required this.kind,
    required this.name,
    required this.version,
    required this.summary,
    required this.licence,
    required this.licenceUrl,
    required this.sizeBytes,
    required this.task,
    required this.broken,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      name.hashCode ^
      version.hashCode ^
      summary.hashCode ^
      licence.hashCode ^
      licenceUrl.hashCode ^
      sizeBytes.hashCode ^
      task.hashCode ^
      broken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAddon &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          name == other.name &&
          version == other.version &&
          summary == other.summary &&
          licence == other.licence &&
          licenceUrl == other.licenceUrl &&
          sizeBytes == other.sizeBytes &&
          task == other.task &&
          broken == other.broken;
}

/// Which of the two things an addon is.
enum BridgeAddonKind {
  /// ONNX Runtime and its provider libraries. Exactly one may be installed.
  runtime,

  /// One analysis model, with its licence and its tensor contract.
  model,
  ;
}

/// What the runtime row says.
enum BridgeRuntimeState {
  /// Nothing is installed. Every model row's button reads "Needs the
  /// runtime" until this changes.
  missing,

  /// The folder is there and nothing has asked for it yet.
  present,

  /// The library has loaded since Lumit started.
  loaded,

  /// The library was asked and refused; see [`BridgeRuntimeStatus::detail`].
  failed,
  ;
}

/// The runtime row's whole reading, in one crossing.
class BridgeRuntimeStatus {
  final BridgeRuntimeState state;

  /// Which execution provider a session tries first: `DirectML`, `CoreML`
  /// or `CPU`. Empty until the library has loaded.
  final String provider;

  /// What the installed runtime addon pins itself at. Empty until then.
  final String version;

  /// The library's own sentence when it would not load, untranslated, and
  /// marked as its own words where it is shown. Empty otherwise.
  final String detail;

  const BridgeRuntimeStatus({
    required this.state,
    required this.provider,
    required this.version,
    required this.detail,
  });

  @override
  int get hashCode =>
      state.hashCode ^ provider.hashCode ^ version.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRuntimeStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          provider == other.provider &&
          version == other.version &&
          detail == other.detail;
}
