// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'effect.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `animator_from`, `colour_of`, `linear_of`, `paragraph_of`, `read_animator`, `read_paragraph`, `read_style`, `reference_point`, `restyle_shift`, `shift_property`, `style_of`, `text_document_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The style a text layer has before anything is styled.
BridgeTextStyle defaultTextStyle() =>
    BridgeLib.instance.api.crateApiAssetsDefaultTextStyle();

/// The paragraph a text layer has before anything is set.
BridgeParagraphStyle defaultParagraphStyle() =>
    BridgeLib.instance.api.crateApiAssetsDefaultParagraphStyle();

/// The font families installed on this machine, sorted for a menu. Not sync,
/// since the first call asks the system for its fonts.
Future<List<String>> textFontFamilies() =>
    BridgeLib.instance.api.crateApiAssetsTextFontFamilies();

/// The faces of one family, such as Regular, Bold and Bold Italic. Empty when
/// the family isn't installed here.
Future<List<String>> textFontFaces({required String family}) =>
    BridgeLib.instance.api.crateApiAssetsTextFontFaces(family: family);

/// Lay out `text` the way the engine draws it in this style, with or without
/// the room animators get round it. The first call with a font loads it.
BridgeTextBlock measureText(
        {required String text,
        required double size,
        required BridgeTextStyle style,
        required BridgeParagraphStyle paragraph,
        required bool animated}) =>
    BridgeLib.instance.api.crateApiAssetsMeasureText(
        text: text,
        size: size,
        style: style,
        paragraph: paragraph,
        animated: animated);

/// Capitals: as typed, all capitals, or small capitals for the lower case.
enum BridgeCaps {
  normal,
  all,
  small,
  ;
}

/// A colour as the document stores it: scene-linear RGBA, which may exceed 1
/// (an HDR tint) or dip below 0 (a lift), so it is not a byte triple.
class BridgeColourRgba {
  final double r;
  final double g;
  final double b;
  final double a;

  const BridgeColourRgba({
    required this.r,
    required this.g,
    required this.b,
    required this.a,
  });

  @override
  int get hashCode => r.hashCode ^ g.hashCode ^ b.hashCode ^ a.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeColourRgba &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          g == other.g &&
          b == other.b &&
          a == other.a;
}

/// Whether pairs of letters are pulled together by the font's own kerning.
enum BridgeKerning {
  off,
  metrics,
  ;
}

/// How the lines of a text layer are laid out against each other. All px.
class BridgeParagraphStyle {
  final BridgeTextAlign align;
  final double indentLeft;
  final double indentRight;
  final double indentFirst;
  final double spaceBefore;
  final double spaceAfter;

  const BridgeParagraphStyle({
    required this.align,
    required this.indentLeft,
    required this.indentRight,
    required this.indentFirst,
    required this.spaceBefore,
    required this.spaceAfter,
  });

  @override
  int get hashCode =>
      align.hashCode ^
      indentLeft.hashCode ^
      indentRight.hashCode ^
      indentFirst.hashCode ^
      spaceBefore.hashCode ^
      spaceAfter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeParagraphStyle &&
          runtimeType == other.runtimeType &&
          align == other.align &&
          indentLeft == other.indentLeft &&
          indentRight == other.indentRight &&
          indentFirst == other.indentFirst &&
          spaceBefore == other.spaceBefore &&
          spaceAfter == other.spaceAfter;
}

/// Which stretch of the words an animator reaches, in per cent of the run.
class BridgeRangeSelector {
  final BridgeScalar start;
  final BridgeScalar end;
  final BridgeScalar offset;
  final BridgeSelectorBasis basis;
  final BridgeSelectorShape shape;

  const BridgeRangeSelector({
    required this.start,
    required this.end,
    required this.offset,
    required this.basis,
    required this.shape,
  });

  @override
  int get hashCode =>
      start.hashCode ^
      end.hashCode ^
      offset.hashCode ^
      basis.hashCode ^
      shape.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRangeSelector &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          offset == other.offset &&
          basis == other.basis &&
          shape == other.shape;
}

/// Where the letters sit against the baseline.
enum BridgeScript {
  normal,
  superscript,
  subscript,
  ;
}

/// What a range selector counts.
enum BridgeSelectorBasis {
  characters,
  words,
  ;
}

/// How a range selector's weight falls off across its range.
enum BridgeSelectorShape {
  square,
  ramp,
  ;
}

/// A solid asset's definition.
class BridgeSolidDef {
  final String name;
  final BridgeColourRgba colour;
  final int width;
  final int height;

  const BridgeSolidDef({
    required this.name,
    required this.colour,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      name.hashCode ^ colour.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSolidDef &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          colour == other.colour &&
          width == other.width &&
          height == other.height;
}

/// Which side the lines of a block line up on.
enum BridgeTextAlign {
  left,
  centre,
  right,
  ;
}

/// One animator group: what a reached letter is asked to do, and the range
/// saying which letters those are.
///
/// Every animator carries all five property groups — the decision entry argues
/// why there is no menu of properties to add them from — defaulted to values
/// that change nothing: no push, no turn, 100 % size, 100 % opacity, no tint.
class BridgeTextAnimator {
  final String name;
  final BridgeRangeSelector selector;
  final BridgeScalar positionX;
  final BridgeScalar positionY;
  final BridgeScalar rotation;
  final BridgeScalar scaleX;
  final BridgeScalar scaleY;
  final BridgeScalar opacity;
  final BridgeScalar fillR;
  final BridgeScalar fillG;
  final BridgeScalar fillB;

  const BridgeTextAnimator({
    required this.name,
    required this.selector,
    required this.positionX,
    required this.positionY,
    required this.rotation,
    required this.scaleX,
    required this.scaleY,
    required this.opacity,
    required this.fillR,
    required this.fillG,
    required this.fillB,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      selector.hashCode ^
      positionX.hashCode ^
      positionY.hashCode ^
      rotation.hashCode ^
      scaleX.hashCode ^
      scaleY.hashCode ^
      opacity.hashCode ^
      fillR.hashCode ^
      fillG.hashCode ^
      fillB.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTextAnimator &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          selector == other.selector &&
          positionX == other.positionX &&
          positionY == other.positionY &&
          rotation == other.rotation &&
          scaleX == other.scaleX &&
          scaleY == other.scaleY &&
          opacity == other.opacity &&
          fillR == other.fillR &&
          fillG == other.fillG &&
          fillB == other.fillB;
}

/// Where a block of text sits inside its layer, in layer pixels. Styled or
/// not, one line or several, it's the engine's own layout.
class BridgeTextBlock {
  /// The layer's size: the raster the engine draws the block into.
  final double width;
  final double height;

  /// How far a caret reaches above and below a baseline.
  final double ascent;
  final double descent;

  /// The left and right edges of the words' own box.
  final double left;
  final double right;

  /// One per line, top to bottom. There is always at least one.
  final List<BridgeTextBlockLine> lines;

  const BridgeTextBlock({
    required this.width,
    required this.height,
    required this.ascent,
    required this.descent,
    required this.left,
    required this.right,
    required this.lines,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      ascent.hashCode ^
      descent.hashCode ^
      left.hashCode ^
      right.hashCode ^
      lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTextBlock &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          ascent == other.ascent &&
          descent == other.descent &&
          left == other.left &&
          right == other.right &&
          lines == other.lines;
}

/// One line of a laid out block.
class BridgeTextBlockLine {
  /// The index of the line's first character in the whole text, counted in
  /// characters.
  final int start;

  /// The baseline, measured down from the layer's top edge.
  final double baseline;

  /// The x of every gap between the line's letters, one more than it has
  /// characters. The break that ends a line isn't one of them.
  final Float64List carets;

  const BridgeTextBlockLine({
    required this.start,
    required this.baseline,
    required this.carets,
  });

  @override
  int get hashCode => start.hashCode ^ baseline.hashCode ^ carets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTextBlockLine &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          baseline == other.baseline &&
          carets == other.carets;
}

/// A text layer's document (v1: one styled run — docs/03 §9.1).
class BridgeTextDocument {
  final String text;

  /// When set, the layer's words come from this expression at each frame
  /// rather than from `text`, which is kept so switching the expression off
  /// restores what was typed.
  final String? expression;

  /// Pixel size at natural scale.
  final double size;
  final BridgeColourRgba fill;

  /// The mask **on this layer** whose curve the glyphs run along.
  /// Unset lays the line straight, and so does a mask id that names nothing.
  final UuidValue? path;

  /// How far along that curve the line starts, px@comp, on the composition's
  /// clock like every other animatable channel that crosses here.
  final BridgeScalar pathOffset;

  /// The animator groups moving the letters separately. Empty is the
  /// ordinary text layer.
  final List<BridgeTextAnimator> animators;

  /// The font, spacing, scale and outline of the letters.
  final BridgeTextStyle style;

  /// Alignment, indents and the room between lines.
  final BridgeParagraphStyle paragraph;

  const BridgeTextDocument({
    required this.text,
    this.expression,
    required this.size,
    required this.fill,
    this.path,
    required this.pathOffset,
    required this.animators,
    required this.style,
    required this.paragraph,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      expression.hashCode ^
      size.hashCode ^
      fill.hashCode ^
      path.hashCode ^
      pathOffset.hashCode ^
      animators.hashCode ^
      style.hashCode ^
      paragraph.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTextDocument &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          expression == other.expression &&
          size == other.size &&
          fill == other.fill &&
          path == other.path &&
          pathOffset == other.pathOffset &&
          animators == other.animators &&
          style == other.style &&
          paragraph == other.paragraph;
}

/// How a text layer's letters are set. One style for the whole layer.
class BridgeTextStyle {
  /// The font family as the system lists it. Empty is the built-in Inter.
  final String family;

  /// The face inside the family, such as "Bold Italic". Empty is the
  /// family's regular face.
  final String face;

  /// Baseline to baseline in px. Unset is auto, 120 % of the size.
  final double? leading;
  final BridgeKerning kerning;

  /// Extra space after every letter, in thousandths of an em.
  final double tracking;

  /// Per cent.
  final double scaleX;

  /// Per cent.
  final double scaleY;

  /// Px the letters are lifted off the baseline, positive is up.
  final double baselineShift;
  final BridgeCaps caps;
  final BridgeScript script;
  final bool fauxBold;
  final bool fauxItalic;
  final bool ligatures;

  /// Off draws the outline alone.
  final bool fillOn;
  final bool strokeOn;
  final BridgeColourRgba stroke;

  /// Px, centred on the letter's edge.
  final double strokeWidth;

  /// The outline is drawn over the fill. Off puts the fill on top.
  final bool strokeOver;

  const BridgeTextStyle({
    required this.family,
    required this.face,
    this.leading,
    required this.kerning,
    required this.tracking,
    required this.scaleX,
    required this.scaleY,
    required this.baselineShift,
    required this.caps,
    required this.script,
    required this.fauxBold,
    required this.fauxItalic,
    required this.ligatures,
    required this.fillOn,
    required this.strokeOn,
    required this.stroke,
    required this.strokeWidth,
    required this.strokeOver,
  });

  @override
  int get hashCode =>
      family.hashCode ^
      face.hashCode ^
      leading.hashCode ^
      kerning.hashCode ^
      tracking.hashCode ^
      scaleX.hashCode ^
      scaleY.hashCode ^
      baselineShift.hashCode ^
      caps.hashCode ^
      script.hashCode ^
      fauxBold.hashCode ^
      fauxItalic.hashCode ^
      ligatures.hashCode ^
      fillOn.hashCode ^
      strokeOn.hashCode ^
      stroke.hashCode ^
      strokeWidth.hashCode ^
      strokeOver.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTextStyle &&
          runtimeType == other.runtimeType &&
          family == other.family &&
          face == other.face &&
          leading == other.leading &&
          kerning == other.kerning &&
          tracking == other.tracking &&
          scaleX == other.scaleX &&
          scaleY == other.scaleY &&
          baselineShift == other.baselineShift &&
          caps == other.caps &&
          script == other.script &&
          fauxBold == other.fauxBold &&
          fauxItalic == other.fauxItalic &&
          ligatures == other.ligatures &&
          fillOn == other.fillOn &&
          strokeOn == other.strokeOn &&
          stroke == other.stroke &&
          strokeWidth == other.strokeWidth &&
          strokeOver == other.strokeOver;
}
