// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `document_snapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Pause. The clock holds its position, so play resumes from here.
void audioPause() => BridgeLib.instance.api.crateApiAudioAudioPause();

/// Move the clock to `secs` — a scrub. The play state is untouched, so
/// scrubbing while playing keeps playing.
void audioSeek({required double secs}) =>
    BridgeLib.instance.api.crateApiAudioAudioSeek(secs: secs);

/// Stop: pause and rewind to the start.
void audioStop() => BridgeLib.instance.api.crateApiAudioAudioStop();

/// Where playback is. Polled every tick, so it allocates nothing and takes one
/// short lock.
BridgeAudioClock audioClock() =>
    BridgeLib.instance.api.crateApiAudioAudioClock();

/// Where playback is, as the transport needs to know it.
class BridgeAudioClock {
  /// Seconds into the composition.
  final double seconds;
  final bool playing;

  /// False while no mix is loaded — no device, nothing prepared yet, or a
  /// prepare still running. The caller should drive the picture from its own
  /// clock until this turns true, and follow `seconds` after that.
  final bool loaded;

  const BridgeAudioClock({
    required this.seconds,
    required this.playing,
    required this.loaded,
  });

  @override
  int get hashCode => seconds.hashCode ^ playing.hashCode ^ loaded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAudioClock &&
          runtimeType == other.runtimeType &&
          seconds == other.seconds &&
          playing == other.playing &&
          loaded == other.loaded;
}
