// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `document_snapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Pause. The clock holds its position, so play resumes from here.
void audioPause() => BridgeLib.instance.api.crateApiAudioAudioPause();

/// Move the clock to `secs` — a scrub. The play state is untouched, so
/// scrubbing while playing keeps playing.
void audioSeek({required double secs}) =>
    BridgeLib.instance.api.crateApiAudioAudioSeek(secs: secs);

/// Stop: pause and rewind to the start.
void audioStop() => BridgeLib.instance.api.crateApiAudioAudioStop();

/// Where playback is. Polled every tick, so it allocates nothing and takes one
/// short lock.
BridgeAudioClock audioClock() =>
    BridgeLib.instance.api.crateApiAudioAudioClock();

/// What the mix is doing: one entry per sounding strip in the order the mixer
/// draws them, then the master last.
///
/// Meant to be polled while the mixer is on screen — it takes one short lock
/// and reads lock-free atomics the audio callback publishes once per buffer.
/// Empty when nothing is loaded or the machine has no output: a mixer with no
/// strips, not a fault. A paused transport reads silence rather than freezing
/// on whatever was playing.
List<BridgeAudioMeter> audioMeters() =>
    BridgeLib.instance.api.crateApiAudioAudioMeters();

/// Put every clip light out. Nothing else about the mix changes — this is the
/// desk's "I have seen it", not a fix for what lit them.
void resetAudioClip() => BridgeLib.instance.api.crateApiAudioResetAudioClip();

/// Every output the machine offers, and which one is in use.
///
/// Asking the sound system is not free, so this is a call to make when a list
/// is about to be shown — never in a rebuild path.
BridgeAudioDevices listAudioDevices() =>
    BridgeLib.instance.api.crateApiAudioListAudioDevices();

/// Play through the output with this id; an empty string means the system
/// default, which is what Lumit ships following.
///
/// Sound stops until the next play: a stream cannot be moved from one device to
/// another, so the open one is closed and the next mix opens the new one. The
/// choice is the machine's, not the project's — the frontend stores it in the
/// settings file and hands it over on every boot, which is a no-op when it has
/// not changed.
void setAudioDevice({required String id}) =>
    BridgeLib.instance.api.crateApiAudioSetAudioDevice(id: id);

/// Where playback is, as the transport needs to know it.
class BridgeAudioClock {
  /// Seconds into the composition.
  final double seconds;
  final bool playing;

  /// False while no mix is loaded — no device, nothing prepared yet, or a
  /// prepare still running. The caller should drive the picture from its own
  /// clock until this turns true, and follow `seconds` after that.
  final bool loaded;

  const BridgeAudioClock({
    required this.seconds,
    required this.playing,
    required this.loaded,
  });

  @override
  int get hashCode => seconds.hashCode ^ playing.hashCode ^ loaded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAudioClock &&
          runtimeType == other.runtimeType &&
          seconds == other.seconds &&
          playing == other.playing &&
          loaded == other.loaded;
}

/// One output the machine can play through.
class BridgeAudioDevice {
  /// What `set_audio_device` is called with. Stable across restarts, so the
  /// frontend can store it and hand it back; opaque otherwise.
  final String id;

  /// What the sound system calls it, for the list.
  final String name;

  /// Whether this is the one the system plays through when nothing is chosen.
  final bool isDefault;

  const BridgeAudioDevice({
    required this.id,
    required this.name,
    required this.isDefault,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAudioDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDefault == other.isDefault;
}

/// What the machine offers, and what Lumit is actually playing through.
class BridgeAudioDevices {
  final List<BridgeAudioDevice> devices;

  /// The id sound comes out of, or empty when the machine has no output at
  /// all. Not necessarily the id that was chosen — see `fell_back`.
  final String active;

  /// True when a device was chosen and it is not there any more, so the
  /// system default is being played through instead. The choice is kept, not
  /// rewritten: plug the device back in and it is used again.
  final bool fellBack;

  const BridgeAudioDevices({
    required this.devices,
    required this.active,
    required this.fellBack,
  });

  @override
  int get hashCode => devices.hashCode ^ active.hashCode ^ fellBack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAudioDevices &&
          runtimeType == other.runtimeType &&
          devices == other.devices &&
          active == other.active &&
          fellBack == other.fellBack;
}

/// One mixer strip's bars, or the master's (docs/09 §3.1, K-683).
///
/// **Linear sample amplitudes, not decibels.** The mix works in amplitudes;
/// a bar that wants dB converts where it is drawn, once, rather than the
/// engine guessing which scale the drawing wanted. 1.0 is full scale.
class BridgeAudioMeter {
  /// The layer this row belongs to, or an empty string for the master. A
  /// Precomp layer's row covers everything inside it — the mixer draws the
  /// rows of the comp in front of you.
  final String layer;

  /// Loudest sample of the last buffer (about ten milliseconds), left then
  /// right. The little line that rests above the bar for a few seconds is
  /// the panel's own hold, not this.
  final double peakLeft;
  final double peakRight;

  /// Root-mean-square of the same buffer — the body of the bar.
  final double rmsLeft;
  final double rmsRight;

  /// Something has reached the master ceiling since the clip lights were
  /// last put out, so the limiter is holding sound back. Sticky until
  /// [`reset_audio_clip`], because a light that cleared itself would only
  /// report an overload to somebody who happened to be looking.
  final bool clipped;

  const BridgeAudioMeter({
    required this.layer,
    required this.peakLeft,
    required this.peakRight,
    required this.rmsLeft,
    required this.rmsRight,
    required this.clipped,
  });

  @override
  int get hashCode =>
      layer.hashCode ^
      peakLeft.hashCode ^
      peakRight.hashCode ^
      rmsLeft.hashCode ^
      rmsRight.hashCode ^
      clipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAudioMeter &&
          runtimeType == other.runtimeType &&
          layer == other.layer &&
          peakLeft == other.peakLeft &&
          peakRight == other.peakRight &&
          rmsLeft == other.rmsLeft &&
          rmsRight == other.rmsRight &&
          clipped == other.clipped;
}
