// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'composition.dart';
import 'effect.dart';
import 'folder.dart';
import 'footage.dart';
import 'graph.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'project_item.dart';
import 'solid.dart';

// These functions are ignored because they are not marked as `pub`: `core`, `core`, `of`, `of`, `port_of`, `read_comp_graph`, `read_node`, `wiring_into`, `wiring_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// One wire: an output socket of one box into an input socket of another.
class BridgeCompEdge {
  final UuidValue from;
  final String fromPort;
  final UuidValue to;
  final String toPort;

  const BridgeCompEdge({
    required this.from,
    required this.fromPort,
    required this.to,
    required this.toPort,
  });

  @override
  int get hashCode =>
      from.hashCode ^ fromPort.hashCode ^ to.hashCode ^ toPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCompEdge &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          fromPort == other.fromPort &&
          to == other.to &&
          toPort == other.toPort;
}

/// A node graph's whole structure, in one crossing.
class BridgeCompGraph {
  /// Every box, in document order: the order the wiring was written in, and
  /// the order an Input's row is drawn in outside the graph.
  final List<BridgeCompNode> nodes;
  final BridgeCompWiring wiring;

  const BridgeCompGraph({
    required this.nodes,
    required this.wiring,
  });

  @override
  int get hashCode => nodes.hashCode ^ wiring.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCompGraph &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          wiring == other.wiring;
}

/// One box on the canvas, as it is drawn.
///
/// Derived, not stored: the engine works this out from the graph and the
/// project each time it is asked, so there is nothing here to write back. What
/// the user edits lives in [`BridgeCompWiring`], and an Fx box's parameters ride
/// the ordinary staged-instance path.
class BridgeCompNode {
  final UuidValue id;
  final BridgeCompNodeKind kind;

  /// The project item a Read box brings in, so the panel can open it or draw
  /// its kind. `None` on every other kind, and on a Read whose item somebody
  /// deleted.
  final ItemReference? item;

  /// True for a Read box whose item is no longer in the project. It draws
  /// transparent and wears the missing mark, exactly as a Precomp layer of a
  /// deleted comp does.
  final bool missing;

  /// The effect's schema key, empty for every box that is not an Fx. Not
  /// display text: `label` is.
  final String matchName;

  /// What the box is called, in English: the item's name for a Read, the
  /// Input's own word, the effect's label for an Fx, and *Output* for the
  /// Output. Empty for a Read whose item has gone, there being no name left
  /// to draw.
  final String label;

  /// The user's own name for this box, shown in place of `label`.
  final String? customName;

  /// False draws the border dashed, the bypass tick being off. Always true
  /// for the three boxes that cannot be bypassed.
  final bool enabled;
  final List<BridgePort> inputs;
  final List<BridgePort> outputs;

  const BridgeCompNode({
    required this.id,
    required this.kind,
    this.item,
    required this.missing,
    required this.matchName,
    required this.label,
    this.customName,
    required this.enabled,
    required this.inputs,
    required this.outputs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      item.hashCode ^
      missing.hashCode ^
      matchName.hashCode ^
      label.hashCode ^
      customName.hashCode ^
      enabled.hashCode ^
      inputs.hashCode ^
      outputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCompNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          item == other.item &&
          missing == other.missing &&
          matchName == other.matchName &&
          label == other.label &&
          customName == other.customName &&
          enabled == other.enabled &&
          inputs == other.inputs &&
          outputs == other.outputs;
}

/// A named region of the canvas: a tinted wash behind a set of boxes.
///
/// No rectangle crosses and no colour: the wash follows the members' own
/// positions, and `colour` is an index into the frontend's label palette.
class BridgeCompNodeGroup {
  final String name;
  final int colour;
  final List<UuidValue> members;

  const BridgeCompNodeGroup({
    required this.name,
    required this.colour,
    required this.members,
  });

  @override
  int get hashCode => name.hashCode ^ colour.hashCode ^ members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCompNodeGroup &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          colour == other.colour &&
          members == other.members;
}

/// Which kind of box this is, and so what the canvas draws it as.
///
/// The four the model has: a project item brought in, a value or picture handed
/// in from outside, a catalogue entry, and the one box whose picture the comp
/// shows.
enum BridgeCompNodeKind {
  read,
  input,
  fx,
  output,
  ;
}

/// Where one box sits on the canvas, in canvas units.
///
/// Document data, as the layer graph's positions are: they persist and travel,
/// and a box with no entry is auto-placed by the panel.
class BridgeCompNodePosition {
  final UuidValue node;
  final double x;
  final double y;

  const BridgeCompNodePosition({
    required this.node,
    required this.x,
    required this.y,
  });

  @override
  int get hashCode => node.hashCode ^ x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCompNodePosition &&
          runtimeType == other.runtimeType &&
          node == other.node &&
          x == other.x &&
          y == other.y;
}

/// The half of the graph the user edits, read out of [`BridgeCompGraph`],
/// changed, and handed straight back to
/// `CompositionReference::set_node_graph`.
///
/// The Fx boxes are deliberately absent: they are staged instances and travel
/// beside this, which is what lets a parameter edit and a wiring edit be the
/// same one commit.
class BridgeCompWiring {
  final List<BridgeReadNode> reads;
  final List<BridgeInputNode> inputs;

  /// The one Output box's id. A graph always has exactly one, and
  /// [`lumit_core::Op::SetCompGraph`] refuses a write that has none or two.
  final UuidValue output;
  final List<BridgeCompEdge> edges;
  final List<BridgeCompNodePosition> layout;

  /// The boxes twirled open to show every socket. A wired socket is drawn
  /// whether its box is exposed or not.
  final List<UuidValue> exposed;
  final List<BridgeCompNodeGroup> groups;

  const BridgeCompWiring({
    required this.reads,
    required this.inputs,
    required this.output,
    required this.edges,
    required this.layout,
    required this.exposed,
    required this.groups,
  });

  @override
  int get hashCode =>
      reads.hashCode ^
      inputs.hashCode ^
      output.hashCode ^
      edges.hashCode ^
      layout.hashCode ^
      exposed.hashCode ^
      groups.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCompWiring &&
          runtimeType == other.runtimeType &&
          reads == other.reads &&
          inputs == other.inputs &&
          output == other.output &&
          edges == other.edges &&
          layout == other.layout &&
          exposed == other.exposed &&
          groups == other.groups;
}

/// One Input box's declaration: what it is called, what it carries, and the
/// range and unit its row gets outside the graph.
///
/// The same five facts the Custom shader's Parameter node carries, with the
/// same names, so one form edits both.
class BridgeGraphInput {
  /// snake_case, unique in the graph, and the parameter id outside it.
  final String id;
  final String label;
  final BridgeInputKind kind;

  /// One number, or four for a colour.
  final F64Array4 default_;
  final double min;
  final double max;
  final BridgeUnit unit;

  /// A project item to stand in for the picture when nothing feeds a picture
  /// Input (§5.11) - what the Node panel's preview picker sets. It crosses
  /// both ways, so a graph read out and written back keeps the one it has.
  final UuidValue? preview;

  const BridgeGraphInput({
    required this.id,
    required this.label,
    required this.kind,
    required this.default_,
    required this.min,
    required this.max,
    required this.unit,
    this.preview,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      kind.hashCode ^
      default_.hashCode ^
      min.hashCode ^
      max.hashCode ^
      unit.hashCode ^
      preview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGraphInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          kind == other.kind &&
          default_ == other.default_ &&
          min == other.min &&
          max == other.max &&
          unit == other.unit &&
          preview == other.preview;
}

/// What an Input box stands for: the five facts the Node panel's form edits
/// (docs/impl/node-graph-comp.md §1.5).
enum BridgeInputKind {
  picture,
  number,
  angle,
  colour,
  ;
}

/// An Input box as it is stored: its id on the canvas, and its declaration.
class BridgeInputNode {
  final UuidValue id;
  final BridgeGraphInput input;

  const BridgeInputNode({
    required this.id,
    required this.input,
  });

  @override
  int get hashCode => id.hashCode ^ input.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeInputNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          input == other.input;
}

/// A Read box as it is stored: which item it brings in, under which name.
class BridgeReadNode {
  final UuidValue id;
  final UuidValue item;
  final String? customName;

  const BridgeReadNode({
    required this.id,
    required this.item,
    this.customName,
  });

  @override
  int get hashCode => id.hashCode ^ item.hashCode ^ customName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeReadNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          item == other.item &&
          customName == other.customName;
}
