// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'graph.dart';
import 'layer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'roto.dart';
part 'effect.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `animation_at`, `badge_of`, `bridge_param`, `bridge_shader_ty`, `bridge_unit`, `catalogue`, `clamp_animation`, `derived_params_of`, `document_for`, `fill_derived`, `hard_bounds`, `is_audio_match_name`, `param`, `plugin_category_key`, `presets_in`, `read_at`, `read_at`, `read_at`, `read_instance_info`, `read`, `sample_at`, `scan_audio_plugins`, `seconds_of`, `shader_error`, `validated`, `write_at`, `write_at`, `write`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_effects`, `new`

/// Every built-in **effect**, in schema order — the Add-effect menu's source of
/// truth ([`lumit_core::fx::BUILTINS`]), and the frb form of v0's `list_effects`.
///
/// Stateless, so it is a free function rather than a method: the menu is
/// available before any project is open.
///
/// **The drivers are here too**, filed under Controls
/// ([`FxCategory::grouping`](lumit_core::fx::FxCategory::grouping)): one search
/// surface offers everything a layer can be given, and applying a driver puts
/// it on the layer's graph rather than its stack — `LayerReference::add_effect`
/// decides that, so no caller has to. [`list_drivers`] still answers the
/// canvas's narrower question: which entries may be *dropped on the graph*.
List<BridgeEffectInfo> listEffects() =>
    BridgeLib.instance.api.crateApiEffectListEffects();

/// **All nine layer styles** (docs/impl/layer-styles.md §1), in §2's
/// pinned painting order.
///
/// Deliberately **not** part of [`list_effects`]: the effect browser, the
/// command palette and the Add-effect menu all walk that list, and offering
/// "Drop shadow (style)" there beside the Drop shadow effect would be the wrong
/// answer to every search for a shadow. A style is added from the Layer menu and
/// from the panel's own Styles heading, and both read this.
///
/// Nine rather than the seven a menu offers, because the frontend asks this two
/// questions and only one of them is about menus: **what may be added** (the
/// seven [`BridgeStyleInfo::offered`] marks) and **what is this style called**
/// (all nine — an imported project can carry a Satin, and a heading reading
/// `style_satin` is what leaving it out looks like).
///
/// Its own tiny shape rather than [`BridgeEffectInfo`], because a style has none
/// of what that carries: no browse category (they are one fixed family), no
/// sockets (nothing wires to a style's declaration before it is on a layer), and
/// no provenance (all nine are Lumit's).
List<BridgeStyleInfo> listStyles() =>
    BridgeLib.instance.api.crateApiEffectListStyles();

/// The Drivers family — the Graph panel's own search list, in the
/// same shape and the same schema order as [`list_effects`].
///
/// Its own listing rather than a filter the frontend applies, because the
/// distinction is the engine's: a driver makes a value, not a picture, so the
/// canvas is the only place one can be *dropped*. Every entry carries the
/// `controls` grouping key and heading its browse family gives it, so a driver
/// reads as one more Controls entry wherever it is listed.
List<BridgeEffectInfo> listDrivers() =>
    BridgeLib.instance.api.crateApiEffectListDrivers();

/// Scan the standard OFX folders (and `OFX_PLUGIN_PATH`) **and the standard
/// CLAP and VST3 folders** (and `CLAP_PATH`, `VST3_PATH`), and offer what is
/// found as effects.
///
/// **Deliberately not `frb(sync)`**: this opens other people's bundles and
/// spawns a broker process per bundle, which is tens of milliseconds at best
/// and seconds on a machine with a large suite installed. flutter_rust_bridge
/// runs it on a worker and hands Dart a future, so the interface never waits on
/// it — the start-up scan and the rescan command are the same call.
///
/// Registration is additive and idempotent: calling this twice registers each
/// plugin once, so a rescan after installing something new is safe at
/// any moment.
Future<BridgePluginScan> rescanPlugins() =>
    BridgeLib.instance.api.crateApiEffectRescanPlugins();

/// Switch a discovered plugin on or off, by the `match_name` the listing hands
/// out (docs/12 §2.6).
///
/// Takes the match name rather than the plugin's own identifier because that is
/// what the browser holds; deriving one from the other is the engine's business
/// and would otherwise be a rule the frontend had to know. A name that is not a
/// plugin's is simply ignored.
///
/// Two things happen: the answer is written to the preferences, so it survives
/// a restart, and it takes effect **now** — a plugin switched off mid-session
/// renders its input unchanged and its layers wear a badge, rather than the
/// change waiting for a relaunch. Switching one back on does not re-register it
/// within the session if it was never scanned in; a rescan does that.
///
/// # Errors
///
/// [`BridgeError::WriteFailed`] when the preference could not be written — the
/// answer still holds for this session.
void setPluginEnabled({required String effect, required bool enabled}) =>
    BridgeLib.instance.api
        .crateApiEffectSetPluginEnabled(effect: effect, enabled: enabled);

/// What plugins have asked Lumit to say since this was last called, oldest
/// first, taken as they are read.
///
/// **Never modal** (docs/12 §2.2, open question): a plugin that wants to tell
/// the user something gets a calm toast on the status strip and nothing more,
/// until the owner says what the Message suite should look like. A plugin that
/// asks a *question* has already been told "you decide" at the suite, which is
/// the reply OFX defines for a host that cannot ask.
///
/// Empty on every session with no plugins, which is what makes polling it from
/// the shell's existing tick free.
List<String> pluginMessages() =>
    BridgeLib.instance.api.crateApiEffectPluginMessages();

/// Every `.lumfx` in the preset library folder, sorted by name — what the
/// Effects & presets browser lists. A file that is not a preset (unreadable,
/// or not preset JSON) is simply not listed; the folder is the user's to put
/// things in, and a stray file there is not a fault.
List<BridgePresetInfo> listPresets() =>
    BridgeLib.instance.api.crateApiEffectListPresets();

/// Every `.lumgrp` **node group** in the same library folder, sorted by name —
/// what the graph canvas's search offers beside the drivers.
///
/// The same folder as the effect presets, because it is the same kind of thing:
/// something this person saved to use again, on any project.
List<BridgePresetInfo> listNodeGroups() =>
    BridgeLib.instance.api.crateApiEffectListNodeGroups();

/// Where the preset library lives, created on first ask — the save dialogue's
/// default folder, so a saved preset appears in the listing without the user
/// navigating anywhere. `None` only when the platform has no home directory.
String? presetsDirPath() =>
    BridgeLib.instance.api.crateApiEffectPresetsDirPath();

/// What `scalar` reads as at `time` — the value the picture is actually showing.
///
/// The panel needs this at exactly two moments, and both would be wrong done in
/// Dart. Turning animation *off* keeps the value the curve currently has, rather
/// than snapping to whatever the first key holds; adding a key at the playhead
/// seeds it with the value already on screen, so the act of adding a key never
/// moves the picture. Bezier keys make either one a real evaluation, not a
/// lerp — so this is the engine's own [`lumit_core::anim::evaluate`] rather than
/// a second implementation that would disagree with the renderer.
///
/// Sampling is in `f64` seconds, matching the engine: exactness is a property of
/// key *times* (which cross as integer pairs), not of a sampled value.
double sampleScalar(
        {required BridgeScalar scalar, required BridgeRational time}) =>
    BridgeLib.instance.api
        .crateApiEffectSampleScalar(scalar: scalar, time: time);

/// Every one of `scalars` at the same `time`, in the order they were given.
///
/// The same answers as calling [`sample_scalar`] once per scalar, and the reason
/// it exists is that the panel wants them all at once: on each frame of a scrub
/// or a playback, *every* animated row on screen asks what its curve reads now.
/// That was one crossing of the boundary per row per frame — chatter that grew
/// with the number of lanes open, so a `U` on a busy layer made the playhead
/// lag over frames the cache already held. One crossing carries the lot.
Float64List sampleScalars(
        {required List<BridgeScalar> scalars, required BridgeRational time}) =>
    BridgeLib.instance.api
        .crateApiEffectSampleScalars(scalars: scalars, time: time);

double sampleScalarWithContext(
        {required BridgeScalar scalar,
        required BridgeRational time,
        required LayerReference layer}) =>
    BridgeLib.instance.api.crateApiEffectSampleScalarWithContext(
        scalar: scalar, time: time, layer: layer);

Float64List sampleScalarRangeWithContext(
        {required BridgeScalar scalar,
        required LayerReference layer,
        required BridgeRational start,
        required BridgeRational end,
        required PlatformInt64 samples}) =>
    BridgeLib.instance.api.crateApiEffectSampleScalarRangeWithContext(
        scalar: scalar, layer: layer, start: start, end: end, samples: samples);

/// Every parameter `effect` declares, in schema order — what the panel draws a
/// row per.
///
/// Keyed by the same `match_name` [`list_effects`] hands out and `add_effect`
/// takes. An unknown name is an empty list rather than an error: a project
/// carrying an effect this build does not know still opens, and its instance
/// simply has no rows to draw.
List<BridgeParamInfo> listParameters({required String effect}) =>
    BridgeLib.instance.api.crateApiEffectListParameters(effect: effect);

/// An effect's vector pairs, in schema order — the fourth static list beside
/// [`list_parameters`], and memoised on the Dart side for the same reason
/// (the schema never changes, and a fetch per card per rebuild is
/// exactly the traffic the budget test forbids).
///
/// An unknown match name is an empty list rather than an error, like every
/// other schema read: a project carrying an effect this build does not know
/// still opens.
List<BridgeParamPair> listPairs({required String effect}) =>
    BridgeLib.instance.api.crateApiEffectListPairs(effect: effect);

/// Every parameter group `effect` declares, in schema order (empty for an
/// effect with none, or an unknown name). The panel inserts each group's
/// twirl at its first member's position and hides the members it covers from
/// the flat run.
List<BridgeParamGroup> listParameterGroups({required String effect}) =>
    BridgeLib.instance.api.crateApiEffectListParameterGroups(effect: effect);

/// Every greying rule `effect` declares (empty for an effect whose controls are
/// all independent, which is most of them, or for an unknown name — a project
/// carrying an effect this build does not know still opens).
List<BridgeEnabledWhen> listEnabledWhen({required String effect}) =>
    BridgeLib.instance.api.crateApiEffectListEnabledWhen(effect: effect);

/// The v1 node vocabulary (custom-shader.md §4.3), in listing order. Static:
/// asked once and memoised Dart-side like every other catalogue.
List<BridgeShaderNodeKind> listShaderNodes() =>
    BridgeLib.instance.api.crateApiEffectListShaderNodes();

/// Resolve one graph document for drawing: every box's ports and types, and
/// whether the whole thing compiles.
///
/// A pure question — nothing is staged and no document moves — which is also
/// how the canvas refuses a drop: build the candidate graph, ask, and decline
/// visually when the answer names a mismatch or a cycle. The engine stays the
/// single validator; the panel never learns the type rules (display and
/// forward, decide in Rust). Called on gestures and reloads, never in a
/// rebuild.
BridgeShaderGraphView shaderGraphView({required String graph}) =>
    BridgeLib.instance.api.crateApiEffectShaderGraphView(graph: graph);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeEffectInstance>>
abstract class BridgeEffectInstance implements RustOpaqueInterface {
  /// Detach the inner graph (§4.1): keep the compiled text, drop the `graph`
  /// key, and leave an ordinary hand-written shader behind. One staged edit,
  /// committed with the stack, so it is one undo step — and it is not
  /// reversible by another button, which is the honest shape: the graph is
  /// gone because the user said so.
  void detachShaderGraph();

  /// False when the effect is individually bypassed (docs/08 §1.5) — the state
  /// of the checkbox in its title bar.
  bool enabled();

  /// One read for everything a card draws — see [`BridgeEffectInstanceInfo`].
  BridgeEffectInstanceInfo getInfo();

  List<String> getParameters();

  /// A parameter's value, whatever kind it is. An unknown `id` is an error;
  /// every parameter an instance actually carries is expressible, so there is
  /// no "cannot represent this one" answer any more.
  BridgeEffectValue getValue({required String id});

  /// This instance's own id — what the stack ops on
  /// [`crate::api::layer::LayerReference`] address it by.
  UuidValue id();

  /// Every row **this instance** draws, in order: the rows its effect
  /// declares, then the rows its own state derives (docs/impl/custom-shader.md
  /// §1.5, docs/impl/effect-registry.md §4).
  ///
  /// The owed half of [`list_parameters`], which is keyed by match name and so
  /// can only ever answer the first half. For every effect but the Custom
  /// shader the two lists are the same list; for a Custom shader the tail is
  /// the uniforms the source it holds declares, and nothing downstream can
  /// tell a derived row from a declared one — same widgets, same keyframes,
  /// same expressions.
  ///
  /// **Not the panel's per-rebuild road.** The panel reads the declared half
  /// from its Dart-side memo and the derived half off
  /// [`BridgeEffectInstanceInfo::derived_params`], which it already holds; this
  /// is the one-piece answer for a caller that has a handle and no read model.
  List<BridgeParamInfo> listParameters();

  String name();

  /// Whether the vector pair keyed by `stem` is chained. A stem this
  /// effect has no pair for is unlinked, never an error.
  bool pairLinked({required String stem});

  /// Add one stroke to this Roto brush, on the **staged** copy.
  ///
  /// `points` are `[x0, y0, x1, y1, …]` in **source raster pixels** on the
  /// unaltered footage — the viewer converts, because only it knows the chain
  /// of transforms the pointer came through, and the matte has to describe the
  /// file's frames rather than this comp's. `frame` is the source
  /// frame the stroke was drawn on.
  ///
  /// **The first stroke sets the base frame**, which is what makes Propagate
  /// answerable at all; a later stroke on another frame is a *correction* and
  /// leaves the base where it is. Moving the base is
  /// [`Self::roto_set_base_frame`], deliberately a separate gesture.
  ///
  /// An odd-length `points`, a stroke with none, or a non-finite coordinate is
  /// refused rather than stored: a stroke nobody can stamp is a stroke that
  /// would silently do nothing.
  void rotoAddStroke(
      {required List<double> points,
      required double radius,
      required BridgeRotoStrokeKind kind,
      required PlatformInt64 frame});

  /// Throw away every stroke and the base frame, on the staged copy — the
  /// panel's "start again". The cached mattes are not touched: they are keyed
  /// by the strokes that made them, so they are simply never asked for again,
  /// and an undo brings the strokes and their mattes both back.
  void rotoClear();

  /// Move the base frame — the frame propagation runs outward from — on the
  /// staged copy.
  ///
  /// A real edit and not a preference: every cached matte depends on it, so
  /// moving it retires the whole run, which is exactly what a user asking for
  /// the shot to be re-decided from somewhere else means.
  void rotoSetBaseFrame({PlatformInt64? frame});

  /// Every stroke this instance holds, for the overlay to draw.
  ///
  /// Read on the gesture that needs it and on a document revision moving —
  /// never per rebuild, which is the contract every other panel read has.
  List<BridgeRotoStroke> rotoStrokes();

  String serialize();

  /// Stage the user's own name for this instance — an empty or
  /// whitespace name clears it back to the effect's label. Staging only, like
  /// `set_value`: `LayerReference::set_effects` is the commit.
  void setCustomName({required String name});

  /// Bypass or enable this instance on the **staged** copy, like
  /// `set_custom_name`. The commit is `LayerReference::set_graph` for a
  /// driver node, whose `B` badge this is; a stack effect has its own
  /// committing op (`LayerReference::set_effect_enabled`) and does not need
  /// this.
  void setEnabled({required bool enabled});

  /// Chain or unchain the vector pair keyed by `stem`, on the **staged**
  /// copy — `LayerReference::set_effects` is the commit, exactly as
  /// `set_custom_name` and `set_value` are, so a toggle is one op and one
  /// undo step like every other effect-stack edit.
  ///
  /// Answers whether anything moved, so a caller can skip a commit that
  /// would undo to itself. The proportional drag a chained pair takes is
  /// deliberately **not** here: it is UI-time arithmetic while a gesture is
  /// live, and the document's business is only which pairs are tied.
  bool setPairLinked({required String stem, required bool linked});

  /// Stage a whole inner graph on this instance (§4.1, CS4), exactly as
  /// `set_shader_source` stages text: `LayerReference::set_effects` is the
  /// commit, so a graph edit is one `SetLayerEffects` and one undo step.
  ///
  /// The graph becomes master. When it compiles, the compiled WGSL is written
  /// into `source` in the same staging — the cached text §4.1 keeps so a
  /// build that cannot compile the graph can still render it — and `origin`
  /// is dropped, the text no longer being any file's. When it does not
  /// compile, the graph is stored anyway with the last text left standing:
  /// being broken is a normal state to pass through, and the badge says so.
  ///
  /// # Errors
  /// [`BridgeError::InvalidShaderGraph`] when the text is not a graph
  /// document at all — a caller bug, not a user state.
  void setShaderGraph({required String graph});

  /// Stage this instance's shader source on the **staged** copy, exactly as
  /// `set_custom_name` and `set_value` do: `LayerReference::set_effects` is the
  /// commit, so a shader edit is one `SetLayerEffects` and one undo step like
  /// every other effect-stack edit.
  ///
  /// `origin` is the file the text was read from, or `None` for text the user
  /// typed — which is the honest answer once they have typed it, since it no
  /// longer says what that file says. An empty `source` clears the block back
  /// to a fresh instance: a passthrough with no badge.
  ///
  /// The rows the new source declares are **offered**, not adopted: the
  /// document keeps the values it has, an id that has gone keeps its row and
  /// its expression, and an id that is new draws at its default until the user
  /// touches it (§1.5).
  void setShaderSource({required String source, String? origin});

  /// Overwrite a parameter on this staged copy. Nothing is committed — see the
  /// type's own documentation; `LayerReference::set_effects` is the commit.
  ///
  /// Refused when `value` is of a different kind from the parameter, so a
  /// control can never quietly change what a parameter *is*.
  ///
  /// **The hard range is enforced here, not in the panel** (docs/08 §1.2).
  /// Every way a number reaches an effect parameter — typed, scrubbed,
  /// dragged in the graph editor, picked off the Viewer, wired from a node,
  /// pasted, loaded from a preset — passes through this one call, and both the
  /// preview and the commit stage through it, so clamping once here is what
  /// makes the picture a scrub shows and the value it lands on the same number.
  /// A control that also clamps its own reading is agreeing with the engine,
  /// not deciding for it; a control that forgets to can no longer render a
  /// value the parameter does not have.
  void setValue({required String id, required BridgeEffectValue value});

  /// The stored inner graph, as its JSON text, or `None` for a hand-written
  /// (or empty) shader (docs/impl/custom-shader.md §4, CS4).
  ///
  /// Read on the gesture that enters the graph, never per rebuild — the same
  /// contract `shader_source` has, and for the same reason.
  String? shaderGraph();

  /// Where the text came from, when it was loaded from a file — remembered for
  /// reload and **never read at render**: a project must be one file that opens
  /// on another machine.
  String? shaderOrigin();

  /// The WGSL text this instance holds, or `None` when it holds none
  /// (docs/impl/custom-shader.md §1.2).
  ///
  /// The source is **instance state, not a parameter**: `Value` is `Copy` and
  /// hashed field by field, a kilobyte of text is neither, and two shader
  /// sources cannot be interpolated. So it does not ride
  /// [`BridgeEffectInstanceInfo::values`] with the numbers; it is read here,
  /// on the gesture that opens an editor, rather than per rebuild.
  String? shaderSource();

  /// Whether this instance's shader will draw, and why not when it will not
  /// (docs/impl/custom-shader.md §2.1, §2.2).
  ///
  /// The per-instance answer the badge wears and the editor anchors its
  /// message to. `error` is `None` for a shader that compiles **and** for an
  /// instance with no source at all, because an effect the user has not filled
  /// in yet is a passthrough rather than a failure.
  BridgeShaderStatus shaderStatus();
}

/// An **automatic** bezier side ([`SideInterp::Auto`]): its speed is computed
/// from the key's neighbours, `clamped` saying whether the computation is the
/// plain smooth one or the one that cannot overshoot them.
///
/// `speed` and `influence` are the ease the side carried when it was last
/// free. They cross in both directions untouched, which is what makes
/// Free → Auto → Free give the custom ease back without the write path having
/// to consult what was there before.
class BridgeAutoSide {
  final bool clamped;
  final double speed;
  final double influence;

  const BridgeAutoSide({
    required this.clamped,
    required this.speed,
    required this.influence,
  });

  @override
  int get hashCode => clamped.hashCode ^ speed.hashCode ^ influence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAutoSide &&
          runtimeType == other.runtimeType &&
          clamped == other.clamped &&
          speed == other.speed &&
          influence == other.influence;
}

/// A bezier side's After Effects-compatible handle: `speed` in value-units per
/// second, `influence` as a fraction of the gap to the neighbouring key.
class BridgeBezierSide {
  final double speed;
  final double influence;

  const BridgeBezierSide({
    required this.speed,
    required this.influence,
  });

  @override
  int get hashCode => speed.hashCode ^ influence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBezierSide &&
          runtimeType == other.runtimeType &&
          speed == other.speed &&
          influence == other.influence;
}

/// A colour parameter: four independently animatable scene-linear channels.
class BridgeColour {
  final BridgeScalar r;
  final BridgeScalar g;
  final BridgeScalar b;
  final BridgeScalar a;

  const BridgeColour({
    required this.r,
    required this.g,
    required this.b,
    required this.a,
  });

  @override
  int get hashCode => r.hashCode ^ g.hashCode ^ b.hashCode ^ a.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeColour &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          g == other.g &&
          b == other.b &&
          a == other.a;
}

/// One built-in effect as the Add-effect menu needs it: the stable `name` to
/// pass to [`crate::api::layer::LayerReference::add_effect`], the sentence-case
/// `label` to draw, and the category to group under. `category` is a stable
/// machine key the menu sorts by; `category_label` is its heading.
class BridgeEffectInfo {
  final String name;
  final String label;
  final String category;
  final String categoryLabel;

  /// Where this entry came from: [`NAMESPACE_BUILTIN`] or [`NAMESPACE_OFX`].
  ///
  /// A discovered plugin is drawn exactly as a built-in is — same row, same
  /// star, same drag — and this is the one difference: docs/12 §2.6 asks for
  /// "a small provenance tag in the effect's context menu", and nothing else.
  /// It rides on the listing rather than being a second call, because the
  /// browser needs it for every row it draws.
  final String namespace;

  /// The sockets an instance of this entry would draw, from its declaration
  /// alone — the parameters that can take a wire.
  ///
  /// Here because the Graph panel has to know an entry's ports *before* it is
  /// in the document: it is what lets adding a driver and joining it to the
  /// wire in hand be one commit and so one undo step, and what lets the Tab
  /// search show only the entries a dragged wire could land on. `wired` is
  /// always false — nothing is wired on a catalogue entry.
  final List<BridgePort> inputs;

  /// The output sockets — empty for every image effect, and the declared
  /// [`Signature::Data`](lumit_core::fx::Signature::Data) ports for a driver.
  final List<BridgePort> outputs;

  const BridgeEffectInfo({
    required this.name,
    required this.label,
    required this.category,
    required this.categoryLabel,
    required this.namespace,
    required this.inputs,
    required this.outputs,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      label.hashCode ^
      category.hashCode ^
      categoryLabel.hashCode ^
      namespace.hashCode ^
      inputs.hashCode ^
      outputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEffectInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          label == other.label &&
          category == other.category &&
          categoryLabel == other.categoryLabel &&
          namespace == other.namespace &&
          inputs == other.inputs &&
          outputs == other.outputs;
}

/// Everything a panel draws for one effect instance, in one crossing:
/// its id, match name, bypass state, and every parameter's current value. The
/// instance is an opaque handle, so `id()`/`name()`/`get_value()` each cross
/// the bridge — a card that read them one at a time cost a call per field per
/// parameter per rebuild.
class BridgeEffectInstanceInfo {
  final UuidValue id;
  final String name;

  /// The user's own name for the instance, or `None` to show the
  /// effect's label. `name` stays the `match_name` either way — it is the
  /// schema key, not a display string.
  final String? customName;
  final bool enabled;
  final List<BridgeParamValue> values;

  /// The stems of the vector pairs this instance has chained, sorted.
  /// Empty is "every pair unlinked", which is what every older project means.
  ///
  /// In the read model rather than asked per pair, for the reason every other
  /// field here is: a chain glyph is drawn per point row per rebuild, and a
  /// call apiece is exactly the hover-hot traffic the budget test forbids.
  final List<String> linkedPairs;

  /// Why this instance is not doing its own work, if it is not (docs/12 §1,
  /// §2.3) — one of [`BADGE_REASONS`], or `None` for the ordinary case.
  ///
  /// A **key**, not a sentence: the panel draws the calm badge in the user's
  /// own language. Four things it can say — the plugin failed, the
  /// plugin is switched off, the plugin is not installed on this machine, or
  /// this build has never heard of the effect at all. The last two are the
  /// placeholder docs/12 §1 requires: the instance is kept, values and all,
  /// so saving cannot lose it.
  final String? badgeReason;

  /// The engine's or the plugin's own words about the failure, where there
  /// are any — shown beneath the badge, verbatim and untranslated, because it
  /// is somebody else's sentence about somebody else's code.
  final String? badgeDetail;

  /// The rows **this instance** has beyond its effect's schema
  /// (docs/impl/custom-shader.md §1.5) — the Custom shader's own uniforms,
  /// read off the source it holds, and empty for every other effect.
  ///
  /// Here rather than asked for per card, and for the reason every other
  /// field of this struct is: the panel draws its rows on every rebuild, and
  /// a call apiece is exactly the traffic `bridge_call_budget_test` forbids.
  /// The declared half stays memoised Dart-side under the match name
  /// ([`list_parameters`]); this is the half that cannot be, because it is a
  /// fact about the instance. The two concatenated are what
  /// [`BridgeEffectInstance::list_parameters`] answers in one piece.
  final List<BridgeParamInfo> derivedParams;

  const BridgeEffectInstanceInfo({
    required this.id,
    required this.name,
    this.customName,
    required this.enabled,
    required this.values,
    required this.linkedPairs,
    this.badgeReason,
    this.badgeDetail,
    required this.derivedParams,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      customName.hashCode ^
      enabled.hashCode ^
      values.hashCode ^
      linkedPairs.hashCode ^
      badgeReason.hashCode ^
      badgeDetail.hashCode ^
      derivedParams.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEffectInstanceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          customName == other.customName &&
          enabled == other.enabled &&
          values == other.values &&
          linkedPairs == other.linkedPairs &&
          badgeReason == other.badgeReason &&
          badgeDetail == other.badgeDetail &&
          derivedParams == other.derivedParams;
}

@freezed
sealed class BridgeEffectValue with _$BridgeEffectValue {
  const BridgeEffectValue._();

  const factory BridgeEffectValue.float(
    BridgeScalar field0,
  ) = BridgeEffectValue_Float;
  const factory BridgeEffectValue.point(
    BridgePoint field0,
  ) = BridgeEffectValue_Point;
  const factory BridgeEffectValue.colour(
    BridgeColour field0,
  ) = BridgeEffectValue_Colour;
  const factory BridgeEffectValue.bool(
    bool field0,
  ) = BridgeEffectValue_Bool;
  const factory BridgeEffectValue.choice(
    int field0,
  ) = BridgeEffectValue_Choice;
  const factory BridgeEffectValue.seed(
    int field0,
  ) = BridgeEffectValue_Seed;
  const factory BridgeEffectValue.file(
    BridgeFileParam field0,
  ) = BridgeEffectValue_File;
  const factory BridgeEffectValue.layer([
    UuidValue? field0,
  ]) = BridgeEffectValue_Layer;

  /// Which of the owning layer's masks an effect walks: the mask id,
  /// or `None` for "First mask". The *geometry* never crosses — the render
  /// flattens it engine-side, beside the op.
  const factory BridgeEffectValue.maskPath([
    UuidValue? field0,
  ]) = BridgeEffectValue_MaskPath;

  /// A tone curve as its own control points: 2..=16 `[x, y]` pairs
  /// in the unit square, in x order. Crosses as written — the engine
  /// straightens what it reads (`CurvePoints::sanitised`), so a panel
  /// mid-drag need not, and a curve is never refused for being momentarily
  /// out of order.
  const factory BridgeEffectValue.curve(
    List<Float32List> field0,
  ) = BridgeEffectValue_Curve;
}

@freezed
sealed class BridgeEnabledCond with _$BridgeEnabledCond {
  const BridgeEnabledCond._();

  /// Editable while the named bool holds this value.
  const factory BridgeEnabledCond.boolIs(
    bool field0,
  ) = BridgeEnabledCond_BoolIs;

  /// Editable while the named choice is on this option index.
  const factory BridgeEnabledCond.choiceIs(
    int field0,
  ) = BridgeEnabledCond_ChoiceIs;

  /// Editable while the named choice is on anything but this index.
  const factory BridgeEnabledCond.choiceIsNot(
    int field0,
  ) = BridgeEnabledCond_ChoiceIsNot;

  /// Editable while the named layer reference actually names a layer.
  const factory BridgeEnabledCond.layerSet() = BridgeEnabledCond_LayerSet;
}

/// One greying rule: `param`'s row is editable only while `on` satisfies
/// `cond`. The panel evaluates it against values it already holds, so ticking
/// a switch greys its dependent row without a round trip;
/// `lumit_core::fx::param_enabled` is the same rule in Rust and the authority
/// the tests pin.
class BridgeEnabledWhen {
  final String param;
  final String on_;
  final BridgeEnabledCond cond;

  const BridgeEnabledWhen({
    required this.param,
    required this.on_,
    required this.cond,
  });

  @override
  int get hashCode => param.hashCode ^ on_.hashCode ^ cond.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEnabledWhen &&
          runtimeType == other.runtimeType &&
          param == other.param &&
          on_ == other.on_ &&
          cond == other.cond;
}

/// A file parameter: the paths it references, and the index that selects which
/// one is live. Two paths cannot be blended, so the index only ever steps
/// (hold keyframes); the common case is one path and a static index.
/// An empty `paths` means unset, which the consuming effect treats as identity.
class BridgeFileParam {
  final List<String> paths;
  final BridgeScalar index;

  const BridgeFileParam({
    required this.paths,
    required this.index,
  });

  @override
  int get hashCode => paths.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFileParam &&
          runtimeType == other.runtimeType &&
          paths == other.paths &&
          index == other.index;
}

/// One keyframe on one scalar channel.
class BridgeKeyframe {
  final BridgeRational time;
  final double value;

  /// Approaching this key.
  final BridgeSideInterp interpIn;

  /// Leaving this key.
  final BridgeSideInterp interpOut;

  const BridgeKeyframe({
    required this.time,
    required this.value,
    required this.interpIn,
    required this.interpOut,
  });

  @override
  int get hashCode =>
      time.hashCode ^ value.hashCode ^ interpIn.hashCode ^ interpOut.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeKeyframe &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          value == other.value &&
          interpIn == other.interpIn &&
          interpOut == other.interpOut;
}

/// One collapsible parameter group of an effect (docs/08 §1.2):
/// the panel tucks the named member rows behind a twirl. An empty `label`
/// renders headerless (the rows appear in place, no twirl) — the shape a
/// conditional run of parameters takes. `visible_when_param` with a
/// non-empty `visible_when_values` shows the group only while that sibling
/// Choice parameter holds one of those indices.
class BridgeParamGroup {
  final String label;

  /// Member parameter ids — a contiguous run of the schema's parameters.
  final List<String> params;

  /// Whether the twirl starts closed.
  final bool collapsed;

  /// See the struct docs.
  final String? visibleWhenParam;

  /// See the struct docs. Empty when the group is unconditional.
  final Uint32List visibleWhenValues;

  const BridgeParamGroup({
    required this.label,
    required this.params,
    required this.collapsed,
    this.visibleWhenParam,
    required this.visibleWhenValues,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      params.hashCode ^
      collapsed.hashCode ^
      visibleWhenParam.hashCode ^
      visibleWhenValues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeParamGroup &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          params == other.params &&
          collapsed == other.collapsed &&
          visibleWhenParam == other.visibleWhenParam &&
          visibleWhenValues == other.visibleWhenValues;
}

/// One declared parameter of an effect, as the panel needs to *draw* it:
/// what to call it, what kind of control it is, and the range or option list
/// that control needs.
///
/// This is the schema, not the value — [`BridgeEffectValue`] carries what a
/// particular instance currently holds. The panel needs both: the value to show,
/// and this to know whether "0.5" wants a slider from 0 to 100 or a colour
/// channel, and what the third entry in a dropdown is called.
class BridgeParamInfo {
  /// Stable snake_case id — the key [`BridgeEffectInstance::get_value`] and
  /// `set_value` take.
  final String id;
  final String label;
  final BridgeParamKind kind;

  /// What the number *is*: the rider the row draws beside the value,
  /// and — on a point pair — the unit a Viewer pick has to write in. Declared
  /// per parameter engine-side, so a row's unit travels with the row rather
  /// than with its id and the panel never has to guess.
  final BridgeUnit unit;

  const BridgeParamInfo({
    required this.id,
    required this.label,
    required this.kind,
    required this.unit,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ kind.hashCode ^ unit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeParamInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          kind == other.kind &&
          unit == other.unit;
}

@freezed
sealed class BridgeParamKind with _$BridgeParamKind {
  const BridgeParamKind._();

  const factory BridgeParamKind.float({
    required double default_,

    /// The slider's travel. Typing may exceed it (docs/08 §1.2); only
    /// `hard_min`/`hard_max` may not.
    required double sliderMin,
    required double sliderMax,

    /// Hard bounds, either side open (a threshold clamps at zero
    /// below and runs unbounded above).
    double? hardMin,
    double? hardMax,
  }) = BridgeParamKind_Float;

  /// A whole-number parameter (docs/08 §1.2): the value is still a Float
  /// scalar in the model — the kind only asks the row to step, display and
  /// commit whole numbers.
  const factory BridgeParamKind.int({
    required PlatformInt64 default_,
    required PlatformInt64 sliderMin,
    required PlatformInt64 sliderMax,
    PlatformInt64? hardMin,
    PlatformInt64? hardMax,
  }) = BridgeParamKind_Int;

  /// Degrees, drawn as a dial beneath the number (docs/07 §6). The value
  /// crossing the bridge is a [`BridgeEffectValue::Float`] — an angle is a
  /// number of degrees, and this kind only says which control to draw.
  /// Unbounded, so the dial winds through full turns.
  const factory BridgeParamKind.angle({
    required double default_,

    /// Snapping increment in degrees while a modifier is held.
    required double dialStep,
  }) = BridgeParamKind_Angle;
  const factory BridgeParamKind.choice({
    required List<String> options,
    required int default_,

    /// Option indices after which the dropdown draws a group divider (T21).
    /// Empty for an ungrouped list.
    required Uint32List dividersAfter,
  }) = BridgeParamKind_Choice;
  const factory BridgeParamKind.bool({
    required bool default_,
  }) = BridgeParamKind_Bool;
  const factory BridgeParamKind.colour({
    /// Scene-linear RGBA. Channels animate independently in the model, so
    /// the panel edits four scalars behind one swatch.
    required Float64List default_,

    /// Per-channel edit range — a linear value may exceed 1 (an HDR tint)
    /// or dip below 0 (a lift), so each colour declares its own.
    required double min,
    required double max,
  }) = BridgeParamKind_Colour;
  const factory BridgeParamKind.seed() = BridgeParamKind_Seed;
  const factory BridgeParamKind.file({
    /// Lower-case extensions without the dot, for the open dialog.
    required List<String> filter,
    required String filterName,
  }) = BridgeParamKind_File;
  const factory BridgeParamKind.layer() = BridgeParamKind_Layer;

  /// One of the **owning layer's masks**, whose geometry the effect walks
  /// (docs/08 §1.2). The panel draws the layer's masks by name, with
  /// "First mask" as the unset entry; the mask names come from the read model
  /// the panel already holds, so the row costs no call of its own.
  const factory BridgeParamKind.maskPath() = BridgeParamKind_MaskPath;

  /// A tone curve, drawn as a curve editor. The panel edits the
  /// point list itself; there is no range to declare, because the points
  /// live in the unit square by definition.
  const factory BridgeParamKind.curve() = BridgeParamKind_Curve;

  /// A closed range, drawn as a track and thumb with the value
  /// beside it. `min`/`max` are the travel *and* the hard bound — that is
  /// what closed means — so the row refuses a typed value outside them.
  ///
  /// The value crossing the bridge is a [`BridgeEffectValue::Float`], the
  /// arrangement `Int` and `Angle` already use: the kind says which control
  /// to draw, not how the number is stored, so the row keeps every float
  /// affordance including keyframes and the graph editor.
  const factory BridgeParamKind.slider({
    required double default_,
    required double min,
    required double max,
  }) = BridgeParamKind_Slider;

  /// A **button**, drawn as one and pressed through
  /// [`crate::api::layer::LayerReference::fire_effect_action`]. It carries no
  /// value at all — no default, no range, nothing in
  /// [`BridgeEffectInstanceInfo::values`] — because a press is an event and
  /// not a number that could be keyframed, undone or interpolated.
  const factory BridgeParamKind.action() = BridgeParamKind_Action;
}

/// One **vector pair** of an effect: two adjacent `_x`/`_y` Float parameters
/// the panel draws as one row of two wells with a chain between them.
///
/// The convention used to be read off the ids at the seam, by whoever needed
/// it; [`lumit_core::fx::EffectSchema::pairs`] is the declaration answering it
/// now, so the panel, the link flag on the instance and the engine all get one
/// answer. `stem` is the key the link flag is stored under, so it is the
/// pair's identity rather than either half's id.
class BridgeParamPair {
  final String stem;
  final String x;
  final String y;

  const BridgeParamPair({
    required this.stem,
    required this.x,
    required this.y,
  });

  @override
  int get hashCode => stem.hashCode ^ x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeParamPair &&
          runtimeType == other.runtimeType &&
          stem == other.stem &&
          x == other.x &&
          y == other.y;
}

/// One parameter's current value, as [`BridgeEffectInstance::get_info`]
/// carries it.
class BridgeParamValue {
  final String id;
  final BridgeEffectValue value;

  const BridgeParamValue({
    required this.id,
    required this.value,
  });

  @override
  int get hashCode => id.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeParamValue &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          value == other.value;
}

/// What one scan of the machine's plugin folders did (docs/12 §2.6).
class BridgePluginScan {
  /// The labels of the effects this scan added, in the order they were found.
  /// Empty for a rescan that found nothing new, which is the usual answer.
  final List<String> registered;

  /// One calm line per bundle or plugin turned away — a broken install, a
  /// context this host cannot drive, a plugin the user switched off. Shown as
  /// a report, never as a dialogue.
  final List<String> skipped;

  const BridgePluginScan({
    required this.registered,
    required this.skipped,
  });

  static Future<BridgePluginScan> default_() =>
      BridgeLib.instance.api.crateApiEffectBridgePluginScanDefault();

  @override
  int get hashCode => registered.hashCode ^ skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePluginScan &&
          runtimeType == other.runtimeType &&
          registered == other.registered &&
          skipped == other.skipped;
}

/// A point parameter: two independently animatable axes.
class BridgePoint {
  final BridgeScalar x;
  final BridgeScalar y;

  const BridgePoint({
    required this.x,
    required this.y,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

/// One saved `.lumfx` preset in the user's library: the display name it was
/// saved under and the file to read when applying it.
class BridgePresetInfo {
  final String name;
  final String path;

  const BridgePresetInfo({
    required this.name,
    required this.path,
  });

  @override
  int get hashCode => name.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePresetInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path;
}

/// An exact rational time in seconds, as `num / den`.
///
/// Keyframe times cross as the integer pair the document stores, never as
/// floating-point seconds (docs/17 "rational time crosses as integers"): a key
/// at 1/3 s read back as 0.333… and written again would no longer land on the
/// frame it was set on, and this round trip has to be exact.
class BridgeRational {
  final PlatformInt64 num;

  /// Always positive in anything the engine hands out; a zero or negative
  /// denominator coming the other way is refused, not normalised.
  final PlatformInt64 den;

  const BridgeRational({
    required this.num,
    required this.den,
  });

  @override
  int get hashCode => num.hashCode ^ den.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRational &&
          runtimeType == other.runtimeType &&
          num == other.num &&
          den == other.den;
}

@freezed
sealed class BridgeScalar with _$BridgeScalar {
  const BridgeScalar._();

  const factory BridgeScalar.static_(
    double field0,
  ) = BridgeScalar_Static;

  /// At least one key, strictly ascending in time — the invariant the
  /// engine's keyframe ops maintain, enforced here on the way in.
  const factory BridgeScalar.keyframed(
    List<BridgeKeyframe> field0,
  ) = BridgeScalar_Keyframed;
  const factory BridgeScalar.expression(
    String field0,
  ) = BridgeScalar_Expression;
}

/// One box of the inner graph, resolved for drawing. `label` is set only for
/// a Parameter box — the user's own word for their own control, shown as-is
/// and never translated; every other box is named by the frontend from `kind`.
class BridgeShaderGraphNode {
  final int id;
  final String kind;
  final String? label;
  final List<BridgeShaderPort> inputs;
  final List<BridgeShaderPort> outputs;

  const BridgeShaderGraphNode({
    required this.id,
    required this.kind,
    this.label,
    required this.inputs,
    required this.outputs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      label.hashCode ^
      inputs.hashCode ^
      outputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeShaderGraphNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          label == other.label &&
          inputs == other.inputs &&
          outputs == other.outputs;
}

/// A stored inner graph as the canvas draws it, plus the one sentence that
/// says whether it will compile. The canvas draws a broken graph exactly as it
/// draws a working one — being broken is a state to work in, and the badge is
/// the messenger (§2.2) — so the boxes and the error travel together.
class BridgeShaderGraphView {
  final List<BridgeShaderGraphNode> nodes;
  final String? error;

  const BridgeShaderGraphView({
    required this.nodes,
    this.error,
  });

  @override
  int get hashCode => nodes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeShaderGraphView &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          error == other.error;
}

/// One entry of the inner graph's add-search: a kind the frontend translates,
/// filed under its family.
class BridgeShaderNodeKind {
  final String kind;
  final String category;

  const BridgeShaderNodeKind({
    required this.kind,
    required this.category,
  });

  @override
  int get hashCode => kind.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeShaderNodeKind &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          category == other.category;
}

/// One port as the inner canvas draws it: its name (an id the frontend
/// translates — the engine sends no English here) and its nominal type.
class BridgeShaderPort {
  final String id;
  final BridgeShaderTy ty;

  const BridgeShaderPort({
    required this.id,
    required this.ty,
  });

  @override
  int get hashCode => id.hashCode ^ ty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeShaderPort &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          ty == other.ty;
}

/// What became of the shader one Custom shader instance holds
/// (docs/impl/custom-shader.md §2.2).
///
/// # In plain terms
///
/// Somebody typed a program. Either it works, or the compiler has something to
/// say about it — and the words are the compiler's own, untranslated, because it
/// is somebody else's sentence about somebody else's code. The line
/// numbers in it have been moved back onto the text the user is looking at, so
/// "line 3" means the third line they typed rather than the third line of the
/// wrapper Lumit put around it.
///
/// A shader that is merely *unfinished* is not a failure: `error` is `None` for
/// an instance with no source, which renders as a passthrough and wears no badge.
class BridgeShaderStatus {
  /// The refusal or the compiler's message, or `None` when the shader draws.
  final String? error;

  /// One calm sentence per annotation that would not parse. A typo in a doc
  /// comment costs that row and not the other eight (§2.2), so these are
  /// notes beside working rows rather than an error instead of them.
  final List<String> notes;

  const BridgeShaderStatus({
    this.error,
    required this.notes,
  });

  @override
  int get hashCode => error.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeShaderStatus &&
          runtimeType == other.runtimeType &&
          error == other.error &&
          notes == other.notes;
}

/// What a wire in the inner graph carries, for the canvas to colour sockets
/// by. Widths one to three are numbers, a vec4 is a colour, and a picture is
/// the identity of a texture only the Sample box can read. No colour crosses
/// the bridge; the frontend maps type to theme token, exactly as the layer
/// graph's `BridgePortType` does.
enum BridgeShaderTy {
  f32,
  vec2,
  vec3,
  vec4,
  picture,
  ;
}

@freezed
sealed class BridgeSideInterp with _$BridgeSideInterp {
  const BridgeSideInterp._();

  const factory BridgeSideInterp.hold() = BridgeSideInterp_Hold;
  const factory BridgeSideInterp.linear() = BridgeSideInterp_Linear;
  const factory BridgeSideInterp.bezier(
    BridgeBezierSide field0,
  ) = BridgeSideInterp_Bezier;
  const factory BridgeSideInterp.auto(
    BridgeAutoSide field0,
  ) = BridgeSideInterp_Auto;
}

/// One entry of [`list_styles`]: the match name [`add_style`] takes, the
/// English label the menu row shows through the engine-label table, and whether
/// a menu should offer it at all.
///
/// [`add_style`]: crate::api::layer::LayerReference::add_style
class BridgeStyleInfo {
  final String name;
  final String label;

  /// Whether this style **renders** in this version (§8) — false for Satin
  /// and Bevel and emboss, which are declared and imported losslessly but
  /// draw nothing. A menu must not offer a style that changes no picture; a
  /// heading still has to be able to name one.
  final bool offered;

  const BridgeStyleInfo({
    required this.name,
    required this.label,
    required this.offered,
  });

  @override
  int get hashCode => name.hashCode ^ label.hashCode ^ offered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStyleInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          label == other.label &&
          offered == other.offered;
}

/// The unit a parameter's number is in — what the row draws as its
/// rider beside the value, and what a point pick has to write in.
///
/// Mirrors [`lumit_core::fx::Unit`] with the two the seam has no use for
/// folded away: `Unset` is a build failure engine-side, so nothing that ships
/// can carry it, and `PctDiag` is forbidden to every parameter. Both
/// arrive here as [`BridgeUnit::Raw`] — the panel draws no rider, which is the
/// honest answer for a unit that must not exist.
enum BridgeUnit {
  /// A plain number: a gamma, a count, a stop, a rate in Hz. No rider.
  raw,

  /// Per cent, where 100 is the whole of whatever it is a share of.
  percent,

  /// Pixels at composition size (px@comp) — the one spatial unit.
  px,
  degrees,
  seconds,

  /// Comp-rate frames.
  frames,
  ;
}
