// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'layer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'effect.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `animation_at`, `document_for`, `param`, `presets_in`, `read_at`, `read_at`, `read_at`, `read_instance_info`, `read`, `write_at`, `write_at`, `write`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_effects`, `new`

/// Every built-in effect, in schema order — the Add-effect menu's source of
/// truth ([`lumit_core::fx::BUILTINS`]), and the frb form of v0's `list_effects`.
///
/// Stateless, so it is a free function rather than a method: the menu is
/// available before any project is open.
List<BridgeEffectInfo> listEffects() =>
    BridgeLib.instance.api.crateApiEffectListEffects();

/// Every `.lumfx` in the preset library folder, sorted by name — what the
/// Effects & presets browser lists. A file that is not a preset (unreadable,
/// or not preset JSON) is simply not listed; the folder is the user's to put
/// things in, and a stray file there is not a fault.
List<BridgePresetInfo> listPresets() =>
    BridgeLib.instance.api.crateApiEffectListPresets();

/// Where the preset library lives, created on first ask — the save dialogue's
/// default folder, so a saved preset appears in the listing without the user
/// navigating anywhere. `None` only when the platform has no home directory.
String? presetsDirPath() =>
    BridgeLib.instance.api.crateApiEffectPresetsDirPath();

/// What `scalar` reads as at `time` — the value the picture is actually showing.
///
/// The panel needs this at exactly two moments, and both would be wrong done in
/// Dart. Turning animation *off* keeps the value the curve currently has, rather
/// than snapping to whatever the first key holds; adding a key at the playhead
/// seeds it with the value already on screen, so the act of adding a key never
/// moves the picture. Bezier keys make either one a real evaluation, not a
/// lerp — so this is the engine's own [`lumit_core::anim::evaluate`] rather than
/// a second implementation that would disagree with the renderer.
///
/// Sampling is in `f64` seconds, matching the engine: exactness is a property of
/// key *times* (which cross as integer pairs), not of a sampled value.
double sampleScalar(
        {required BridgeScalar scalar, required BridgeRational time}) =>
    BridgeLib.instance.api
        .crateApiEffectSampleScalar(scalar: scalar, time: time);

double sampleScalarWithContext(
        {required BridgeScalar scalar,
        required BridgeRational time,
        required LayerReference layer}) =>
    BridgeLib.instance.api.crateApiEffectSampleScalarWithContext(
        scalar: scalar, time: time, layer: layer);

Float64List sampleScalarRangeWithContext(
        {required BridgeScalar scalar,
        required LayerReference layer,
        required BridgeRational start,
        required BridgeRational end,
        required PlatformInt64 samples}) =>
    BridgeLib.instance.api.crateApiEffectSampleScalarRangeWithContext(
        scalar: scalar, layer: layer, start: start, end: end, samples: samples);

/// Every parameter `effect` declares, in schema order — what the panel draws a
/// row per.
///
/// Keyed by the same `match_name` [`list_effects`] hands out and `add_effect`
/// takes. An unknown name is an empty list rather than an error: a project
/// carrying an effect this build does not know still opens, and its instance
/// simply has no rows to draw.
List<BridgeParamInfo> listParameters({required String effect}) =>
    BridgeLib.instance.api.crateApiEffectListParameters(effect: effect);

/// Every parameter group `effect` declares, in schema order (empty for an
/// effect with none, or an unknown name). The panel inserts each group's
/// twirl at its first member's position and hides the members it covers from
/// the flat run.
List<BridgeParamGroup> listParameterGroups({required String effect}) =>
    BridgeLib.instance.api.crateApiEffectListParameterGroups(effect: effect);

/// Every greying rule `effect` declares (empty for an effect whose controls are
/// all independent, which is most of them, or for an unknown name — a project
/// carrying an effect this build does not know still opens).
List<BridgeEnabledWhen> listEnabledWhen({required String effect}) =>
    BridgeLib.instance.api.crateApiEffectListEnabledWhen(effect: effect);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeEffectInstance>>
abstract class BridgeEffectInstance implements RustOpaqueInterface {
  /// False when the effect is individually bypassed (docs/08 §1.5) — the state
  /// of the checkbox in its title bar.
  bool enabled();

  /// One read for everything a card draws — see [`BridgeEffectInstanceInfo`].
  BridgeEffectInstanceInfo getInfo();

  List<String> getParameters();

  /// A parameter's value, whatever kind it is. An unknown `id` is an error;
  /// every parameter an instance actually carries is expressible, so there is
  /// no "cannot represent this one" answer any more.
  BridgeEffectValue getValue({required String id});

  /// This instance's own id — what the stack ops on
  /// [`crate::api::layer::LayerReference`] address it by.
  UuidValue id();

  String name();

  String serialize();

  /// Stage the user's own name for this instance (K-321) — an empty or
  /// whitespace name clears it back to the effect's label. Staging only, like
  /// `set_value`: `LayerReference::set_effects` is the commit.
  void setCustomName({required String name});

  /// Overwrite a parameter on this staged copy. Nothing is committed — see the
  /// type's own documentation; `LayerReference::set_effects` is the commit.
  ///
  /// Refused when `value` is of a different kind from the parameter, so a
  /// control can never quietly change what a parameter *is*.
  void setValue({required String id, required BridgeEffectValue value});
}

/// A bezier side's After Effects-compatible handle: `speed` in value-units per
/// second, `influence` as a fraction of the gap to the neighbouring key.
class BridgeBezierSide {
  final double speed;
  final double influence;

  const BridgeBezierSide({
    required this.speed,
    required this.influence,
  });

  @override
  int get hashCode => speed.hashCode ^ influence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBezierSide &&
          runtimeType == other.runtimeType &&
          speed == other.speed &&
          influence == other.influence;
}

/// A colour parameter: four independently animatable scene-linear channels.
class BridgeColour {
  final BridgeScalar r;
  final BridgeScalar g;
  final BridgeScalar b;
  final BridgeScalar a;

  const BridgeColour({
    required this.r,
    required this.g,
    required this.b,
    required this.a,
  });

  @override
  int get hashCode => r.hashCode ^ g.hashCode ^ b.hashCode ^ a.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeColour &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          g == other.g &&
          b == other.b &&
          a == other.a;
}

/// One built-in effect as the Add-effect menu needs it: the stable `name` to
/// pass to [`crate::api::layer::LayerReference::add_effect`], the sentence-case
/// `label` to draw, and the category to group under. `category` is a stable
/// machine key the menu sorts by; `category_label` is its heading (K-090).
class BridgeEffectInfo {
  final String name;
  final String label;
  final String category;
  final String categoryLabel;

  const BridgeEffectInfo({
    required this.name,
    required this.label,
    required this.category,
    required this.categoryLabel,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      label.hashCode ^
      category.hashCode ^
      categoryLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEffectInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          label == other.label &&
          category == other.category &&
          categoryLabel == other.categoryLabel;
}

/// Everything a panel draws for one effect instance, in one crossing (K-183):
/// its id, match name, bypass state, and every parameter's current value. The
/// instance is an opaque handle, so `id()`/`name()`/`get_value()` each cross
/// the bridge — a card that read them one at a time cost a call per field per
/// parameter per rebuild.
class BridgeEffectInstanceInfo {
  final UuidValue id;
  final String name;

  /// The user's own name for the instance (K-321), or `None` to show the
  /// effect's label. `name` stays the `match_name` either way — it is the
  /// schema key, not a display string.
  final String? customName;
  final bool enabled;
  final List<BridgeParamValue> values;

  const BridgeEffectInstanceInfo({
    required this.id,
    required this.name,
    this.customName,
    required this.enabled,
    required this.values,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      customName.hashCode ^
      enabled.hashCode ^
      values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEffectInstanceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          customName == other.customName &&
          enabled == other.enabled &&
          values == other.values;
}

@freezed
sealed class BridgeEffectValue with _$BridgeEffectValue {
  const BridgeEffectValue._();

  const factory BridgeEffectValue.float(
    BridgeScalar field0,
  ) = BridgeEffectValue_Float;
  const factory BridgeEffectValue.point(
    BridgePoint field0,
  ) = BridgeEffectValue_Point;
  const factory BridgeEffectValue.colour(
    BridgeColour field0,
  ) = BridgeEffectValue_Colour;
  const factory BridgeEffectValue.bool(
    bool field0,
  ) = BridgeEffectValue_Bool;
  const factory BridgeEffectValue.choice(
    int field0,
  ) = BridgeEffectValue_Choice;
  const factory BridgeEffectValue.seed(
    int field0,
  ) = BridgeEffectValue_Seed;
  const factory BridgeEffectValue.file(
    BridgeFileParam field0,
  ) = BridgeEffectValue_File;
  const factory BridgeEffectValue.layer([
    UuidValue? field0,
  ]) = BridgeEffectValue_Layer;

  /// Which of the owning layer's masks an effect walks (K-408): the mask id,
  /// or `None` for "First mask". The *geometry* never crosses — the render
  /// flattens it engine-side, beside the op.
  const factory BridgeEffectValue.maskPath([
    UuidValue? field0,
  ]) = BridgeEffectValue_MaskPath;

  /// A tone curve as its own control points (K-412): 2..=16 `[x, y]` pairs
  /// in the unit square, in x order. Crosses as written — the engine
  /// straightens what it reads (`CurvePoints::sanitised`), so a panel
  /// mid-drag need not, and a curve is never refused for being momentarily
  /// out of order.
  const factory BridgeEffectValue.curve(
    List<Float32List> field0,
  ) = BridgeEffectValue_Curve;
}

@freezed
sealed class BridgeEnabledCond with _$BridgeEnabledCond {
  const BridgeEnabledCond._();

  /// Editable while the named bool holds this value.
  const factory BridgeEnabledCond.boolIs(
    bool field0,
  ) = BridgeEnabledCond_BoolIs;

  /// Editable while the named choice is on this option index.
  const factory BridgeEnabledCond.choiceIs(
    int field0,
  ) = BridgeEnabledCond_ChoiceIs;

  /// Editable while the named choice is on anything but this index.
  const factory BridgeEnabledCond.choiceIsNot(
    int field0,
  ) = BridgeEnabledCond_ChoiceIsNot;

  /// Editable while the named layer reference actually names a layer.
  const factory BridgeEnabledCond.layerSet() = BridgeEnabledCond_LayerSet;
}

/// One greying rule: `param`'s row is editable only while `on` satisfies
/// `cond`. The panel evaluates it against values it already holds, so ticking
/// a switch greys its dependent row without a round trip;
/// `lumit_core::fx::param_enabled` is the same rule in Rust and the authority
/// the tests pin.
class BridgeEnabledWhen {
  final String param;
  final String on_;
  final BridgeEnabledCond cond;

  const BridgeEnabledWhen({
    required this.param,
    required this.on_,
    required this.cond,
  });

  @override
  int get hashCode => param.hashCode ^ on_.hashCode ^ cond.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEnabledWhen &&
          runtimeType == other.runtimeType &&
          param == other.param &&
          on_ == other.on_ &&
          cond == other.cond;
}

/// A file parameter: the paths it references, and the index that selects which
/// one is live. Two paths cannot be blended, so the index only ever steps
/// (hold keyframes, K-111); the common case is one path and a static index.
/// An empty `paths` means unset, which the consuming effect treats as identity.
class BridgeFileParam {
  final List<String> paths;
  final BridgeScalar index;

  const BridgeFileParam({
    required this.paths,
    required this.index,
  });

  @override
  int get hashCode => paths.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFileParam &&
          runtimeType == other.runtimeType &&
          paths == other.paths &&
          index == other.index;
}

/// One keyframe on one scalar channel.
class BridgeKeyframe {
  final BridgeRational time;
  final double value;

  /// Approaching this key.
  final BridgeSideInterp interpIn;

  /// Leaving this key.
  final BridgeSideInterp interpOut;

  const BridgeKeyframe({
    required this.time,
    required this.value,
    required this.interpIn,
    required this.interpOut,
  });

  @override
  int get hashCode =>
      time.hashCode ^ value.hashCode ^ interpIn.hashCode ^ interpOut.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeKeyframe &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          value == other.value &&
          interpIn == other.interpIn &&
          interpOut == other.interpOut;
}

/// One collapsible parameter group of an effect (docs/08 §1.2, K-145/K-257):
/// the panel tucks the named member rows behind a twirl. An empty `label`
/// renders headerless (the rows appear in place, no twirl) — the shape a
/// conditional run of parameters takes. `visible_when_param` with a
/// non-empty `visible_when_values` shows the group only while that sibling
/// Choice parameter holds one of those indices.
class BridgeParamGroup {
  final String label;

  /// Member parameter ids — a contiguous run of the schema's parameters.
  final List<String> params;

  /// Whether the twirl starts closed.
  final bool collapsed;

  /// See the struct docs.
  final String? visibleWhenParam;

  /// See the struct docs. Empty when the group is unconditional.
  final Uint32List visibleWhenValues;

  const BridgeParamGroup({
    required this.label,
    required this.params,
    required this.collapsed,
    this.visibleWhenParam,
    required this.visibleWhenValues,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      params.hashCode ^
      collapsed.hashCode ^
      visibleWhenParam.hashCode ^
      visibleWhenValues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeParamGroup &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          params == other.params &&
          collapsed == other.collapsed &&
          visibleWhenParam == other.visibleWhenParam &&
          visibleWhenValues == other.visibleWhenValues;
}

/// One declared parameter of an effect, as the panel needs to *draw* it:
/// what to call it, what kind of control it is, and the range or option list
/// that control needs.
///
/// This is the schema, not the value — [`BridgeEffectValue`] carries what a
/// particular instance currently holds. The panel needs both: the value to show,
/// and this to know whether "0.5" wants a slider from 0 to 100 or a colour
/// channel, and what the third entry in a dropdown is called.
class BridgeParamInfo {
  /// Stable snake_case id — the key [`BridgeEffectInstance::get_value`] and
  /// `set_value` take.
  final String id;
  final String label;
  final BridgeParamKind kind;

  const BridgeParamInfo({
    required this.id,
    required this.label,
    required this.kind,
  });

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeParamInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          kind == other.kind;
}

@freezed
sealed class BridgeParamKind with _$BridgeParamKind {
  const BridgeParamKind._();

  const factory BridgeParamKind.float({
    required double default_,

    /// The slider's travel. Typing may exceed it (docs/08 §1.2); only
    /// `hard_min`/`hard_max` may not.
    required double sliderMin,
    required double sliderMax,

    /// Hard bounds, either side open (K-090: a threshold clamps at zero
    /// below and runs unbounded above).
    double? hardMin,
    double? hardMax,
  }) = BridgeParamKind_Float;

  /// A whole-number parameter (docs/08 §1.2): the value is still a Float
  /// scalar in the model — the kind only asks the row to step, display and
  /// commit whole numbers.
  const factory BridgeParamKind.int({
    required PlatformInt64 default_,
    required PlatformInt64 sliderMin,
    required PlatformInt64 sliderMax,
    PlatformInt64? hardMin,
    PlatformInt64? hardMax,
  }) = BridgeParamKind_Int;

  /// Degrees, drawn as a dial beneath the number (docs/07 §6). The value
  /// crossing the bridge is a [`BridgeEffectValue::Float`] — an angle is a
  /// number of degrees, and this kind only says which control to draw.
  /// Unbounded, so the dial winds through full turns.
  const factory BridgeParamKind.angle({
    required double default_,

    /// Snapping increment in degrees while a modifier is held.
    required double dialStep,
  }) = BridgeParamKind_Angle;
  const factory BridgeParamKind.choice({
    required List<String> options,
    required int default_,

    /// Option indices after which the dropdown draws a group divider (T21).
    /// Empty for an ungrouped list.
    required Uint32List dividersAfter,
  }) = BridgeParamKind_Choice;
  const factory BridgeParamKind.bool({
    required bool default_,
  }) = BridgeParamKind_Bool;
  const factory BridgeParamKind.colour({
    /// Scene-linear RGBA. Channels animate independently in the model, so
    /// the panel edits four scalars behind one swatch.
    required Float64List default_,

    /// Per-channel edit range — a linear value may exceed 1 (an HDR tint)
    /// or dip below 0 (a lift), so each colour declares its own.
    required double min,
    required double max,
  }) = BridgeParamKind_Colour;
  const factory BridgeParamKind.seed() = BridgeParamKind_Seed;
  const factory BridgeParamKind.file({
    /// Lower-case extensions without the dot, for the open dialog.
    required List<String> filter,
    required String filterName,
  }) = BridgeParamKind_File;
  const factory BridgeParamKind.layer() = BridgeParamKind_Layer;

  /// One of the **owning layer's masks**, whose geometry the effect walks
  /// (K-408, docs/08 §1.2). The panel draws the layer's masks by name, with
  /// "First mask" as the unset entry; the mask names come from the read model
  /// the panel already holds, so the row costs no call of its own.
  const factory BridgeParamKind.maskPath() = BridgeParamKind_MaskPath;

  /// A tone curve, drawn as a curve editor (K-412). The panel edits the
  /// point list itself; there is no range to declare, because the points
  /// live in the unit square by definition.
  const factory BridgeParamKind.curve() = BridgeParamKind_Curve;

  /// A closed range (K-414), drawn as a track and thumb with the value
  /// beside it. `min`/`max` are the travel *and* the hard bound — that is
  /// what closed means — so the row refuses a typed value outside them.
  ///
  /// The value crossing the bridge is a [`BridgeEffectValue::Float`], the
  /// arrangement `Int` and `Angle` already use: the kind says which control
  /// to draw, not how the number is stored, so the row keeps every float
  /// affordance including keyframes and the graph editor.
  const factory BridgeParamKind.slider({
    required double default_,
    required double min,
    required double max,
  }) = BridgeParamKind_Slider;

  /// A **button** (K-417), drawn as one and pressed through
  /// [`crate::api::layer::LayerReference::fire_effect_action`]. It carries no
  /// value at all — no default, no range, nothing in
  /// [`BridgeEffectInstanceInfo::values`] — because a press is an event and
  /// not a number that could be keyframed, undone or interpolated.
  const factory BridgeParamKind.action() = BridgeParamKind_Action;
}

/// One parameter's current value, as [`BridgeEffectInstance::get_info`]
/// carries it.
class BridgeParamValue {
  final String id;
  final BridgeEffectValue value;

  const BridgeParamValue({
    required this.id,
    required this.value,
  });

  @override
  int get hashCode => id.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeParamValue &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          value == other.value;
}

/// A point parameter: two independently animatable axes.
class BridgePoint {
  final BridgeScalar x;
  final BridgeScalar y;

  const BridgePoint({
    required this.x,
    required this.y,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

/// One saved `.lumfx` preset in the user's library: the display name it was
/// saved under and the file to read when applying it.
class BridgePresetInfo {
  final String name;
  final String path;

  const BridgePresetInfo({
    required this.name,
    required this.path,
  });

  @override
  int get hashCode => name.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePresetInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path;
}

/// An exact rational time in seconds, as `num / den`.
///
/// Keyframe times cross as the integer pair the document stores, never as
/// floating-point seconds (docs/17 "rational time crosses as integers"): a key
/// at 1/3 s read back as 0.333… and written again would no longer land on the
/// frame it was set on, and this round trip has to be exact.
class BridgeRational {
  final PlatformInt64 num;

  /// Always positive in anything the engine hands out; a zero or negative
  /// denominator coming the other way is refused, not normalised.
  final PlatformInt64 den;

  const BridgeRational({
    required this.num,
    required this.den,
  });

  @override
  int get hashCode => num.hashCode ^ den.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRational &&
          runtimeType == other.runtimeType &&
          num == other.num &&
          den == other.den;
}

@freezed
sealed class BridgeScalar with _$BridgeScalar {
  const BridgeScalar._();

  const factory BridgeScalar.static_(
    double field0,
  ) = BridgeScalar_Static;

  /// At least one key, strictly ascending in time — the invariant the
  /// engine's keyframe ops maintain, enforced here on the way in.
  const factory BridgeScalar.keyframed(
    List<BridgeKeyframe> field0,
  ) = BridgeScalar_Keyframed;
  const factory BridgeScalar.expression(
    String field0,
  ) = BridgeScalar_Expression;
}

@freezed
sealed class BridgeSideInterp with _$BridgeSideInterp {
  const BridgeSideInterp._();

  const factory BridgeSideInterp.hold() = BridgeSideInterp_Hold;
  const factory BridgeSideInterp.linear() = BridgeSideInterp_Linear;
  const factory BridgeSideInterp.bezier(
    BridgeBezierSide field0,
  ) = BridgeSideInterp_Bezier;
}
