// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'effect.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'state.dart';
part 'footage.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `attach_proxy`, `project`, `resolve_path`, `source_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `id`, `new`, `project_id`

/// How the running MAKE-PROXY job is getting on. Safe to call on the
/// interface's own cadence: it drains a channel and reads two numbers.
///
/// Reading is also what *finishes* the job: a transcode that has just landed is
/// attached to its item here, so an item gains its proxy whether or not the
/// panel that asked for it is still on screen.
BridgeProxyState proxyPoll() =>
    BridgeLib.instance.api.crateApiFootageProxyPoll();

/// Ask the running MAKE-PROXY job to stop. The half-written file is removed — a
/// cancelled proxy leaves nothing pretending to be a finished one.
void proxyCancel() => BridgeLib.instance.api.crateApiFootageProxyCancel();

/// A footage file's own vital statistics, as the container declares them.
///
/// What "a comp matching the footage" means when a clip is dragged onto the New
/// composition button (docs/07 §3.1): the size, the rate and the length come from
/// here. The rate is the exact pair the container carries and the duration is
/// rational seconds — both because a rate that went through a float would not come
/// back as 30000/1001 (docs/14 §2).
///
/// Audio-only media has no picture, so `width`/`height` are zero and the rate is
/// 0/1; the caller keeps its own size rather than making a comp no pixels wide.
class BridgeMediaInfo {
  final int width;
  final int height;
  final int fpsNum;
  final int fpsDen;
  final BridgeRational duration;

  /// The picture stream's codec as the container names it (`h264`, `png`),
  /// or `None` when there is no picture. The *user's* word for the file, not
  /// a display string of ours, so it crosses untranslated (K-303).
  final String? videoCodec;

  /// The sound stream's codec, or `None` when the file is silent.
  final String? audioCodec;

  /// The sound's channel count and rate in hertz. Both zero when there is no
  /// sound — the panel says nothing rather than "0 channels".
  final int channels;
  final int sampleRate;

  /// Whether the picture is a **still** rather than something that runs
  /// (K-246). A still probes with a video stream too — one frame of it — so
  /// the question is whether the stream lasts, and the engine
  /// ([`lumit_media::MediaProbe::runs_as_video`]) is the one place it is
  /// asked, so the panel cannot call a file a still while the Timeline cuts
  /// it as a clip.
  ///
  /// This is what replaced the panel's zero-picture-width inference: a file
  /// with no picture is `video_codec: None`, which is a different fact from
  /// a picture that does not move.
  final bool isStill;

  const BridgeMediaInfo({
    required this.width,
    required this.height,
    required this.fpsNum,
    required this.fpsDen,
    required this.duration,
    this.videoCodec,
    this.audioCodec,
    required this.channels,
    required this.sampleRate,
    required this.isStill,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      fpsNum.hashCode ^
      fpsDen.hashCode ^
      duration.hashCode ^
      videoCodec.hashCode ^
      audioCodec.hashCode ^
      channels.hashCode ^
      sampleRate.hashCode ^
      isStill.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeMediaInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          fpsNum == other.fpsNum &&
          fpsDen == other.fpsDen &&
          duration == other.duration &&
          videoCodec == other.videoCodec &&
          audioCodec == other.audioCodec &&
          channels == other.channels &&
          sampleRate == other.sampleRate &&
          isStill == other.isStill;
}

/// The stand-in file attached to one footage item, as the Project panel's row
/// reads it (K-501).
///
/// Three row states, all readable from here: no proxy at all (`None` from
/// [`FootageReference::get_proxy`]), one attached and being read (`in_use`), and
/// one attached but switched off — either by this item's own tick or by the
/// project's master switch.
///
/// Whether the file on the end of it is *usable* is a different question, about
/// media rather than about the document, and nothing here answers it: the
/// renderer falls back to the original on its own when a proxy is missing or
/// disagrees about the footage's length, deliberately without reporting it as
/// missing media.
class BridgeProxy {
  /// Where the stand-in is, in the same form the Path column shows for the
  /// original: the relative path a saved project carries, else the absolute
  /// one (K-173).
  final String path;

  /// This item's own *use proxy* tick.
  final bool enabled;

  /// Whether the document actually reads it — this item's tick and the
  /// project's master switch both on.
  final bool inUse;

  const BridgeProxy({
    required this.path,
    required this.enabled,
    required this.inUse,
  });

  @override
  int get hashCode => path.hashCode ^ enabled.hashCode ^ inUse.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProxy &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          enabled == other.enabled &&
          inUse == other.inUse;
}

@freezed
sealed class BridgeProxyState with _$BridgeProxyState {
  const BridgeProxyState._();

  /// Nothing has run since start-up.
  const factory BridgeProxyState.idle() = BridgeProxyState_Idle;
  const factory BridgeProxyState.running({
    required BigInt frame,

    /// Zero until the source's length has been read.
    required BigInt total,
  }) = BridgeProxyState_Running;

  /// The finished file — already attached to its item by the time this is
  /// read.
  const factory BridgeProxyState.done({
    required String path,
  }) = BridgeProxyState_Done;
  const factory BridgeProxyState.failed({
    required String error,
  }) = BridgeProxyState_Failed;
}

class FootageReference {
  final UuidValue internalproject;
  final UuidValue internalid;

  const FootageReference({
    required this.internalproject,
    required this.internalid,
  });

  /// Detach this item's proxy. The file on disk is left alone — a proxy took
  /// minutes to make, and forgetting it in the project is not a reason to
  /// delete it.
  void clearProxy() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceClearProxy(
        that: this,
      );

  /// Where this item's file is, as the *project* records it: the relative
  /// path a saved project actually carries (K-173), falling back to the
  /// absolute one only when the project has never been saved and there is
  /// nothing to be relative to.
  ///
  /// Display data — the Project panel's Path column. It says where the
  /// reference points, not whether anything is there; `get_status` is the
  /// question about the disk, and this deliberately touches none.
  String filePath() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceFilePath(
        that: this,
      );

  /// The proxy attached to this item, or `None` when there is none.
  BridgeProxy? getProxy() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceGetProxy(
        that: this,
      );

  Future<LumitMediaStatus> getStatus() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceGetStatus(
        that: this,
      );

  /// Make this item's proxy: transcode the original half as wide, and attach
  /// the result when it lands.
  ///
  /// Returns as soon as the job is *running*; ask [`proxy_poll`] how it is
  /// getting on. A second one while the first runs is a calm refusal — two
  /// transcodes share one disk.
  void makeProxy() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceMakeProxy(
        that: this,
      );

  Future<BridgeMediaInfo?> mediaInfo() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceMediaInfo(
        that: this,
      );

  /// Where MAKE-PROXY would write this item's proxy: beside the original,
  /// with `_proxy` before a `.mov` extension.
  ///
  /// Shown before the job starts, so a file already there can be pointed out
  /// rather than silently overwritten.
  String proxyPath() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceProxyPath(
        that: this,
      );

  /// Point this footage item at `path`, and fix every *other* missing item
  /// whose file name turns up in the same folder — one undo step for the lot.
  ///
  /// The sibling sweep is the behaviour that makes relinking a moved project
  /// bearable: footage almost always moves as a folder, so relinking one clip
  /// by hand should not mean relinking forty. A sibling is only touched when it
  /// currently fails to resolve *and* a file of its name exists beside the
  /// picked one, so a healthy item is never repointed.
  void relink({required String path}) => BridgeLib.instance.api
      .crateApiFootageFootageReferenceRelink(that: this, path: path);

  /// Attach `path` as this item's proxy, replacing any proxy already there,
  /// and switch it on.
  ///
  /// One undo step: the op carries the whole reference, so attaching and
  /// detaching invert each other exactly as a relink does.
  void setProxy({required String path}) => BridgeLib.instance.api
      .crateApiFootageFootageReferenceSetProxy(that: this, path: path);

  /// This item's own *use proxy* tick, leaving the proxy attached — how one
  /// clip is checked at full quality without giving up the proxy.
  ///
  /// Refused on an item with no proxy: the panel does not draw the tick on a
  /// row that has nothing to tick.
  void setUseProxy({required bool on_}) => BridgeLib.instance.api
      .crateApiFootageFootageReferenceSetUseProxy(that: this, on_: on_);

  Future<BridgeRenderedFrame?> thumbnail({required int maxEdge}) => BridgeLib
      .instance.api
      .crateApiFootageFootageReferenceThumbnail(that: this, maxEdge: maxEdge);

  @override
  int get hashCode => internalproject.hashCode ^ internalid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FootageReference &&
          runtimeType == other.runtimeType &&
          internalproject == other.internalproject &&
          internalid == other.internalid;
}

enum LumitMediaStatus {
  missing,
  ready,
  ;
}
