// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'effect.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'state.dart';

// These functions are ignored because they are not marked as `pub`: `project`, `resolve_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `eq`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `id`, `new`, `project_id`

/// A footage file's own vital statistics, as the container declares them.
///
/// What "a comp matching the footage" means when a clip is dragged onto the New
/// composition button (docs/07 §3.1): the size, the rate and the length come from
/// here. The rate is the exact pair the container carries and the duration is
/// rational seconds — both because a rate that went through a float would not come
/// back as 30000/1001 (docs/14 §2).
///
/// Audio-only media has no picture, so `width`/`height` are zero and the rate is
/// 0/1; the caller keeps its own size rather than making a comp no pixels wide.
class BridgeMediaInfo {
  final int width;
  final int height;
  final int fpsNum;
  final int fpsDen;
  final BridgeRational duration;

  /// The picture stream's codec as the container names it (`h264`, `png`),
  /// or `None` when there is no picture. The *user's* word for the file, not
  /// a display string of ours, so it crosses untranslated (K-303).
  final String? videoCodec;

  /// The sound stream's codec, or `None` when the file is silent.
  final String? audioCodec;

  /// The sound's channel count and rate in hertz. Both zero when there is no
  /// sound — the panel says nothing rather than "0 channels".
  final int channels;
  final int sampleRate;

  /// Whether the picture is a **still** rather than something that runs
  /// (K-246). A still probes with a video stream too — one frame of it — so
  /// the question is whether the stream lasts, and the engine
  /// ([`lumit_media::MediaProbe::runs_as_video`]) is the one place it is
  /// asked, so the panel cannot call a file a still while the Timeline cuts
  /// it as a clip.
  ///
  /// This is what replaced the panel's zero-picture-width inference: a file
  /// with no picture is `video_codec: None`, which is a different fact from
  /// a picture that does not move.
  final bool isStill;

  const BridgeMediaInfo({
    required this.width,
    required this.height,
    required this.fpsNum,
    required this.fpsDen,
    required this.duration,
    this.videoCodec,
    this.audioCodec,
    required this.channels,
    required this.sampleRate,
    required this.isStill,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      fpsNum.hashCode ^
      fpsDen.hashCode ^
      duration.hashCode ^
      videoCodec.hashCode ^
      audioCodec.hashCode ^
      channels.hashCode ^
      sampleRate.hashCode ^
      isStill.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeMediaInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          fpsNum == other.fpsNum &&
          fpsDen == other.fpsDen &&
          duration == other.duration &&
          videoCodec == other.videoCodec &&
          audioCodec == other.audioCodec &&
          channels == other.channels &&
          sampleRate == other.sampleRate &&
          isStill == other.isStill;
}

class FootageReference {
  final UuidValue internalproject;
  final UuidValue internalid;

  const FootageReference({
    required this.internalproject,
    required this.internalid,
  });

  /// Where this item's file is, as the *project* records it: the relative
  /// path a saved project actually carries (K-173), falling back to the
  /// absolute one only when the project has never been saved and there is
  /// nothing to be relative to.
  ///
  /// Display data — the Project panel's Path column. It says where the
  /// reference points, not whether anything is there; `get_status` is the
  /// question about the disk, and this deliberately touches none.
  String filePath() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceFilePath(
        that: this,
      );

  Future<LumitMediaStatus> getStatus() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceGetStatus(
        that: this,
      );

  Future<BridgeMediaInfo?> mediaInfo() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceMediaInfo(
        that: this,
      );

  /// Point this footage item at `path`, and fix every *other* missing item
  /// whose file name turns up in the same folder — one undo step for the lot.
  ///
  /// The sibling sweep is the behaviour that makes relinking a moved project
  /// bearable: footage almost always moves as a folder, so relinking one clip
  /// by hand should not mean relinking forty. A sibling is only touched when it
  /// currently fails to resolve *and* a file of its name exists beside the
  /// picked one, so a healthy item is never repointed.
  void relink({required String path}) => BridgeLib.instance.api
      .crateApiFootageFootageReferenceRelink(that: this, path: path);

  Future<BridgeRenderedFrame?> thumbnail({required int maxEdge}) => BridgeLib
      .instance.api
      .crateApiFootageFootageReferenceThumbnail(that: this, maxEdge: maxEdge);

  @override
  int get hashCode => internalproject.hashCode ^ internalid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FootageReference &&
          runtimeType == other.runtimeType &&
          internalproject == other.internalproject &&
          internalid == other.internalid;
}

enum LumitMediaStatus {
  missing,
  ready,
  ;
}
