// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'graph.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `catalogue_ports`, `core`, `core`, `of`, `of`, `of`, `of`, `of`, `param_ports`, `read_layer_graph`, `wiring_into`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// One wire.
class BridgeGraphEdge {
  final BridgeOutputRef from;
  final BridgeInputRef to;

  const BridgeGraphEdge({
    required this.from,
    required this.to,
  });

  @override
  int get hashCode => from.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGraphEdge &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to;
}

/// One box on the canvas, as it is drawn.
///
/// Derived, not stored: the engine works this out from the layer each time it
/// is asked, so there is nothing here to write back. What the user *edits*
/// lives in [`BridgeGraphWiring`], and a driver's parameters ride the ordinary
/// staged-instance path (`LayerReference::get_graph_drivers`).
class BridgeGraphNode {
  final BridgeNodeRef node;

  /// The effect's schema key, empty for the two derived boxes. Not display
  /// text — `label` is.
  final String matchName;

  /// What the box is called, in English.
  final String label;

  /// The user's own name for this instance, shown in place of
  /// `label`. Always `None` for the derived boxes.
  final String? customName;

  /// False draws the border dashed — the `B` badge. Always true for the
  /// derived boxes, which cannot be bypassed.
  final bool enabled;
  final List<BridgePort> inputs;
  final List<BridgePort> outputs;

  const BridgeGraphNode({
    required this.node,
    required this.matchName,
    required this.label,
    this.customName,
    required this.enabled,
    required this.inputs,
    required this.outputs,
  });

  @override
  int get hashCode =>
      node.hashCode ^
      matchName.hashCode ^
      label.hashCode ^
      customName.hashCode ^
      enabled.hashCode ^
      inputs.hashCode ^
      outputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGraphNode &&
          runtimeType == other.runtimeType &&
          node == other.node &&
          matchName == other.matchName &&
          label == other.label &&
          customName == other.customName &&
          enabled == other.enabled &&
          inputs == other.inputs &&
          outputs == other.outputs;
}

/// The half of the graph the user edits: wires, positions, which boxes are
/// grown to show every socket, and the named regions behind them.
///
/// Read out of [`BridgeLayerGraph`], changed, and handed straight back to
/// `LayerReference::set_graph` — one gesture, one op, one undo step. There is
/// deliberately no per-wire call: adding a driver *and* auto-wiring it is one
/// write, which is what makes it one undo step (docs/impl/node-graph.md §3).
class BridgeGraphWiring {
  final List<BridgeGraphEdge> edges;
  final List<BridgeNodePosition> layout;

  /// The boxes whose `E` badge is on. A wired socket is drawn whether its box
  /// is exposed or not.
  final List<BridgeNodeRef> exposed;

  /// The named regions.
  final List<BridgeNodeGroup> groups;

  /// The Layer out box's image socket is unplugged, so the layer draws
  /// nothing. It rides here rather than as a call of its own so
  /// that unplugging it is the same one commit, and the same one undo step,
  /// as every other wiring gesture.
  final bool outUnwired;

  const BridgeGraphWiring({
    required this.edges,
    required this.layout,
    required this.exposed,
    required this.groups,
    required this.outUnwired,
  });

  @override
  int get hashCode =>
      edges.hashCode ^
      layout.hashCode ^
      exposed.hashCode ^
      groups.hashCode ^
      outUnwired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGraphWiring &&
          runtimeType == other.runtimeType &&
          edges == other.edges &&
          layout == other.layout &&
          exposed == other.exposed &&
          groups == other.groups &&
          outUnwired == other.outUnwired;
}

@freezed
sealed class BridgeInputRef with _$BridgeInputRef {
  const BridgeInputRef._();

  /// A parameter socket: the parameter follows the wire instead of its own
  /// keyframes. At most one wire per socket.
  const factory BridgeInputRef.param({
    required BridgeNodeRef node,
    required String port,
  }) = BridgeInputRef_Param;

  /// An effect's matte input.
  const factory BridgeInputRef.matte({
    required UuidValue effect,
  }) = BridgeInputRef_Matte;
}

/// A layer's whole graph, in one crossing.
class BridgeLayerGraph {
  /// Every box, in draw order: the Source, one per effect **in stack order**,
  /// the Layer out, then the drivers in document order. Filtering this to the
  /// `Effect` boxes gives the effect stack exactly as the Effect controls
  /// panel lists it — the graph has no second opinion about the picture's
  /// path, because the stack *is* the path (§1.1).
  final List<BridgeGraphNode> nodes;
  final BridgeGraphWiring wiring;

  const BridgeLayerGraph({
    required this.nodes,
    required this.wiring,
  });

  @override
  int get hashCode => nodes.hashCode ^ wiring.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLayerGraph &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          wiring == other.wiring;
}

/// A named region of the canvas: a tinted wash behind a set of boxes.
///
/// **No rectangle crosses**, and no colour: the wash is worked out from where
/// the members are sitting, and `colour` is an index into the frontend's own
/// label palette taken modulo its length. The engine has never known what a
/// colour is, and it does not know what a node card is either.
class BridgeNodeGroup {
  final String name;
  final int colour;
  final List<BridgeNodeRef> members;

  const BridgeNodeGroup({
    required this.name,
    required this.colour,
    required this.members,
  });

  @override
  int get hashCode => name.hashCode ^ colour.hashCode ^ members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeNodeGroup &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          colour == other.colour &&
          members == other.members;
}

/// Where one box sits on the canvas, in canvas units.
///
/// Document data: positions persist and travel with the project, and are
/// committed by the same whole-graph write as the wires. A box with no entry is
/// auto-placed by the panel.
class BridgeNodePosition {
  final BridgeNodeRef node;
  final double x;
  final double y;

  const BridgeNodePosition({
    required this.node,
    required this.x,
    required this.y,
  });

  @override
  int get hashCode => node.hashCode ^ x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeNodePosition &&
          runtimeType == other.runtimeType &&
          node == other.node &&
          x == other.x &&
          y == other.y;
}

@freezed
sealed class BridgeNodeRef with _$BridgeNodeRef {
  const BridgeNodeRef._();

  const factory BridgeNodeRef.source() = BridgeNodeRef_Source;
  const factory BridgeNodeRef.effect(
    UuidValue field0,
  ) = BridgeNodeRef_Effect;
  const factory BridgeNodeRef.driver(
    UuidValue field0,
  ) = BridgeNodeRef_Driver;
  const factory BridgeNodeRef.out() = BridgeNodeRef_Out;
}

@freezed
sealed class BridgeOutputRef with _$BridgeOutputRef {
  const BridgeOutputRef._();

  /// A driver's declared output port.
  const factory BridgeOutputRef.driver({
    required UuidValue node,
    required String port,
  }) = BridgeOutputRef_Driver;

  /// The layer's own masked source alpha at that point in the chain (§1.4).
  const factory BridgeOutputRef.sourceMatte() = BridgeOutputRef_SourceMatte;

  /// A **stack effect's** declared data output — Particulate's Points stream.
  /// The effect goes on making its picture for the chain; this taps
  /// the data it declares beside it, and carries no picture itself.
  const factory BridgeOutputRef.effectData({
    required UuidValue effect,
    required String port,
  }) = BridgeOutputRef_EffectData;
}

/// One socket on a box: the id the document writes down, the English word drawn
/// beside it, what it carries, and whether a wire is on it.
class BridgePort {
  final String id;
  final String label;
  final BridgePortType portType;

  /// Whether a wire lands on (an input) or leaves from (an output) this
  /// socket. The image chain's own sockets are wired by construction — the
  /// picture always flows straight down the stack.
  final bool wired;

  const BridgePort({
    required this.id,
    required this.label,
    required this.portType,
    required this.wired,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ portType.hashCode ^ wired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePort &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          portType == other.portType &&
          wired == other.wired;
}

/// What a socket carries, and so what colour the frontend draws it. Seven
/// types, five colours: image with matte, number, colour, shape with points,
/// audio.
enum BridgePortType {
  image,
  matte,
  number,
  colour,
  shape,
  points,
  audio,
  ;
}
