// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `preset_map`, `row`, `with_keymap`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Every binding, grouped by context in the order the page lists them — the
/// whole table in one call.
///
/// Rebuilt from the map each time rather than cached: it is a few hundred short
/// strings, it is read once when the page opens and once per edit, and a cache
/// here would be one more thing that can disagree with the truth.
List<BridgeKeymapGroup> keymapGroups() =>
    BridgeLib.instance.api.crateApiKeymapKeymapGroups();

/// The rows matching `query` across every context — the search box above the
/// table. An empty query matches everything.
List<BridgeKeyBinding> keymapSearch({required String query}) =>
    BridgeLib.instance.api.crateApiKeymapKeymapSearch(query: query);

/// Every chord that could fire two actions at once, described for display.
/// Empty when the keymap is unambiguous, which is the shipped state.
List<BridgeKeyConflict> keymapConflicts() =>
    BridgeLib.instance.api.crateApiKeymapKeymapConflicts();

/// Every chord a panel takes over from an app-wide binding, described for
/// display (K-281). Said out loud beside the table rather than flagged as
/// something to fix — the shipped default carries one on purpose (`L`).
List<BridgeKeyShadow> keymapShadows() =>
    BridgeLib.instance.api.crateApiKeymapKeymapShadows();

/// What `chord` does while `context` is focused, or `None` for nothing bound.
///
/// This is the dispatch path: every keypress the frontend sees becomes chord
/// text and comes through here. Sync and lock-light for that reason — it is a
/// linear scan of a few hundred bindings, which is nothing beside the frame it
/// happens in, and it must never be the reason a keypress feels late.
String? keymapLookup(
        {required BridgeKeyContext context, required String chord}) =>
    BridgeLib.instance.api
        .crateApiKeymapKeymapLookup(context: context, chord: chord);

/// Point an action at a new chord, and hand back the table as it now stands.
///
/// Rejects only chord text that is not a chord; a chord another action already
/// holds is accepted deliberately, because refusing it would make swapping two
/// actions' keys impossible. Within one context the previous owner is left
/// unbound and its row goes blank; a panel-scoped binding taking an app-wide
/// chord leaves both alive, the panel's winning where it is focused, and
/// [`keymap_shadows`] says so (K-281).
Future<List<BridgeKeymapGroup>> keymapRebind(
        {required BridgeKeyContext context,
        required String action,
        required String chord}) =>
    BridgeLib.instance.api.crateApiKeymapKeymapRebind(
        context: context, action: action, chord: chord);

/// Leave an action with no chord at all, and hand back the table.
Future<List<BridgeKeymapGroup>> keymapUnbind(
        {required BridgeKeyContext context, required String action}) =>
    BridgeLib.instance.api
        .crateApiKeymapKeymapUnbind(context: context, action: action);

/// Put one action back to the chord the shipped default gives it, and hand
/// back the table. Nothing else in the map is touched — this is the per-row
/// reset, not [`keymap_load_preset`]. Always the Lumit default: "reset" on a
/// settings row means "what the app ships with", whichever preset was loaded
/// since.
Future<List<BridgeKeymapGroup>> keymapResetBinding(
        {required BridgeKeyContext context, required String action}) =>
    BridgeLib.instance.api
        .crateApiKeymapKeymapResetBinding(context: context, action: action);

/// Replace the whole keymap with a shipped preset, and hand back the table.
Future<List<BridgeKeymapGroup>> keymapLoadPreset(
        {required BridgeKeymapPreset preset}) =>
    BridgeLib.instance.api.crateApiKeymapKeymapLoadPreset(preset: preset);

/// The whole keymap as JSON — what the frontend stores between sessions and
/// what "Export keymap…" writes to a file the user can share. One format for
/// both, so a keymap that survives a restart is the same keymap that travels.
String keymapToJson() => BridgeLib.instance.api.crateApiKeymapKeymapToJson();

/// Take a keymap back from JSON — a restored session, or an imported file — and
/// hand back the table.
///
/// Rejects anything that is not a keymap rather than half-applying it, so a
/// corrupt stored blob or somebody else's JSON leaves the current map alone.
///
/// **Laid over the shipped defaults, not swapped for them** (K-302). A file
/// only knows the actions that existed when it was written, and it used to
/// replace the map whole — so every action added since was left with no chord
/// at all for anyone who had ever saved a keymap. That is how `Ctrl+C` came to
/// do nothing in a build whose every test passed. An action the file names
/// keeps the file's chord and an action it deliberately unbound stays unbound;
/// only the ones it never heard of take their default.
Future<List<BridgeKeymapGroup>> keymapFromJson({required String json}) =>
    BridgeLib.instance.api.crateApiKeymapKeymapFromJson(json: json);

/// One row of the Settings → Keymap table: what the action is called, what it
/// is called internally, and the chord that runs it.
class BridgeKeyBinding {
  final BridgeKeyContext context;

  /// The stable id, e.g. `"playback.toggle"` — what the frontend switches on.
  final String action;

  /// What the table shows in its left-hand column, e.g. "Play or pause".
  final String description;

  /// The chord in its canonical text form, e.g. `"Mod+Shift+P"`. Empty when
  /// the action is currently unbound, which is a state the table shows
  /// rather than hides. One chord per row — K-200 settled that no shipped
  /// action carries two, so a list here would be structure with nothing to
  /// hold.
  final String chord;

  const BridgeKeyBinding({
    required this.context,
    required this.action,
    required this.description,
    required this.chord,
  });

  @override
  int get hashCode =>
      context.hashCode ^
      action.hashCode ^
      description.hashCode ^
      chord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeKeyBinding &&
          runtimeType == other.runtimeType &&
          context == other.context &&
          action == other.action &&
          description == other.description &&
          chord == other.chord;
}

/// One chord that could fire more than one action where both are live — what
/// the page warns about, and what the user resolves by rebinding one of them.
class BridgeKeyConflict {
  final String chord;

  /// The competing actions, already described for display.
  final List<String> actions;

  const BridgeKeyConflict({
    required this.chord,
    required this.actions,
  });

  @override
  int get hashCode => chord.hashCode ^ actions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeKeyConflict &&
          runtimeType == other.runtimeType &&
          chord == other.chord &&
          actions == other.actions;
}

/// Where a binding is live. Mirrors `lumit_keymap::KeyContext` across the seam.
enum BridgeKeyContext {
  global,
  tools,
  project,
  timeline,
  viewer,
  graph,
  panels,
  effects,
  ;
}

/// One chord a panel takes over from an app-wide binding (K-281).
///
/// **Not a clash.** The focused panel gets first refusal and the app-wide
/// binding is the fallback, so the chord runs exactly one action and which one
/// is never in doubt. It is reported because the app-wide meaning does stop
/// working in that one panel, and somebody reading their keymap should be able
/// to see that rather than discover it by pressing the key.
class BridgeKeyShadow {
  final String chord;

  /// Where the takeover applies, e.g. "Timeline".
  final String context;

  /// What the chord does there, described for display.
  final String action;

  /// What it does everywhere else.
  final String shadowed;

  const BridgeKeyShadow({
    required this.chord,
    required this.context,
    required this.action,
    required this.shadowed,
  });

  @override
  int get hashCode =>
      chord.hashCode ^ context.hashCode ^ action.hashCode ^ shadowed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeKeyShadow &&
          runtimeType == other.runtimeType &&
          chord == other.chord &&
          context == other.context &&
          action == other.action &&
          shadowed == other.shadowed;
}

/// One context's worth of rows, with the heading to put above them — the shape
/// the settings page draws top to bottom.
class BridgeKeymapGroup {
  final BridgeKeyContext context;

  /// The heading, e.g. "Timeline" or "Anywhere".
  final String label;
  final List<BridgeKeyBinding> bindings;

  const BridgeKeymapGroup({
    required this.context,
    required this.label,
    required this.bindings,
  });

  @override
  int get hashCode => context.hashCode ^ label.hashCode ^ bindings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeKeymapGroup &&
          runtimeType == other.runtimeType &&
          context == other.context &&
          label == other.label &&
          bindings == other.bindings;
}

/// Which shipped keymap to load wholesale.
enum BridgeKeymapPreset {
  /// Lumit's own defaults (docs/07 §15).
  lumit,

  /// The After Effects muscle-memory alternate.
  afterEffects,
  ;
}
