// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'layer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `press`, `read`, `read`, `roto_block_mut`, `roto_block`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The Roto brush `effect` on `layer`, as its status row draws it.
///
/// **Polled while it is moving and never otherwise** (the camera track's §5c
/// second deviation): a press moves no document revision, so there is nothing to
/// refresh against, and the engine keeps progress as a value in a map precisely
/// so nobody has to hold a subscription.
BridgeRotoStatus rotoStatus(
        {required LayerReference layer, required UuidValue effect}) =>
    BridgeLib.instance.api.crateApiRotoRotoStatus(layer: layer, effect: effect);

/// Why a propagation produced no mattes.
///
/// A **reason, not a sentence** (K-303): the engine's own `RotoFailure` carries
/// English, and English crossing here would ship untranslated inside a
/// translated window. Dart switches over this and picks the arb key, which is
/// the shape `BridgeTrackFailure` already uses.
enum BridgeRotoFailure {
  /// No resolved media fingerprint — nothing to key a cache with.
  offline,

  /// No optical flow on this device. Refused rather than degraded to the CPU
  /// oracle, which at seconds a frame pair would look like a hang.
  flowUnavailable,

  /// One propagation at a time.
  busy,

  /// Propagate pressed before any stroke.
  noBaseFrame,

  /// The media could not be opened, or carries no video.
  unreadable,

  /// Opened, but with no frames to propagate through.
  noFrames,

  /// The base frame's strokes do not describe a subject.
  noSeeds,
  ;
}

/// How far a propagation has got — the bridge form of
/// [`lumit_render::roto::Progress`], flattened so the panel reads fields rather
/// than unwrapping a shape.
enum BridgeRotoStage {
  /// Nothing has ever been asked for this brush in this session.
  idle,

  /// Accepted, not started.
  queued,

  /// Working outward from the base frame.
  solving,

  /// There is a run in the store.
  done,

  /// Stopped between frames. **The finished prefix was kept** (K-540), so the
  /// span below is real and a later Propagate resumes from it.
  cancelled,

  /// Refused — see [`BridgeRotoStatus::failure`].
  failed,
  ;
}

/// Everything the Roto brush's status row draws, in one crossing.
class BridgeRotoStatus {
  final BridgeRotoStage stage;

  /// Frames finished so far, and how many the clip has. Both zero outside
  /// [`BridgeRotoStage::Solving`].
  final int done;
  final int total;

  /// How many of `done` were **copied** from an earlier run rather than
  /// solved — the number that makes prefix reuse visible to the person
  /// waiting (docs/impl/roto.md §5).
  final int reused;

  /// Set only at [`BridgeRotoStage::Failed`].
  final BridgeRotoFailure? failure;

  /// The span the matte actually covers, in **source** frames, or `None`
  /// before anything has been propagated. Outside it the effect is a
  /// passthrough and the panel says so.
  final PlatformInt64? firstFrame;
  final PlatformInt64? lastFrame;

  /// How many frames the clip has, against which the span is whole or
  /// partial. Zero when nothing has been propagated.
  final int clipFrames;

  /// Whether there is a base frame at all — what makes Propagate offerable
  /// rather than a button that refuses.
  final PlatformInt64? baseFrame;

  /// How many strokes the instance holds.
  final int strokes;

  const BridgeRotoStatus({
    required this.stage,
    required this.done,
    required this.total,
    required this.reused,
    this.failure,
    this.firstFrame,
    this.lastFrame,
    required this.clipFrames,
    this.baseFrame,
    required this.strokes,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      done.hashCode ^
      total.hashCode ^
      reused.hashCode ^
      failure.hashCode ^
      firstFrame.hashCode ^
      lastFrame.hashCode ^
      clipFrames.hashCode ^
      baseFrame.hashCode ^
      strokes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRotoStatus &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          done == other.done &&
          total == other.total &&
          reused == other.reused &&
          failure == other.failure &&
          firstFrame == other.firstFrame &&
          lastFrame == other.lastFrame &&
          clipFrames == other.clipFrames &&
          baseFrame == other.baseFrame &&
          strokes == other.strokes;
}

/// One stored stroke, as the overlay draws it.
class BridgeRotoStroke {
  final UuidValue id;

  /// `[x0, y0, x1, y1, …]` in source raster pixels (K-248).
  final Float32List points;
  final double radius;
  final BridgeRotoStrokeKind kind;
  final PlatformInt64 frame;

  const BridgeRotoStroke({
    required this.id,
    required this.points,
    required this.radius,
    required this.kind,
    required this.frame,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      points.hashCode ^
      radius.hashCode ^
      kind.hashCode ^
      frame.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRotoStroke &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          points == other.points &&
          radius == other.radius &&
          kind == other.kind &&
          frame == other.frame;
}

/// What a stroke claims — the bridge's copy of
/// [`lumit_core::roto::RotoStrokeKind`], so Dart switches over a generated enum
/// rather than passing a number nobody checks.
enum BridgeRotoStrokeKind {
  /// This is the subject.
  foreground,

  /// This is not.
  background,

  /// Give this the refine band, whatever the segmentation decided.
  refine,
  ;
}
