// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'composition.dart';
import 'folder.dart';
import 'footage.dart';
import 'layer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'project.dart';
import 'project_item.dart';
import 'solid.dart';
import 'state.dart';
part 'share.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `describe`, `ending`, `events_for`, `let_go`, `person`, `resume`, `saved`, `saving`, `stop_all`, `stop`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The port a host listens on unless the person picks another.
int shareDefaultPort() =>
    BridgeLib.instance.api.crateApiShareShareDefaultPort();

/// This machine's address on its network, to offer in an invite. A guess the
/// person can type over, for a VPN or a forwarded port.
String shareLocalAddress() =>
    BridgeLib.instance.api.crateApiShareShareLocalAddress();

/// Join the project an invite names. It opens as a new, unsaved project in
/// place of whatever was open, so saving it writes this person's own copy.
///
/// `footage` is the folder this machine keeps the project's footage in. Each
/// item is looked for there by name and then by fingerprint, and what is not
/// found shows as missing, to be relinked like any other.
///
/// Not sync: it waits on the network and on the whole document arriving.
Future<BridgeJoinOutcome> joinSharedProject(
        {required String invite,
        required String name,
        String? footage,
        RustStreamSink<ScopedChange>? onChangeStream,
        RustStreamSink<BridgeShareEvent>? events}) =>
    BridgeLib.instance.api.crateApiShareJoinSharedProject(
        invite: invite,
        name: name,
        footage: footage,
        onChangeStream: onChangeStream,
        events: events);

@freezed
sealed class BridgeJoinOutcome with _$BridgeJoinOutcome {
  const BridgeJoinOutcome._();

  const factory BridgeJoinOutcome.joined({
    required ProjectReference project,
  }) = BridgeJoinOutcome_Joined;

  /// The text is not an invite.
  const factory BridgeJoinOutcome.badInvite() = BridgeJoinOutcome_BadInvite;

  /// Nobody answered at that address, or the invite was not accepted.
  const factory BridgeJoinOutcome.unreachable() = BridgeJoinOutcome_Unreachable;
  const factory BridgeJoinOutcome.versionMismatch({
    required String host,
  }) = BridgeJoinOutcome_VersionMismatch;
  const factory BridgeJoinOutcome.full() = BridgeJoinOutcome_Full;
  const factory BridgeJoinOutcome.unsafe() = BridgeJoinOutcome_Unsafe;
  const factory BridgeJoinOutcome.failed() = BridgeJoinOutcome_Failed;
}

/// Edits this guest made while its host was away that touch something the
/// host's side changed too. Held until the person chooses.
class BridgeShareConflict {
  /// What the first held edit is called in the History list, in the
  /// engine's English.
  final String step;

  /// The project item it touched, or the composition its layer is in.
  final String? item;
  final String? layer;

  /// How many edits are held.
  final int edits;

  const BridgeShareConflict({
    required this.step,
    this.item,
    this.layer,
    required this.edits,
  });

  @override
  int get hashCode =>
      step.hashCode ^ item.hashCode ^ layer.hashCode ^ edits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeShareConflict &&
          runtimeType == other.runtimeType &&
          step == other.step &&
          item == other.item &&
          layer == other.layer &&
          edits == other.edits;
}

@freezed
sealed class BridgeShareEnding with _$BridgeShareEnding {
  const BridgeShareEnding._();

  /// The host stopped sharing.
  const factory BridgeShareEnding.closed() = BridgeShareEnding_Closed;

  /// The host runs another version of Lumit, which `host` names.
  const factory BridgeShareEnding.versionMismatch({
    required String host,
  }) = BridgeShareEnding_VersionMismatch;

  /// The project already has as many people as it takes.
  const factory BridgeShareEnding.full() = BridgeShareEnding_Full;

  /// The host's project is one this machine will not open.
  const factory BridgeShareEnding.unsafe() = BridgeShareEnding_Unsafe;

  /// The host took this person out of the project.
  const factory BridgeShareEnding.removed() = BridgeShareEnding_Removed;
}

@freezed
sealed class BridgeShareEvent with _$BridgeShareEvent {
  const BridgeShareEvent._();

  /// Who is here and what each is looking at. The whole list each time.
  const factory BridgeShareEvent.people({
    required List<BridgeSharePerson> people,
  }) = BridgeShareEvent_People;

  /// This guest has lost its host and is working on alone until it is back.
  const factory BridgeShareEvent.away() = BridgeShareEvent_Away;

  /// The host is back. The document was replaced by the host's with this
  /// guest's own edits merged in, so everything on screen is stale. `held`
  /// conflicts wait in `share_conflicts`, and `refused` edits no longer
  /// applied and are gone.
  const factory BridgeShareEvent.back({
    required int held,
    required int refused,
  }) = BridgeShareEvent_Back;

  /// The invite this guest is looking for its host by leads to a different
  /// project. It is still away and still looking.
  const factory BridgeShareEvent.elsewhere() = BridgeShareEvent_Elsewhere;

  /// Sharing is over for this guest. The project stays open as it is.
  const factory BridgeShareEvent.ended({
    required BridgeShareEnding reason,
  }) = BridgeShareEvent_Ended;
}

/// One person in a shared project, and what they are looking at.
class BridgeSharePerson {
  final int id;
  final String name;

  /// An index into the label palette, from 1, given out in joining order.
  final int colour;

  /// This is the person at this machine.
  final bool me;

  /// The composition they have open, if it is still in the project.
  final CompositionReference? comp;

  /// The layers they have selected in it.
  final List<LayerReference> layers;

  /// The frame their playhead is on in `comp`.
  final PlatformInt64? playhead;

  /// Their pointer over the Viewer, in composition pixels.
  final double? cursorX;
  final double? cursorY;

  const BridgeSharePerson({
    required this.id,
    required this.name,
    required this.colour,
    required this.me,
    this.comp,
    required this.layers,
    this.playhead,
    this.cursorX,
    this.cursorY,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      colour.hashCode ^
      me.hashCode ^
      comp.hashCode ^
      layers.hashCode ^
      playhead.hashCode ^
      cursorX.hashCode ^
      cursorY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSharePerson &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          colour == other.colour &&
          me == other.me &&
          comp == other.comp &&
          layers == other.layers &&
          playhead == other.playhead &&
          cursorX == other.cursorX &&
          cursorY == other.cursorY;
}

@freezed
sealed class BridgeShareStarted with _$BridgeShareStarted {
  const BridgeShareStarted._();

  /// Sharing, and listening on `port`. `key` is the invite's secret, to
  /// hand back to [`ProjectReference::share`] when this project is shared
  /// again, so the invite people already hold still finds it. `restored`
  /// edits made since the project was last saved were put back first: the
  /// project had been closed without saving, and the people coming back
  /// were working on a document with them in.
  const factory BridgeShareStarted.sharing({
    required int port,
    required String key,
    required int restored,
  }) = BridgeShareStarted_Sharing;

  /// Something else on this machine has the port.
  const factory BridgeShareStarted.portInUse() = BridgeShareStarted_PortInUse;

  /// The project is already shared, or the system would not listen.
  const factory BridgeShareStarted.failed() = BridgeShareStarted_Failed;
}
