// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// What this build can truthfully say about itself at load time (K-008).
///
/// Facts only. The GPU adapter is not named, because it is not known until the
/// first render — a splash that claimed one would be inventing it.
List<String> bootLog() => BridgeLib.instance.api.crateApiShellBootLog();

/// The tier in force. A readout, not a setting: the controller measures real
/// render costs and decides, so there is nothing here to set.
BridgePlaybackTier playbackTier() =>
    BridgeLib.instance.api.crateApiShellPlaybackTier();

/// Start the controller again, optimistic at full.
///
/// Called when playback stops or the composition changes, so a fresh run does
/// not inherit a tier that a different, heavier comp earned.
BridgePlaybackTier resetRealtime() =>
    BridgeLib.instance.api.crateApiShellResetRealtime();

/// Render live drags at the Viewer's own resolution instead of the drag budget
/// (K-744, qualifying K-383).
///
/// K-383 caps a drag preview at a 640x360 raster so the picture keeps up with
/// the pointer, and said the reduction needed no flag from the frontend. This
/// is that flag, and only that: `true` renders a dragged frame exactly as a
/// committed one, sharp and as slow as the composition really is. Everything
/// else about a drag is unchanged.
///
/// A setting rather than a render argument, so it cannot be forgotten by a new
/// drag call site — the same reason the reduction itself lives in the worker.
/// The engine holds the live choice with no store behind it, so the settings
/// file carries it and hands it back at boot, as the cache budgets do.
void setFullResDragPreviews({required bool fullRes}) => BridgeLib.instance.api
    .crateApiShellSetFullResDragPreviews(fullRes: fullRes);

/// How often Lumit writes a rotating copy of every open project, and how many
/// copies it keeps (docs/10-FILE-FORMAT.md §4).
///
/// `minutes` of 0 turns autosave off, which is a setting a user is entitled to
/// hold. Both values are application settings rather than project data — how
/// often this machine copies your work is a property of the machine — so the
/// frontend owns the file they live in and calls this at boot and on every
/// change. The timer itself is the engine's, because the document is.
///
/// Nothing is written for a project that has not moved since its last save or
/// its own last autosave, and nothing is written for one that has never been
/// saved: the copies live beside the project file, and the crash journal is
/// what covers a project with no file yet.
void setAutosave({required int minutes, required int keep}) =>
    BridgeLib.instance.api
        .crateApiShellSetAutosave(minutes: minutes, keep: keep);

/// The autosaves beside `project`, newest first.
///
/// An empty list is an ordinary answer, not an error: a project that has never
/// been open long enough to autosave simply has none. Stateless, so a free
/// function — the recovery dialogue runs before anything is loaded.
List<BridgeAutosave> listAutosaves({required String project}) =>
    BridgeLib.instance.api.crateApiShellListAutosaves(project: project);

/// Show a finished file in the desktop's own file manager.
///
/// The export dialogue's *Open folder* is the only caller that asks directly;
/// a queued export with that tick set reveals itself as it lands. Returns
/// whether the request was handed over — a machine with no file manager (a
/// headless CI box, most obviously) says no rather than failing, because
/// nothing depends on the window appearing.
bool revealInFolder({required String path}) =>
    BridgeLib.instance.api.crateApiShellRevealInFolder(path: path);

/// One rotating autosave beside a project.
class BridgeAutosave {
  /// 1 is the newest.
  final int slot;
  final String path;

  const BridgeAutosave({
    required this.slot,
    required this.path,
  });

  @override
  int get hashCode => slot.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAutosave &&
          runtimeType == other.runtimeType &&
          slot == other.slot &&
          path == other.path;
}

/// How coarsely playback is currently rendering (K-030/K-171).
class BridgePlaybackTier {
  /// 1 = full, 2 = half, 3 = third, 4 = quarter.
  final int tier;

  /// The render scale that tier means, `1.0 / tier`.
  final double scale;

  const BridgePlaybackTier({
    required this.tier,
    required this.scale,
  });

  @override
  int get hashCode => tier.hashCode ^ scale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlaybackTier &&
          runtimeType == other.runtimeType &&
          tier == other.tier &&
          scale == other.scale;
}

/// What a journal replay recovered.
class BridgeRecovery {
  /// Ops found in the journal.
  final int found;

  /// Ops that still applied. Fewer than `found` means the journal ran past
  /// what the saved document can take — the replay stops at the first op that
  /// no longer applies rather than skipping it, because every op after one
  /// that failed was written against a document that no longer exists.
  final int replayed;

  const BridgeRecovery({
    required this.found,
    required this.replayed,
  });

  @override
  int get hashCode => found.hashCode ^ replayed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRecovery &&
          runtimeType == other.runtimeType &&
          found == other.found &&
          replayed == other.replayed;
}
