// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'composition.dart';
import 'folder.dart';
import 'footage.dart';
import 'layer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'project.dart';
import 'project_item.dart';
import 'solid.dart';
part 'state.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `handle_change_callback`, `journal_for`, `op_scope`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LumitBridgeState>>
abstract class LumitBridgeState implements RustOpaqueInterface {
  static ProjectReference? getCurrentProject() =>
      BridgeLib.instance.api.crateApiStateLumitBridgeStateGetCurrentProject();

  static ProjectReference newProject(
          {RustStreamSink<ScopedChange>? onChangeStream}) =>
      BridgeLib.instance.api.crateApiStateLumitBridgeStateNewProject(
          onChangeStream: onChangeStream);

  /// Deliberately **not** `#[frb(sync)]`, unlike its `new_project` sibling:
  /// reading a `.lum` parses a whole document and stats every media file it
  /// names, and on the UI isolate that froze the window for as long as it
  /// took. Async puts it on a worker thread, which is what lets Dart hold the
  /// previous document on screen behind a progress bar until this returns.
  static Future<ProjectReference?> openProject(
          {required String path,
          RustStreamSink<ScopedChange>? onChangeStream}) =>
      BridgeLib.instance.api.crateApiStateLumitBridgeStateOpenProject(
          path: path, onChangeStream: onChangeStream);
}

/// One effect's measured cost within its layer, in milliseconds.
class BridgeEffectTiming {
  /// The effect *instance* id, as a string — the row in the layer's stack.
  final String effect;
  final double ms;

  const BridgeEffectTiming({
    required this.effect,
    required this.ms,
  });

  @override
  int get hashCode => effect.hashCode ^ ms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEffectTiming &&
          runtimeType == other.runtimeType &&
          effect == other.effect &&
          ms == other.ms;
}

/// What one measured frame cost, per layer and per effect — the Timeline's
/// render-time column and the Effect controls panel's readouts (docs/13 §7.1).
///
/// Published only while the frontend has asked to be measuring
/// (`set_render_profiling`), because measuring is not free: it fences the
/// graphics card at each node so a millisecond means the work rather than the
/// paperwork.
class BridgeFrameProfile {
  final BigInt frame;

  /// The whole frame, wall-clock, including the stages no layer owns.
  final double totalMs;

  /// The composition's top-level layers, bottom-most first.
  final List<BridgeLayerTiming> layers;

  const BridgeFrameProfile({
    required this.frame,
    required this.totalMs,
    required this.layers,
  });

  @override
  int get hashCode => frame.hashCode ^ totalMs.hashCode ^ layers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFrameProfile &&
          runtimeType == other.runtimeType &&
          frame == other.frame &&
          totalMs == other.totalMs &&
          layers == other.layers;
}

/// One layer's measured cost for the frame just made.
class BridgeLayerTiming {
  final String layer;

  /// The layer's own picture: its source (a Precomp's whole comp included)
  /// and its effect stack. The final composite is one pass over the whole
  /// stack rather than a per-layer act, so it lands in `total_ms` and on no
  /// row — see `lumit_render::profile`.
  final double ms;
  final List<BridgeEffectTiming> effects;

  const BridgeLayerTiming({
    required this.layer,
    required this.ms,
    required this.effects,
  });

  @override
  int get hashCode => layer.hashCode ^ ms.hashCode ^ effects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLayerTiming &&
          runtimeType == other.runtimeType &&
          layer == other.layer &&
          ms == other.ms &&
          effects == other.effects;
}

/// How far the frame the user is waiting for has got (docs/13 §7.1).
///
/// Sent only for a frame somebody is *waiting on* — a scrub, a value drag, a
/// playhead move — and never during playback, where a frame due in 16 ms has
/// neither the need for a bar nor the time to describe itself. A frame served
/// from the cache reports nothing at all, because there was nothing to wait
/// for: it simply arrives.
class BridgeRenderProgress {
  /// Which frame this is about, so a report that arrives after the playhead
  /// has moved on can be recognised as stale rather than drawn.
  final BigInt frame;

  /// The stage's wire code — 0 planning, 1 decoding, 2 building, 3
  /// compositing, 4 presenting ([`lumit_render::RenderStage::code`]).
  final int stage;

  /// How much of the whole frame is done, 0..=1. An estimate built from
  /// fixed stage weights, which is what a progress bar needs and all it can
  /// honestly claim.
  final double fraction;

  /// True on the last report of a frame — the render is finished (or was
  /// abandoned) and the bar should go. Sent by the worker rather than the
  /// engine, so a frame that failed still ends its own bar.
  final bool done;

  const BridgeRenderProgress({
    required this.frame,
    required this.stage,
    required this.fraction,
    required this.done,
  });

  @override
  int get hashCode =>
      frame.hashCode ^ stage.hashCode ^ fraction.hashCode ^ done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRenderProgress &&
          runtimeType == other.runtimeType &&
          frame == other.frame &&
          stage == other.stage &&
          fraction == other.fraction &&
          done == other.done;
}

/// A small still picture as plain pixels — the thumbnail payload
/// (`FootageReference::thumbnail`). **Not a Viewer transport**: the read-back
/// frame path was deleted in K-183, so the only pixel payloads that cross the
/// bridge are these thumbnails and the scope traces, both small by
/// construction.
class BridgeRenderedFrame {
  /// Which frame of the source this is (0 for a thumbnail's poster frame).
  final BigInt frame;
  final int width;
  final int height;

  /// Tightly packed, straight (non-premultiplied) RGBA8: `width * height * 4`.
  final Uint8List rgba;

  const BridgeRenderedFrame({
    required this.frame,
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode =>
      frame.hashCode ^ width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRenderedFrame &&
          runtimeType == other.runtimeType &&
          frame == other.frame &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

/// The pixels under the dropper: a square window of the picture, centred on the
/// point the pointer was over when it was asked for (docs/07 §6.1).
///
/// **A window rather than the nine pixels the magnifier shows**, so the pointer
/// can move without asking again: the frontend cuts the magnifier's grid out of
/// what it already has, and re-reads only when the pointer approaches the edge
/// of it. That turns a sweep across the picture from a request per mouse move
/// into a handful.
///
/// Small by construction — 129×129 is 66 KiB, against a 1080p frame's 8 MiB —
/// so it crosses the boundary as plain pixels without breaking the K-183 rule
/// that *frames* only ever cross as GPU handles. It is the answer to a question
/// about a few pixels, not a picture to display.
class BridgeSampledPixels {
  /// The window's side length in pixels: `window × window`, always odd, so
  /// there is a single centre pixel.
  final int window;

  /// Tightly packed display-ready sRGB RGBA8, `window * window * 4`,
  /// row-major from the top-left of the window. Edge pixels repeat where the
  /// window runs off the picture, so it is always exactly this size and can
  /// be indexed without a border case.
  final Uint8List rgba;

  /// The raster the window was taken from, and where in it the centre pixel
  /// sits — which is what says where in the picture the window lies.
  ///
  /// **This raster, not the composition's.** The picture read may be a
  /// reduced-resolution preview, so these are the only coordinates in which
  /// the window can be indexed; a caller holding composition pixels must map
  /// through `width`/`height` rather than assume they line up.
  final int width;
  final int height;
  final int x;
  final int y;

  /// Which frame this is of, so a window that arrives after the playhead has
  /// moved on can be recognised as stale rather than drawn.
  final BigInt frame;

  /// True when the window is of one layer rendered alone rather than of the
  /// composite — a depth pass being read for a focal point, say.
  final bool layerAlone;

  const BridgeSampledPixels({
    required this.window,
    required this.rgba,
    required this.width,
    required this.height,
    required this.x,
    required this.y,
    required this.frame,
    required this.layerAlone,
  });

  @override
  int get hashCode =>
      window.hashCode ^
      rgba.hashCode ^
      width.hashCode ^
      height.hashCode ^
      x.hashCode ^
      y.hashCode ^
      frame.hashCode ^
      layerAlone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSampledPixels &&
          runtimeType == other.runtimeType &&
          window == other.window &&
          rgba == other.rgba &&
          width == other.width &&
          height == other.height &&
          x == other.x &&
          y == other.y &&
          frame == other.frame &&
          layerAlone == other.layerAlone;
}

/// One scope trace: a fixed 256x256 RGBA picture the Scopes panel draws.
///
/// The one place pixels still cross the boundary, and small enough not to
/// matter — 256 KiB against a 1080p frame's 8 MiB. Viewer frames themselves
/// only ever cross as GPU handles (K-183): flutter_rust_bridge's SSE codec
/// serialises a `Vec<u8>` one byte at a time, measured at 8.8 ms for a 1080p
/// frame, which is why the read-back frame transport was deleted.
class BridgeScopeTrace {
  final Uint8List rgba;

  const BridgeScopeTrace({
    required this.rgba,
  });

  @override
  int get hashCode => rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeScopeTrace &&
          runtimeType == other.runtimeType &&
          rgba == other.rgba;
}

/// The Windows zero-copy Viewer frame (K-177): an NT handle to a shared D3D12
/// texture the Flutter runner imports directly, so no pixels cross the FFI
/// boundary. The handle is stable for the session and changes only when the
/// comp's dimensions do. The format is always RGBA8, so it is not carried.
class BridgeSharedFrameInfo {
  /// The NT `HANDLE` value. `u64` because a Windows handle is 64-bit; it
  /// reaches Dart as a `BigInt`.
  final BigInt handle;

  /// Which frame of the composition this is. The frontend does not track this
  /// itself: a picture that says which frame it is needs no bookkeeping to
  /// place — the frontend paints it and moves the playhead there.
  final BigInt frame;
  final int width;
  final int height;

  /// The preview tier this frame was made at: 1 Full, 2 Half, 3 Third,
  /// 4 Quarter.
  ///
  /// Carried on the frame in place of being asked for. Two Viewer widgets
  /// showed the tier, and each one asked the engine for it in its `build()` —
  /// two calls across the boundary for each frame of playback, for a number
  /// that only changes when a frame is made. The frame that changes it now
  /// brings it.
  final int tier;

  const BridgeSharedFrameInfo({
    required this.handle,
    required this.frame,
    required this.width,
    required this.height,
    required this.tier,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      frame.hashCode ^
      width.hashCode ^
      height.hashCode ^
      tier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSharedFrameInfo &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          frame == other.frame &&
          width == other.width &&
          height == other.height &&
          tier == other.tier;
}

class BridgeSharedFrameInfoLinux {
  final int fd;

  /// Which frame of the composition this is. The frontend does not track this
  /// itself: a picture that says which frame it is needs no bookkeeping to
  /// place — the frontend paints it and moves the playhead there.
  final BigInt frame;
  final int width;
  final int height;
  final int stride;
  final int offset;

  /// The DRM fourcc (`DRM_FORMAT_ABGR8888`, memory order R,G,B,A).
  final int drmFourcc;

  /// The DRM modifier (`DRM_FORMAT_MOD_LINEAR` = 0 on the linear-tiling path).
  final BigInt modifier;

  /// The preview tier this frame was made at: 1 Full, 2 Half, 3 Third,
  /// 4 Quarter.
  ///
  /// Carried on the frame in place of being asked for. Two Viewer widgets
  /// showed the tier, and each one asked the engine for it in its `build()` —
  /// two calls across the boundary for each frame of playback, for a number
  /// that only changes when a frame is made. The frame that changes it now
  /// brings it.
  final int tier;

  const BridgeSharedFrameInfoLinux({
    required this.fd,
    required this.frame,
    required this.width,
    required this.height,
    required this.stride,
    required this.offset,
    required this.drmFourcc,
    required this.modifier,
    required this.tier,
  });

  @override
  int get hashCode =>
      fd.hashCode ^
      frame.hashCode ^
      width.hashCode ^
      height.hashCode ^
      stride.hashCode ^
      offset.hashCode ^
      drmFourcc.hashCode ^
      modifier.hashCode ^
      tier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSharedFrameInfoLinux &&
          runtimeType == other.runtimeType &&
          fd == other.fd &&
          frame == other.frame &&
          width == other.width &&
          height == other.height &&
          stride == other.stride &&
          offset == other.offset &&
          drmFourcc == other.drmFourcc &&
          modifier == other.modifier &&
          tier == other.tier;
}

class ScopedChange {
  final ProjectReference project;
  final ItemReference? item;
  final LayerReference? layer;

  /// The project item list changed: an item was added, removed, renamed,
  /// refiled or relinked. The Project panel rebuilds on this and ignores
  /// everything else, so tweaking a layer value no longer re-probes every
  /// footage file on disk.
  final bool items;

  const ScopedChange({
    required this.project,
    this.item,
    this.layer,
    required this.items,
  });

  @override
  int get hashCode =>
      project.hashCode ^ item.hashCode ^ layer.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScopedChange &&
          runtimeType == other.runtimeType &&
          project == other.project &&
          item == other.item &&
          layer == other.layer &&
          items == other.items;
}

@freezed
sealed class WorkerResponse with _$WorkerResponse {
  const WorkerResponse._();

  /// Linux, `shared-texture-linux`.
  const factory WorkerResponse.renderedDmaBuf(
    BridgeSharedFrameInfoLinux field0,
  ) = WorkerResponse_RenderedDMABuf;

  /// Windows, `shared-texture`.
  const factory WorkerResponse.renderedSharedTexture(
    BridgeSharedFrameInfo field0,
  ) = WorkerResponse_RenderedSharedTexture;

  /// A scope trace, which rides the same stream as the frames so the panel
  /// needs no second channel.
  const factory WorkerResponse.scope(
    BridgeScopeTrace field0,
  ) = WorkerResponse_Scope;

  /// The pixels under the dropper — the answer to one
  /// `CompositionReference::sample_pixels`, riding the same stream for the
  /// same reason a trace does.
  const factory WorkerResponse.sampled(
    BridgeSampledPixels field0,
  ) = WorkerResponse_Sampled;

  /// Playback finished on its own — it ran off the end of the composition.
  ///
  /// Sent so the transport can show itself stopped without the frontend having
  /// to work out where the end was. Stopping *because the user asked* needs no
  /// message: the frontend already knows, having asked.
  const factory WorkerResponse.playbackEnded() = WorkerResponse_PlaybackEnded;

  /// The idle fill banked another frame (docs/06 §5.5), so the Timeline's
  /// cache bar has something new to draw. Carries nothing: the bar re-asks
  /// `cached_frames` itself. Without this the fill worked invisibly — the
  /// bar only redrew when a frame arrived, and a fill shows no frame.
  const factory WorkerResponse.cacheFilled() = WorkerResponse_CacheFilled;

  /// How far the frame being waited for has got — the Viewer's preview
  /// progress bar (docs/07 §2.5).
  const factory WorkerResponse.renderProgress(
    BridgeRenderProgress field0,
  ) = WorkerResponse_RenderProgress;

  /// What the frame just made cost, layer by layer and effect by effect —
  /// the render-time indicators (docs/13 §7.1).
  const factory WorkerResponse.frameProfile(
    BridgeFrameProfile field0,
  ) = WorkerResponse_FrameProfile;
}
