// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'layer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `create_transform_keys`, `failure_of`, `idle`, `idle`, `media_source`, `tracked_media`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// How `layer`'s analysis is getting on.
///
/// Polled, never subscribed to: the reading is a value in a map that whoever
/// repaints samples, exactly as the cache bar is sampled
/// (docs/impl/tracking.md §5b). A layer that is not tracked footage reads
/// [`BridgeTrackStage::Idle`], which is what it is.
BridgeTrackStatus trackStatus({required LayerReference layer}) =>
    BridgeLib.instance.api.crateApiTrackTrackStatus(layer: layer);

/// `layer`'s solved point cloud as it lands on composition frame `frame`.
///
/// **Once per frame change, never per rebuild** — the rule the Levels histogram
/// follows (K-413) and the bridge-call budget pins. The frame the cloud is drawn
/// from is found by the one walk the camera link uses
/// ([`lumit_core::track::tracked_solved_frame`]), so the dots and the camera
/// they were solved with can never disagree about which moment this is.
///
/// **The reference frame** is §5b's second deviation, unchanged: the solve
/// describes a media item, not a composition, so its pixels are read at the
/// footage's own raster centred on the comp. Exact for the ordinary case — a
/// comp made from the shot — and off by the size ratio otherwise.
List<BridgeTrackPoint> trackedPoints(
        {required LayerReference layer, required PlatformInt64 frame}) =>
    BridgeLib.instance.api
        .crateApiTrackTrackedPoints(layer: layer, frame: frame);

/// `camera`'s solve link and how it is reading at composition frame `frame` —
/// the badge, in one crossing.
BridgeCameraLink cameraLink(
        {required LayerReference camera, required PlatformInt64 frame}) =>
    BridgeLib.instance.api
        .crateApiTrackCameraLink(camera: camera, frame: frame);

/// Press one of an effect's Action parameters (K-417).
///
/// An Action carries no value, so this is an **event** and not a write: nothing
/// is staged, nothing is committed, and no undo entry appears. Today the Camera
/// track's Analyse and Cancel are the only two; an unknown effect or parameter
/// is refused rather than ignored, because a button that silently does nothing
/// is the hardest kind of fault to see.
void fireEffectAction(
        {required LayerReference layer,
        required UuidValue effect,
        required String param}) =>
    BridgeLib.instance.api.crateApiTrackFireEffectAction(
        layer: layer, effect: effect, param: param);

/// Add a Camera layer whose motion is derived from `tracked`'s solve (K-417).
///
/// The link is the whole point: nothing is copied, so re-analysing the shot
/// moves this camera with it, and every clip of the same footage reads the same
/// solve through its own time mapping. Its transform rows are the **correction
/// lane** (K-578) — dragging one nudges the solved motion rather than replacing
/// it — and they start at the pose captured here, which is that lane's nought.
LayerReference addSolvedCamera({required LayerReference tracked}) =>
    BridgeLib.instance.api.crateApiTrackAddSolvedCamera(tracked: tracked);

/// Bake a solve-linked camera into keyframes and sever the link (K-417).
///
/// One key per composition frame, at the composition's rate, exactly the motion
/// that was being derived — and from then on an ordinary camera the user edits.
/// The bake is honest about being many keyframes: they are real, editable, and
/// the graph editor shows them like any others.
///
/// One undo step, and undo restores the link last, which is what lets the
/// read-only guard stay unconditional in both directions.
void convertCameraToKeyframes({required LayerReference camera}) =>
    BridgeLib.instance.api
        .crateApiTrackConvertCameraToKeyframes(camera: camera);

/// **Clear corrections** (K-578): put a linked camera's own properties back to
/// the pose the link was made at, leaving the link itself alone.
///
/// One undo step. Refused when there is no link, or nothing in the lane — a
/// command that committed an empty batch would put a step on the undo stack
/// that changed nothing.
void clearCameraCorrections({required LayerReference camera}) =>
    BridgeLib.instance.api.crateApiTrackClearCameraCorrections(camera: camera);

/// Point `camera` at a tracked layer, or clear the link (K-417).
///
/// The link is a property of the Camera layer, so this is an ordinary
/// undoable edit — and `None` is how a camera stops being derived without
/// baking anything.
void setCameraSolveLink({required LayerReference camera, UuidValue? tracked}) =>
    BridgeLib.instance.api
        .crateApiTrackSetCameraSolveLink(camera: camera, tracked: tracked);

/// Put a Null (or a Solid) at the mean solved position of `tracks` — K-417's
/// creation gesture, After Effects' own.
///
/// The layer is 3D and sits where the points are, **oriented to face the
/// camera**: a layer carrying the camera's own rotation is parallel to its image
/// plane, which is what facing it means. `frame` is the composition frame the
/// selection was made on, which is the moment whose camera the layer is turned
/// to.
///
/// Refused when none of the ids names a solved point — there is no position to
/// put anything at, and a layer at the origin would be a silent lie.
LayerReference addLayerAtPoints(
        {required LayerReference tracked,
        required List<int> tracks,
        required PlatformInt64 frame,
        required bool solid}) =>
    BridgeLib.instance.api.crateApiTrackAddLayerAtPoints(
        tracked: tracked, tracks: tracks, frame: frame, solid: solid);

/// How the Planar track instance `effect` on `layer` is getting on.
///
/// Polled while it is moving and never otherwise, exactly as
/// [`track_status`] is — the reading is a value in a map, not a subscription.
/// The answer is filed under the **effect instance**, because what was tracked
/// is the quad this instance holds (K-579).
BridgePlanarStatus planarStatus(
        {required LayerReference layer, required UuidValue effect}) =>
    BridgeLib.instance.api
        .crateApiTrackPlanarStatus(layer: layer, effect: effect);

/// **Create corner pin** (K-579): put a Corner pin on the layer the Planar
/// track's *Pin layer* row names, its four points keyframed to the tracked
/// surface.
///
/// One undoable edit, and one the user can throw away like any other: the pin is
/// an ordinary effect with ordinary keyframes on it from the moment it lands.
///
/// Refused when nothing has been tracked under this instance, or when no pin
/// layer has been chosen — a button that quietly did nothing would be the
/// hardest kind of fault to see.
void createCornerPin(
        {required LayerReference tracked, required UuidValue effect}) =>
    BridgeLib.instance.api
        .crateApiTrackCreateCornerPin(tracked: tracked, effect: effect);

/// A Camera layer's solve link, as the badge and the Convert command read it.
class BridgeCameraLink {
  final BridgeLinkState state;

  /// The tracked layer the link names, or `None` for an ordinary camera.
  final UuidValue? tracked;

  const BridgeCameraLink({
    required this.state,
    this.tracked,
  });

  @override
  int get hashCode => state.hashCode ^ tracked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCameraLink &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          tracked == other.tracked;
}

/// How a Camera layer's placement is being arrived at — the bridge form of
/// [`lumit_core::track::LinkState`], which is the badge.
enum BridgeLinkState {
  unlinked,
  derived,
  held,
  unresolved,
  ;
}

/// Everything the Planar track's status row draws, in one crossing.
///
/// Deliberately not [`BridgeTrackStatus`] with two fields ignored. A planar
/// track has no point cloud and no reprojection error, and a camera solve has
/// no re-anchor count; one struct carrying both would have four rows that mean
/// nothing in half the places it is read, and the panel would have to know
/// which half it was holding.
class BridgePlanarStatus {
  final BridgeTrackStage stage;

  /// Frames followed so far, and how many there are. Both zero outside
  /// [`BridgeTrackStage::Tracking`].
  final int done;
  final int total;

  /// Set only at [`BridgeTrackStage::Failed`].
  final BridgeTrackFailure? failure;

  /// How many frames of the clip carry the surface, and how many the clip
  /// has. `frames < clip_frames` is a **partial** track: the surface was lost
  /// part-way and what was followed is the part before it.
  final int frames;
  final int clipFrames;

  /// How many times the measurement was re-anchored (docs/impl/tracking.md
  /// §6). Zero is a track measured entirely against its reference frame, and
  /// so one carrying no accumulated drift at all — which is the one number
  /// about a planar track that says how much to trust its far end.
  final int reanchors;

  const BridgePlanarStatus({
    required this.stage,
    required this.done,
    required this.total,
    this.failure,
    required this.frames,
    required this.clipFrames,
    required this.reanchors,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      done.hashCode ^
      total.hashCode ^
      failure.hashCode ^
      frames.hashCode ^
      clipFrames.hashCode ^
      reanchors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlanarStatus &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          done == other.done &&
          total == other.total &&
          failure == other.failure &&
          frames == other.frames &&
          clipFrames == other.clipFrames &&
          reanchors == other.reanchors;
}

/// Why an analysis produced no camera path.
///
/// A **reason, not a sentence** (K-303): the engine's own `AnalysisError`
/// carries English, and English crossing here would ship untranslated inside a
/// translated window. Dart switches over this and picks the arb key, which is
/// the shape `lumit_import::Reason` already uses for the import report.
enum BridgeTrackFailure {
  /// The media could not be opened, or carries no video.
  unreadable,

  /// Opened, but with no frames to track.
  noFrames,

  /// The frames themselves could not be followed (a size change mid-clip).
  tracking,

  /// Too little in the picture held still enough to follow.
  noFeatures,

  /// The camera only turned: there is no position to solve and no depth to
  /// recover (docs/impl/tracking.md §4's sixth deviation).
  rotationOnly,

  /// The shot carries a camera move the solver could not stand behind.
  noSolve,

  /// The quad's contents are not one flat surface, or move against
  /// themselves (K-579).
  notPlanar,
  ;
}

/// One solved point, ready to draw: where it lands on the picture at the frame
/// asked for, and how near the camera it was.
class BridgeTrackPoint {
  /// The track this point came from — what a selection names, and what
  /// [`add_layer_at_points`] takes back.
  final int track;

  /// **Composition pixels**, origin top-left, the coordinates every other
  /// overlay in the Viewer works in.
  final double x;
  final double y;

  /// Nearness over the cloud on this frame, 0..1, 1 being the nearest —
  /// already normalised, because a depth cue is arithmetic over the whole
  /// cloud and the interface draws what it is given.
  final double depth;

  const BridgeTrackPoint({
    required this.track,
    required this.x,
    required this.y,
    required this.depth,
  });

  @override
  int get hashCode => track.hashCode ^ x.hashCode ^ y.hashCode ^ depth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTrackPoint &&
          runtimeType == other.runtimeType &&
          track == other.track &&
          x == other.x &&
          y == other.y &&
          depth == other.depth;
}

/// How far the analysis of a tracked layer has got — the bridge form of
/// [`lumit_render::track::Progress`], flattened so the panel reads fields
/// rather than unwrapping a shape.
enum BridgeTrackStage {
  /// Nothing has ever been asked for this media in this session.
  idle,

  /// Accepted, not started.
  queued,

  /// Decoding and following features.
  tracking,

  /// The frames are in; the geometry and the solve are running.
  solving,

  /// There is a solve in the store.
  done,

  /// Stopped. Nothing was written.
  cancelled,

  /// Refused — see [`BridgeTrackStatus::failure`].
  failed,
  ;
}

/// Everything the Camera track's status row draws, in one crossing.
class BridgeTrackStatus {
  final BridgeTrackStage stage;

  /// Frames tracked so far, and how many there are. Both zero outside
  /// [`BridgeTrackStage::Tracking`].
  final int done;
  final int total;

  /// Set only at [`BridgeTrackStage::Failed`].
  final BridgeTrackFailure? failure;

  /// The solve's mean reprojection error in source pixels, and how many
  /// points and frames it holds. Zero until there is a solve to describe.
  final double meanError;
  final int points;

  /// How many frames of the clip carry a solved camera. The span always
  /// starts at the clip's first frame — the analysis tracks the source from
  /// its beginning and can only stop early, never start late — so this and
  /// `clip_frames` are the whole of the bar the panel draws.
  final int frames;

  /// How many frames the clip has. `frames < clip_frames` is a **partial**
  /// track: the shot could not be followed all the way through, and what was
  /// solved is the part before it stopped carrying
  /// ([`lumit_render::track::Solved::is_partial`]).
  final int clipFrames;

  const BridgeTrackStatus({
    required this.stage,
    required this.done,
    required this.total,
    this.failure,
    required this.meanError,
    required this.points,
    required this.frames,
    required this.clipFrames,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      done.hashCode ^
      total.hashCode ^
      failure.hashCode ^
      meanError.hashCode ^
      points.hashCode ^
      frames.hashCode ^
      clipFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTrackStatus &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          done == other.done &&
          total == other.total &&
          failure == other.failure &&
          meanError == other.meanError &&
          points == other.points &&
          frames == other.frames &&
          clipFrames == other.clipFrames;
}
