// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// A footage item's measured size, from the frontend's own probe cache: the
/// engine's probe lives on the worker, and this call runs on the caller's
/// thread, so the sizes it already holds come along rather than being asked
/// for again.
class BridgeMediaSize {
  final UuidValue item;
  final int width;
  final int height;

  const BridgeMediaSize({
    required this.item,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => item.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeMediaSize &&
          runtimeType == other.runtimeType &&
          item == other.item &&
          width == other.width &&
          height == other.height;
}

/// A camera: its eye, the four corners of the comp-sized rectangle its zoom
/// in front of it, and the point of interest when it has one.
class BridgeWireCamera {
  final UuidValue layer;
  final BridgeWirePoint eye;
  final List<BridgeWirePoint> corners;
  final BridgeWirePoint? pointOfInterest;

  const BridgeWireCamera({
    required this.layer,
    required this.eye,
    required this.corners,
    this.pointOfInterest,
  });

  @override
  int get hashCode =>
      layer.hashCode ^
      eye.hashCode ^
      corners.hashCode ^
      pointOfInterest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWireCamera &&
          runtimeType == other.runtimeType &&
          layer == other.layer &&
          eye == other.eye &&
          corners == other.corners &&
          pointOfInterest == other.pointOfInterest;
}

/// A 3D layer's rectangle: four corners, clockwise from the top left.
class BridgeWireLayer {
  final UuidValue layer;
  final List<BridgeWirePoint> corners;

  const BridgeWireLayer({
    required this.layer,
    required this.corners,
  });

  @override
  int get hashCode => layer.hashCode ^ corners.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWireLayer &&
          runtimeType == other.runtimeType &&
          layer == other.layer &&
          corners == other.corners;
}

class BridgeWireLight {
  final UuidValue layer;
  final BridgeWirePoint at;

  const BridgeWireLight({
    required this.layer,
    required this.at,
  });

  @override
  int get hashCode => layer.hashCode ^ at.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWireLight &&
          runtimeType == other.runtimeType &&
          layer == other.layer &&
          at == other.at;
}

/// A comp-space point taken through the view: where it lands in comp pixels,
/// and whether it sits in front of the view's eye. A point behind it still
/// carries a number, but not one worth drawing.
class BridgeWirePoint {
  final double x;
  final double y;
  final bool inFront;

  const BridgeWirePoint({
    required this.x,
    required this.y,
    required this.inFront,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ inFront.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWirePoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          inFront == other.inFront;
}

class BridgeWireframes {
  final List<BridgeWireLayer> layers;
  final List<BridgeWireCamera> cameras;
  final List<BridgeWireLight> lights;

  const BridgeWireframes({
    required this.layers,
    required this.cameras,
    required this.lights,
  });

  @override
  int get hashCode => layers.hashCode ^ cameras.hashCode ^ lights.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWireframes &&
          runtimeType == other.runtimeType &&
          layers == other.layers &&
          cameras == other.cameras &&
          lights == other.lights;
}
