// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/assets.dart';
import 'api/audio.dart';
import 'api/cache.dart';
import 'api/composition.dart';
import 'api/effect.dart';
import 'api/export.dart';
import 'api/expressions.dart';
import 'api/folder.dart';
import 'api/footage.dart';
import 'api/graph.dart';
import 'api/import.dart';
import 'api/keymap.dart';
import 'api/layer.dart';
import 'api/project.dart';
import 'api/project_item.dart';
import 'api/retime.dart';
import 'api/shell.dart';
import 'api/solid.dart';
import 'api/state.dart';
import 'api/system.dart';
import 'api/track.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:uuid/uuid.dart';

abstract class BridgeLibApiImplPlatform extends BaseApiImpl<BridgeLibWire> {
  BridgeLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_BridgeEffectInstancePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstancePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_BridgeErrorPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeErrorPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ExpressionsPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressionsPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_LumitBridgeStatePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeStatePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BridgeEffectInstance
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw);

  @protected
  BridgeError
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          dynamic raw);

  @protected
  Expressions
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions(
          dynamic raw);

  @protected
  LumitBridgeState
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          dynamic raw);

  @protected
  BridgeEffectInstance
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw);

  @protected
  BridgeEffectInstance
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw);

  @protected
  BridgeEffectInstance
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw);

  @protected
  BridgeError
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          dynamic raw);

  @protected
  Expressions
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions(
          dynamic raw);

  @protected
  LumitBridgeState
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          dynamic raw);

  @protected
  RustStreamSink<ScopedChange> dco_decode_StreamSink_scoped_change_Sse(
      dynamic raw);

  @protected
  RustStreamSink<WorkerResponse> dco_decode_StreamSink_worker_response_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeBezierSide dco_decode_box_autoadd_bridge_bezier_side(dynamic raw);

  @protected
  BridgeColour dco_decode_box_autoadd_bridge_colour(dynamic raw);

  @protected
  BridgeColourRgba dco_decode_box_autoadd_bridge_colour_rgba(dynamic raw);

  @protected
  BridgeCompSettings dco_decode_box_autoadd_bridge_comp_settings(dynamic raw);

  @protected
  BridgeEffectValue dco_decode_box_autoadd_bridge_effect_value(dynamic raw);

  @protected
  BridgeExportSpec dco_decode_box_autoadd_bridge_export_spec(dynamic raw);

  @protected
  BridgeFileParam dco_decode_box_autoadd_bridge_file_param(dynamic raw);

  @protected
  BridgeFlowParams dco_decode_box_autoadd_bridge_flow_params(dynamic raw);

  @protected
  BridgeFrameProfile dco_decode_box_autoadd_bridge_frame_profile(dynamic raw);

  @protected
  BridgeGraphWiring dco_decode_box_autoadd_bridge_graph_wiring(dynamic raw);

  @protected
  BridgeImportedProject dco_decode_box_autoadd_bridge_imported_project(
      dynamic raw);

  @protected
  BridgeMask dco_decode_box_autoadd_bridge_mask(dynamic raw);

  @protected
  BridgeMatte dco_decode_box_autoadd_bridge_matte(dynamic raw);

  @protected
  BridgeMediaInfo dco_decode_box_autoadd_bridge_media_info(dynamic raw);

  @protected
  BridgeNodeRef dco_decode_box_autoadd_bridge_node_ref(dynamic raw);

  @protected
  BridgePoint dco_decode_box_autoadd_bridge_point(dynamic raw);

  @protected
  BridgeProjectCacheLocation
      dco_decode_box_autoadd_bridge_project_cache_location(dynamic raw);

  @protected
  BridgeRational dco_decode_box_autoadd_bridge_rational(dynamic raw);

  @protected
  BridgeRenderProgress dco_decode_box_autoadd_bridge_render_progress(
      dynamic raw);

  @protected
  BridgeRenderedFrame dco_decode_box_autoadd_bridge_rendered_frame(dynamic raw);

  @protected
  BridgeSampledPixels dco_decode_box_autoadd_bridge_sampled_pixels(dynamic raw);

  @protected
  BridgeScalar dco_decode_box_autoadd_bridge_scalar(dynamic raw);

  @protected
  BridgeScopeTrace dco_decode_box_autoadd_bridge_scope_trace(dynamic raw);

  @protected
  BridgeShapeItem dco_decode_box_autoadd_bridge_shape_item(dynamic raw);

  @protected
  BridgeSharedFrameInfo dco_decode_box_autoadd_bridge_shared_frame_info(
      dynamic raw);

  @protected
  BridgeSharedFrameInfoLinux
      dco_decode_box_autoadd_bridge_shared_frame_info_linux(dynamic raw);

  @protected
  BridgeSolidDef dco_decode_box_autoadd_bridge_solid_def(dynamic raw);

  @protected
  BridgeSpan dco_decode_box_autoadd_bridge_span(dynamic raw);

  @protected
  BridgeStroke dco_decode_box_autoadd_bridge_stroke(dynamic raw);

  @protected
  BridgeTextDocument dco_decode_box_autoadd_bridge_text_document(dynamic raw);

  @protected
  BridgeTrackFailure dco_decode_box_autoadd_bridge_track_failure(dynamic raw);

  @protected
  BridgeTransform dco_decode_box_autoadd_bridge_transform(dynamic raw);

  @protected
  CompositionReference dco_decode_box_autoadd_composition_reference(
      dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FolderReference dco_decode_box_autoadd_folder_reference(dynamic raw);

  @protected
  FootageReference dco_decode_box_autoadd_footage_reference(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ItemReference dco_decode_box_autoadd_item_reference(dynamic raw);

  @protected
  LayerReference dco_decode_box_autoadd_layer_reference(dynamic raw);

  @protected
  ProjectReference dco_decode_box_autoadd_project_reference(dynamic raw);

  @protected
  SolidReference dco_decode_box_autoadd_solid_reference(dynamic raw);

  @protected
  BridgeAnimatedMaskPath dco_decode_bridge_animated_mask_path(dynamic raw);

  @protected
  BridgeAudioClock dco_decode_bridge_audio_clock(dynamic raw);

  @protected
  BridgeAudioPeaks dco_decode_bridge_audio_peaks(dynamic raw);

  @protected
  BridgeAutosave dco_decode_bridge_autosave(dynamic raw);

  @protected
  BridgeBezierSide dco_decode_bridge_bezier_side(dynamic raw);

  @protected
  BridgeCacheLocation dco_decode_bridge_cache_location(dynamic raw);

  @protected
  BridgeCacheStats dco_decode_bridge_cache_stats(dynamic raw);

  @protected
  BridgeCameraLink dco_decode_bridge_camera_link(dynamic raw);

  @protected
  BridgeClip dco_decode_bridge_clip(dynamic raw);

  @protected
  BridgeColour dco_decode_bridge_colour(dynamic raw);

  @protected
  BridgeColourRgba dco_decode_bridge_colour_rgba(dynamic raw);

  @protected
  BridgeCompModel dco_decode_bridge_comp_model(dynamic raw);

  @protected
  BridgeCompSettings dco_decode_bridge_comp_settings(dynamic raw);

  @protected
  BridgeCompSize dco_decode_bridge_comp_size(dynamic raw);

  @protected
  BridgeCrop dco_decode_bridge_crop(dynamic raw);

  @protected
  BridgeDiskCacheStats dco_decode_bridge_disk_cache_stats(dynamic raw);

  @protected
  BridgeEffectInfo dco_decode_bridge_effect_info(dynamic raw);

  @protected
  BridgeEffectInstanceInfo dco_decode_bridge_effect_instance_info(dynamic raw);

  @protected
  BridgeEffectTiming dco_decode_bridge_effect_timing(dynamic raw);

  @protected
  BridgeEffectValue dco_decode_bridge_effect_value(dynamic raw);

  @protected
  BridgeEnabledCond dco_decode_bridge_enabled_cond(dynamic raw);

  @protected
  BridgeEnabledWhen dco_decode_bridge_enabled_when(dynamic raw);

  @protected
  BridgeExportPreset dco_decode_bridge_export_preset(dynamic raw);

  @protected
  BridgeExportPresetEntry dco_decode_bridge_export_preset_entry(dynamic raw);

  @protected
  BridgeExportQueueItem dco_decode_bridge_export_queue_item(dynamic raw);

  @protected
  BridgeExportQueueState dco_decode_bridge_export_queue_state(dynamic raw);

  @protected
  BridgeExportSpec dco_decode_bridge_export_spec(dynamic raw);

  @protected
  BridgeExportState dco_decode_bridge_export_state(dynamic raw);

  @protected
  BridgeFileParam dco_decode_bridge_file_param(dynamic raw);

  @protected
  BridgeFlowParams dco_decode_bridge_flow_params(dynamic raw);

  @protected
  BridgeFormatCaps dco_decode_bridge_format_caps(dynamic raw);

  @protected
  BridgeFrameProfile dco_decode_bridge_frame_profile(dynamic raw);

  @protected
  BridgeGraphEdge dco_decode_bridge_graph_edge(dynamic raw);

  @protected
  BridgeGraphNode dco_decode_bridge_graph_node(dynamic raw);

  @protected
  BridgeGraphWiring dco_decode_bridge_graph_wiring(dynamic raw);

  @protected
  BridgeHistory dco_decode_bridge_history(dynamic raw);

  @protected
  BridgeImportArg dco_decode_bridge_import_arg(dynamic raw);

  @protected
  BridgeImportOutcome dco_decode_bridge_import_outcome(dynamic raw);

  @protected
  BridgeImportReport dco_decode_bridge_import_report(dynamic raw);

  @protected
  BridgeImportRow dco_decode_bridge_import_row(dynamic raw);

  @protected
  BridgeImportedProject dco_decode_bridge_imported_project(dynamic raw);

  @protected
  BridgeInputRef dco_decode_bridge_input_ref(dynamic raw);

  @protected
  BridgeKeyBinding dco_decode_bridge_key_binding(dynamic raw);

  @protected
  BridgeKeyConflict dco_decode_bridge_key_conflict(dynamic raw);

  @protected
  BridgeKeyContext dco_decode_bridge_key_context(dynamic raw);

  @protected
  BridgeKeyShadow dco_decode_bridge_key_shadow(dynamic raw);

  @protected
  BridgeKeyframe dco_decode_bridge_keyframe(dynamic raw);

  @protected
  BridgeKeymapGroup dco_decode_bridge_keymap_group(dynamic raw);

  @protected
  BridgeKeymapPreset dco_decode_bridge_keymap_preset(dynamic raw);

  @protected
  BridgeLayerEntry dco_decode_bridge_layer_entry(dynamic raw);

  @protected
  BridgeLayerGraph dco_decode_bridge_layer_graph(dynamic raw);

  @protected
  BridgeLayerInfo dco_decode_bridge_layer_info(dynamic raw);

  @protected
  BridgeLayerKind dco_decode_bridge_layer_kind(dynamic raw);

  @protected
  BridgeLayerMarker dco_decode_bridge_layer_marker(dynamic raw);

  @protected
  BridgeLayerSwitch dco_decode_bridge_layer_switch(dynamic raw);

  @protected
  BridgeLayerSwitches dco_decode_bridge_layer_switches(dynamic raw);

  @protected
  BridgeLayerTiming dco_decode_bridge_layer_timing(dynamic raw);

  @protected
  BridgeLinkState dco_decode_bridge_link_state(dynamic raw);

  @protected
  BridgeMarker dco_decode_bridge_marker(dynamic raw);

  @protected
  BridgeMask dco_decode_bridge_mask(dynamic raw);

  @protected
  BridgeMaskMode dco_decode_bridge_mask_mode(dynamic raw);

  @protected
  BridgeMatte dco_decode_bridge_matte(dynamic raw);

  @protected
  BridgeMediaInfo dco_decode_bridge_media_info(dynamic raw);

  @protected
  BridgeMemoryReport dco_decode_bridge_memory_report(dynamic raw);

  @protected
  BridgeMetadataField dco_decode_bridge_metadata_field(dynamic raw);

  @protected
  BridgeNodePosition dco_decode_bridge_node_position(dynamic raw);

  @protected
  BridgeNodeRef dco_decode_bridge_node_ref(dynamic raw);

  @protected
  BridgeOutputRef dco_decode_bridge_output_ref(dynamic raw);

  @protected
  BridgePaintMode dco_decode_bridge_paint_mode(dynamic raw);

  @protected
  BridgeParamGroup dco_decode_bridge_param_group(dynamic raw);

  @protected
  BridgeParamInfo dco_decode_bridge_param_info(dynamic raw);

  @protected
  BridgeParamKind dco_decode_bridge_param_kind(dynamic raw);

  @protected
  BridgeParamPair dco_decode_bridge_param_pair(dynamic raw);

  @protected
  BridgeParamValue dco_decode_bridge_param_value(dynamic raw);

  @protected
  BridgePlaybackMode dco_decode_bridge_playback_mode(dynamic raw);

  @protected
  BridgePlaybackTier dco_decode_bridge_playback_tier(dynamic raw);

  @protected
  BridgePoint dco_decode_bridge_point(dynamic raw);

  @protected
  BridgePort dco_decode_bridge_port(dynamic raw);

  @protected
  BridgePortType dco_decode_bridge_port_type(dynamic raw);

  @protected
  BridgePresetInfo dco_decode_bridge_preset_info(dynamic raw);

  @protected
  BridgeProjectCacheLocation dco_decode_bridge_project_cache_location(
      dynamic raw);

  @protected
  BridgeRational dco_decode_bridge_rational(dynamic raw);

  @protected
  BridgeRecovery dco_decode_bridge_recovery(dynamic raw);

  @protected
  BridgeRenderProgress dco_decode_bridge_render_progress(dynamic raw);

  @protected
  BridgeRenderedFrame dco_decode_bridge_rendered_frame(dynamic raw);

  @protected
  BridgeRetimeInterp dco_decode_bridge_retime_interp(dynamic raw);

  @protected
  BridgeRevealGroups dco_decode_bridge_reveal_groups(dynamic raw);

  @protected
  BridgeRevealKind dco_decode_bridge_reveal_kind(dynamic raw);

  @protected
  BridgeSampledPixels dco_decode_bridge_sampled_pixels(dynamic raw);

  @protected
  BridgeScalar dco_decode_bridge_scalar(dynamic raw);

  @protected
  BridgeScopeTrace dco_decode_bridge_scope_trace(dynamic raw);

  @protected
  BridgeShapeItem dco_decode_bridge_shape_item(dynamic raw);

  @protected
  BridgeSharedFrameInfo dco_decode_bridge_shared_frame_info(dynamic raw);

  @protected
  BridgeSharedFrameInfoLinux dco_decode_bridge_shared_frame_info_linux(
      dynamic raw);

  @protected
  BridgeSideInterp dco_decode_bridge_side_interp(dynamic raw);

  @protected
  BridgeSolidDef dco_decode_bridge_solid_def(dynamic raw);

  @protected
  BridgeSpan dco_decode_bridge_span(dynamic raw);

  @protected
  BridgeStroke dco_decode_bridge_stroke(dynamic raw);

  @protected
  BridgeStrokePoint dco_decode_bridge_stroke_point(dynamic raw);

  @protected
  BridgeTextDocument dco_decode_bridge_text_document(dynamic raw);

  @protected
  BridgeTrackFailure dco_decode_bridge_track_failure(dynamic raw);

  @protected
  BridgeTrackPoint dco_decode_bridge_track_point(dynamic raw);

  @protected
  BridgeTrackStage dco_decode_bridge_track_stage(dynamic raw);

  @protected
  BridgeTrackStatus dco_decode_bridge_track_status(dynamic raw);

  @protected
  BridgeTransform dco_decode_bridge_transform(dynamic raw);

  @protected
  BridgeTransformProp dco_decode_bridge_transform_prop(dynamic raw);

  @protected
  BridgeUnit dco_decode_bridge_unit(dynamic raw);

  @protected
  BridgeVertex dco_decode_bridge_vertex(dynamic raw);

  @protected
  BridgeViewerTransport dco_decode_bridge_viewer_transport(dynamic raw);

  @protected
  BridgeVramCacheStats dco_decode_bridge_vram_cache_stats(dynamic raw);

  @protected
  CompositionReference dco_decode_composition_reference(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  F32Array4 dco_decode_f_32_array_4(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FolderReference dco_decode_folder_reference(dynamic raw);

  @protected
  FootageReference dco_decode_footage_reference(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ItemReference dco_decode_item_reference(dynamic raw);

  @protected
  LayerReference dco_decode_layer_reference(dynamic raw);

  @protected
  List<BridgeEffectInstance>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<UuidValue> dco_decode_list_Uuid(dynamic raw);

  @protected
  List<BridgeAnimatedMaskPath> dco_decode_list_bridge_animated_mask_path(
      dynamic raw);

  @protected
  List<BridgeAutosave> dco_decode_list_bridge_autosave(dynamic raw);

  @protected
  List<BridgeClip> dco_decode_list_bridge_clip(dynamic raw);

  @protected
  List<BridgeEffectInfo> dco_decode_list_bridge_effect_info(dynamic raw);

  @protected
  List<BridgeEffectInstanceInfo> dco_decode_list_bridge_effect_instance_info(
      dynamic raw);

  @protected
  List<BridgeEffectTiming> dco_decode_list_bridge_effect_timing(dynamic raw);

  @protected
  List<BridgeEnabledWhen> dco_decode_list_bridge_enabled_when(dynamic raw);

  @protected
  List<BridgeExportPresetEntry> dco_decode_list_bridge_export_preset_entry(
      dynamic raw);

  @protected
  List<BridgeExportQueueItem> dco_decode_list_bridge_export_queue_item(
      dynamic raw);

  @protected
  List<BridgeGraphEdge> dco_decode_list_bridge_graph_edge(dynamic raw);

  @protected
  List<BridgeGraphNode> dco_decode_list_bridge_graph_node(dynamic raw);

  @protected
  List<BridgeImportArg> dco_decode_list_bridge_import_arg(dynamic raw);

  @protected
  List<BridgeImportRow> dco_decode_list_bridge_import_row(dynamic raw);

  @protected
  List<BridgeKeyBinding> dco_decode_list_bridge_key_binding(dynamic raw);

  @protected
  List<BridgeKeyConflict> dco_decode_list_bridge_key_conflict(dynamic raw);

  @protected
  List<BridgeKeyShadow> dco_decode_list_bridge_key_shadow(dynamic raw);

  @protected
  List<BridgeKeyframe> dco_decode_list_bridge_keyframe(dynamic raw);

  @protected
  List<BridgeKeymapGroup> dco_decode_list_bridge_keymap_group(dynamic raw);

  @protected
  List<BridgeLayerEntry> dco_decode_list_bridge_layer_entry(dynamic raw);

  @protected
  List<BridgeLayerMarker> dco_decode_list_bridge_layer_marker(dynamic raw);

  @protected
  List<BridgeLayerTiming> dco_decode_list_bridge_layer_timing(dynamic raw);

  @protected
  List<BridgeMarker> dco_decode_list_bridge_marker(dynamic raw);

  @protected
  List<BridgeMask> dco_decode_list_bridge_mask(dynamic raw);

  @protected
  List<BridgeMetadataField> dco_decode_list_bridge_metadata_field(dynamic raw);

  @protected
  List<BridgeNodePosition> dco_decode_list_bridge_node_position(dynamic raw);

  @protected
  List<BridgeNodeRef> dco_decode_list_bridge_node_ref(dynamic raw);

  @protected
  List<BridgeParamGroup> dco_decode_list_bridge_param_group(dynamic raw);

  @protected
  List<BridgeParamInfo> dco_decode_list_bridge_param_info(dynamic raw);

  @protected
  List<BridgeParamPair> dco_decode_list_bridge_param_pair(dynamic raw);

  @protected
  List<BridgeParamValue> dco_decode_list_bridge_param_value(dynamic raw);

  @protected
  List<BridgePort> dco_decode_list_bridge_port(dynamic raw);

  @protected
  List<BridgePresetInfo> dco_decode_list_bridge_preset_info(dynamic raw);

  @protected
  List<BridgeScalar> dco_decode_list_bridge_scalar(dynamic raw);

  @protected
  List<BridgeShapeItem> dco_decode_list_bridge_shape_item(dynamic raw);

  @protected
  List<BridgeStroke> dco_decode_list_bridge_stroke(dynamic raw);

  @protected
  List<BridgeStrokePoint> dco_decode_list_bridge_stroke_point(dynamic raw);

  @protected
  List<BridgeTrackPoint> dco_decode_list_bridge_track_point(dynamic raw);

  @protected
  List<BridgeTransformProp> dco_decode_list_bridge_transform_prop(dynamic raw);

  @protected
  List<BridgeVertex> dco_decode_list_bridge_vertex(dynamic raw);

  @protected
  List<ItemReference> dco_decode_list_item_reference(dynamic raw);

  @protected
  List<LayerReference> dco_decode_list_layer_reference(dynamic raw);

  @protected
  List<Float32List> dco_decode_list_list_prim_f_32_strict(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LumitMediaStatus dco_decode_lumit_media_status(dynamic raw);

  @protected
  RustStreamSink<ScopedChange>? dco_decode_opt_StreamSink_scoped_change_Sse(
      dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  UuidValue? dco_decode_opt_Uuid(dynamic raw);

  @protected
  BridgeColourRgba? dco_decode_opt_box_autoadd_bridge_colour_rgba(dynamic raw);

  @protected
  BridgeCompSettings? dco_decode_opt_box_autoadd_bridge_comp_settings(
      dynamic raw);

  @protected
  BridgeExportSpec? dco_decode_opt_box_autoadd_bridge_export_spec(dynamic raw);

  @protected
  BridgeImportedProject? dco_decode_opt_box_autoadd_bridge_imported_project(
      dynamic raw);

  @protected
  BridgeMatte? dco_decode_opt_box_autoadd_bridge_matte(dynamic raw);

  @protected
  BridgeMediaInfo? dco_decode_opt_box_autoadd_bridge_media_info(dynamic raw);

  @protected
  BridgeProjectCacheLocation?
      dco_decode_opt_box_autoadd_bridge_project_cache_location(dynamic raw);

  @protected
  BridgeRational? dco_decode_opt_box_autoadd_bridge_rational(dynamic raw);

  @protected
  BridgeRenderedFrame? dco_decode_opt_box_autoadd_bridge_rendered_frame(
      dynamic raw);

  @protected
  BridgeScalar? dco_decode_opt_box_autoadd_bridge_scalar(dynamic raw);

  @protected
  BridgeSpan? dco_decode_opt_box_autoadd_bridge_span(dynamic raw);

  @protected
  BridgeTextDocument? dco_decode_opt_box_autoadd_bridge_text_document(
      dynamic raw);

  @protected
  BridgeTrackFailure? dco_decode_opt_box_autoadd_bridge_track_failure(
      dynamic raw);

  @protected
  BridgeTransform? dco_decode_opt_box_autoadd_bridge_transform(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ItemReference? dco_decode_opt_box_autoadd_item_reference(dynamic raw);

  @protected
  LayerReference? dco_decode_opt_box_autoadd_layer_reference(dynamic raw);

  @protected
  ProjectReference? dco_decode_opt_box_autoadd_project_reference(dynamic raw);

  @protected
  Float32List? dco_decode_opt_list_prim_f_32_strict(dynamic raw);

  @protected
  ProjectReference dco_decode_project_reference(dynamic raw);

  @protected
  ScopedChange dco_decode_scoped_change(dynamic raw);

  @protected
  SolidReference dco_decode_solid_reference(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WorkerResponse dco_decode_worker_response(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BridgeEffectInstance
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer);

  @protected
  BridgeError
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          SseDeserializer deserializer);

  @protected
  Expressions
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions(
          SseDeserializer deserializer);

  @protected
  LumitBridgeState
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          SseDeserializer deserializer);

  @protected
  BridgeEffectInstance
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer);

  @protected
  BridgeEffectInstance
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer);

  @protected
  BridgeEffectInstance
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer);

  @protected
  BridgeError
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          SseDeserializer deserializer);

  @protected
  Expressions
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions(
          SseDeserializer deserializer);

  @protected
  LumitBridgeState
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<ScopedChange> sse_decode_StreamSink_scoped_change_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<WorkerResponse> sse_decode_StreamSink_worker_response_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeBezierSide sse_decode_box_autoadd_bridge_bezier_side(
      SseDeserializer deserializer);

  @protected
  BridgeColour sse_decode_box_autoadd_bridge_colour(
      SseDeserializer deserializer);

  @protected
  BridgeColourRgba sse_decode_box_autoadd_bridge_colour_rgba(
      SseDeserializer deserializer);

  @protected
  BridgeCompSettings sse_decode_box_autoadd_bridge_comp_settings(
      SseDeserializer deserializer);

  @protected
  BridgeEffectValue sse_decode_box_autoadd_bridge_effect_value(
      SseDeserializer deserializer);

  @protected
  BridgeExportSpec sse_decode_box_autoadd_bridge_export_spec(
      SseDeserializer deserializer);

  @protected
  BridgeFileParam sse_decode_box_autoadd_bridge_file_param(
      SseDeserializer deserializer);

  @protected
  BridgeFlowParams sse_decode_box_autoadd_bridge_flow_params(
      SseDeserializer deserializer);

  @protected
  BridgeFrameProfile sse_decode_box_autoadd_bridge_frame_profile(
      SseDeserializer deserializer);

  @protected
  BridgeGraphWiring sse_decode_box_autoadd_bridge_graph_wiring(
      SseDeserializer deserializer);

  @protected
  BridgeImportedProject sse_decode_box_autoadd_bridge_imported_project(
      SseDeserializer deserializer);

  @protected
  BridgeMask sse_decode_box_autoadd_bridge_mask(SseDeserializer deserializer);

  @protected
  BridgeMatte sse_decode_box_autoadd_bridge_matte(SseDeserializer deserializer);

  @protected
  BridgeMediaInfo sse_decode_box_autoadd_bridge_media_info(
      SseDeserializer deserializer);

  @protected
  BridgeNodeRef sse_decode_box_autoadd_bridge_node_ref(
      SseDeserializer deserializer);

  @protected
  BridgePoint sse_decode_box_autoadd_bridge_point(SseDeserializer deserializer);

  @protected
  BridgeProjectCacheLocation
      sse_decode_box_autoadd_bridge_project_cache_location(
          SseDeserializer deserializer);

  @protected
  BridgeRational sse_decode_box_autoadd_bridge_rational(
      SseDeserializer deserializer);

  @protected
  BridgeRenderProgress sse_decode_box_autoadd_bridge_render_progress(
      SseDeserializer deserializer);

  @protected
  BridgeRenderedFrame sse_decode_box_autoadd_bridge_rendered_frame(
      SseDeserializer deserializer);

  @protected
  BridgeSampledPixels sse_decode_box_autoadd_bridge_sampled_pixels(
      SseDeserializer deserializer);

  @protected
  BridgeScalar sse_decode_box_autoadd_bridge_scalar(
      SseDeserializer deserializer);

  @protected
  BridgeScopeTrace sse_decode_box_autoadd_bridge_scope_trace(
      SseDeserializer deserializer);

  @protected
  BridgeShapeItem sse_decode_box_autoadd_bridge_shape_item(
      SseDeserializer deserializer);

  @protected
  BridgeSharedFrameInfo sse_decode_box_autoadd_bridge_shared_frame_info(
      SseDeserializer deserializer);

  @protected
  BridgeSharedFrameInfoLinux
      sse_decode_box_autoadd_bridge_shared_frame_info_linux(
          SseDeserializer deserializer);

  @protected
  BridgeSolidDef sse_decode_box_autoadd_bridge_solid_def(
      SseDeserializer deserializer);

  @protected
  BridgeSpan sse_decode_box_autoadd_bridge_span(SseDeserializer deserializer);

  @protected
  BridgeStroke sse_decode_box_autoadd_bridge_stroke(
      SseDeserializer deserializer);

  @protected
  BridgeTextDocument sse_decode_box_autoadd_bridge_text_document(
      SseDeserializer deserializer);

  @protected
  BridgeTrackFailure sse_decode_box_autoadd_bridge_track_failure(
      SseDeserializer deserializer);

  @protected
  BridgeTransform sse_decode_box_autoadd_bridge_transform(
      SseDeserializer deserializer);

  @protected
  CompositionReference sse_decode_box_autoadd_composition_reference(
      SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FolderReference sse_decode_box_autoadd_folder_reference(
      SseDeserializer deserializer);

  @protected
  FootageReference sse_decode_box_autoadd_footage_reference(
      SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ItemReference sse_decode_box_autoadd_item_reference(
      SseDeserializer deserializer);

  @protected
  LayerReference sse_decode_box_autoadd_layer_reference(
      SseDeserializer deserializer);

  @protected
  ProjectReference sse_decode_box_autoadd_project_reference(
      SseDeserializer deserializer);

  @protected
  SolidReference sse_decode_box_autoadd_solid_reference(
      SseDeserializer deserializer);

  @protected
  BridgeAnimatedMaskPath sse_decode_bridge_animated_mask_path(
      SseDeserializer deserializer);

  @protected
  BridgeAudioClock sse_decode_bridge_audio_clock(SseDeserializer deserializer);

  @protected
  BridgeAudioPeaks sse_decode_bridge_audio_peaks(SseDeserializer deserializer);

  @protected
  BridgeAutosave sse_decode_bridge_autosave(SseDeserializer deserializer);

  @protected
  BridgeBezierSide sse_decode_bridge_bezier_side(SseDeserializer deserializer);

  @protected
  BridgeCacheLocation sse_decode_bridge_cache_location(
      SseDeserializer deserializer);

  @protected
  BridgeCacheStats sse_decode_bridge_cache_stats(SseDeserializer deserializer);

  @protected
  BridgeCameraLink sse_decode_bridge_camera_link(SseDeserializer deserializer);

  @protected
  BridgeClip sse_decode_bridge_clip(SseDeserializer deserializer);

  @protected
  BridgeColour sse_decode_bridge_colour(SseDeserializer deserializer);

  @protected
  BridgeColourRgba sse_decode_bridge_colour_rgba(SseDeserializer deserializer);

  @protected
  BridgeCompModel sse_decode_bridge_comp_model(SseDeserializer deserializer);

  @protected
  BridgeCompSettings sse_decode_bridge_comp_settings(
      SseDeserializer deserializer);

  @protected
  BridgeCompSize sse_decode_bridge_comp_size(SseDeserializer deserializer);

  @protected
  BridgeCrop sse_decode_bridge_crop(SseDeserializer deserializer);

  @protected
  BridgeDiskCacheStats sse_decode_bridge_disk_cache_stats(
      SseDeserializer deserializer);

  @protected
  BridgeEffectInfo sse_decode_bridge_effect_info(SseDeserializer deserializer);

  @protected
  BridgeEffectInstanceInfo sse_decode_bridge_effect_instance_info(
      SseDeserializer deserializer);

  @protected
  BridgeEffectTiming sse_decode_bridge_effect_timing(
      SseDeserializer deserializer);

  @protected
  BridgeEffectValue sse_decode_bridge_effect_value(
      SseDeserializer deserializer);

  @protected
  BridgeEnabledCond sse_decode_bridge_enabled_cond(
      SseDeserializer deserializer);

  @protected
  BridgeEnabledWhen sse_decode_bridge_enabled_when(
      SseDeserializer deserializer);

  @protected
  BridgeExportPreset sse_decode_bridge_export_preset(
      SseDeserializer deserializer);

  @protected
  BridgeExportPresetEntry sse_decode_bridge_export_preset_entry(
      SseDeserializer deserializer);

  @protected
  BridgeExportQueueItem sse_decode_bridge_export_queue_item(
      SseDeserializer deserializer);

  @protected
  BridgeExportQueueState sse_decode_bridge_export_queue_state(
      SseDeserializer deserializer);

  @protected
  BridgeExportSpec sse_decode_bridge_export_spec(SseDeserializer deserializer);

  @protected
  BridgeExportState sse_decode_bridge_export_state(
      SseDeserializer deserializer);

  @protected
  BridgeFileParam sse_decode_bridge_file_param(SseDeserializer deserializer);

  @protected
  BridgeFlowParams sse_decode_bridge_flow_params(SseDeserializer deserializer);

  @protected
  BridgeFormatCaps sse_decode_bridge_format_caps(SseDeserializer deserializer);

  @protected
  BridgeFrameProfile sse_decode_bridge_frame_profile(
      SseDeserializer deserializer);

  @protected
  BridgeGraphEdge sse_decode_bridge_graph_edge(SseDeserializer deserializer);

  @protected
  BridgeGraphNode sse_decode_bridge_graph_node(SseDeserializer deserializer);

  @protected
  BridgeGraphWiring sse_decode_bridge_graph_wiring(
      SseDeserializer deserializer);

  @protected
  BridgeHistory sse_decode_bridge_history(SseDeserializer deserializer);

  @protected
  BridgeImportArg sse_decode_bridge_import_arg(SseDeserializer deserializer);

  @protected
  BridgeImportOutcome sse_decode_bridge_import_outcome(
      SseDeserializer deserializer);

  @protected
  BridgeImportReport sse_decode_bridge_import_report(
      SseDeserializer deserializer);

  @protected
  BridgeImportRow sse_decode_bridge_import_row(SseDeserializer deserializer);

  @protected
  BridgeImportedProject sse_decode_bridge_imported_project(
      SseDeserializer deserializer);

  @protected
  BridgeInputRef sse_decode_bridge_input_ref(SseDeserializer deserializer);

  @protected
  BridgeKeyBinding sse_decode_bridge_key_binding(SseDeserializer deserializer);

  @protected
  BridgeKeyConflict sse_decode_bridge_key_conflict(
      SseDeserializer deserializer);

  @protected
  BridgeKeyContext sse_decode_bridge_key_context(SseDeserializer deserializer);

  @protected
  BridgeKeyShadow sse_decode_bridge_key_shadow(SseDeserializer deserializer);

  @protected
  BridgeKeyframe sse_decode_bridge_keyframe(SseDeserializer deserializer);

  @protected
  BridgeKeymapGroup sse_decode_bridge_keymap_group(
      SseDeserializer deserializer);

  @protected
  BridgeKeymapPreset sse_decode_bridge_keymap_preset(
      SseDeserializer deserializer);

  @protected
  BridgeLayerEntry sse_decode_bridge_layer_entry(SseDeserializer deserializer);

  @protected
  BridgeLayerGraph sse_decode_bridge_layer_graph(SseDeserializer deserializer);

  @protected
  BridgeLayerInfo sse_decode_bridge_layer_info(SseDeserializer deserializer);

  @protected
  BridgeLayerKind sse_decode_bridge_layer_kind(SseDeserializer deserializer);

  @protected
  BridgeLayerMarker sse_decode_bridge_layer_marker(
      SseDeserializer deserializer);

  @protected
  BridgeLayerSwitch sse_decode_bridge_layer_switch(
      SseDeserializer deserializer);

  @protected
  BridgeLayerSwitches sse_decode_bridge_layer_switches(
      SseDeserializer deserializer);

  @protected
  BridgeLayerTiming sse_decode_bridge_layer_timing(
      SseDeserializer deserializer);

  @protected
  BridgeLinkState sse_decode_bridge_link_state(SseDeserializer deserializer);

  @protected
  BridgeMarker sse_decode_bridge_marker(SseDeserializer deserializer);

  @protected
  BridgeMask sse_decode_bridge_mask(SseDeserializer deserializer);

  @protected
  BridgeMaskMode sse_decode_bridge_mask_mode(SseDeserializer deserializer);

  @protected
  BridgeMatte sse_decode_bridge_matte(SseDeserializer deserializer);

  @protected
  BridgeMediaInfo sse_decode_bridge_media_info(SseDeserializer deserializer);

  @protected
  BridgeMemoryReport sse_decode_bridge_memory_report(
      SseDeserializer deserializer);

  @protected
  BridgeMetadataField sse_decode_bridge_metadata_field(
      SseDeserializer deserializer);

  @protected
  BridgeNodePosition sse_decode_bridge_node_position(
      SseDeserializer deserializer);

  @protected
  BridgeNodeRef sse_decode_bridge_node_ref(SseDeserializer deserializer);

  @protected
  BridgeOutputRef sse_decode_bridge_output_ref(SseDeserializer deserializer);

  @protected
  BridgePaintMode sse_decode_bridge_paint_mode(SseDeserializer deserializer);

  @protected
  BridgeParamGroup sse_decode_bridge_param_group(SseDeserializer deserializer);

  @protected
  BridgeParamInfo sse_decode_bridge_param_info(SseDeserializer deserializer);

  @protected
  BridgeParamKind sse_decode_bridge_param_kind(SseDeserializer deserializer);

  @protected
  BridgeParamPair sse_decode_bridge_param_pair(SseDeserializer deserializer);

  @protected
  BridgeParamValue sse_decode_bridge_param_value(SseDeserializer deserializer);

  @protected
  BridgePlaybackMode sse_decode_bridge_playback_mode(
      SseDeserializer deserializer);

  @protected
  BridgePlaybackTier sse_decode_bridge_playback_tier(
      SseDeserializer deserializer);

  @protected
  BridgePoint sse_decode_bridge_point(SseDeserializer deserializer);

  @protected
  BridgePort sse_decode_bridge_port(SseDeserializer deserializer);

  @protected
  BridgePortType sse_decode_bridge_port_type(SseDeserializer deserializer);

  @protected
  BridgePresetInfo sse_decode_bridge_preset_info(SseDeserializer deserializer);

  @protected
  BridgeProjectCacheLocation sse_decode_bridge_project_cache_location(
      SseDeserializer deserializer);

  @protected
  BridgeRational sse_decode_bridge_rational(SseDeserializer deserializer);

  @protected
  BridgeRecovery sse_decode_bridge_recovery(SseDeserializer deserializer);

  @protected
  BridgeRenderProgress sse_decode_bridge_render_progress(
      SseDeserializer deserializer);

  @protected
  BridgeRenderedFrame sse_decode_bridge_rendered_frame(
      SseDeserializer deserializer);

  @protected
  BridgeRetimeInterp sse_decode_bridge_retime_interp(
      SseDeserializer deserializer);

  @protected
  BridgeRevealGroups sse_decode_bridge_reveal_groups(
      SseDeserializer deserializer);

  @protected
  BridgeRevealKind sse_decode_bridge_reveal_kind(SseDeserializer deserializer);

  @protected
  BridgeSampledPixels sse_decode_bridge_sampled_pixels(
      SseDeserializer deserializer);

  @protected
  BridgeScalar sse_decode_bridge_scalar(SseDeserializer deserializer);

  @protected
  BridgeScopeTrace sse_decode_bridge_scope_trace(SseDeserializer deserializer);

  @protected
  BridgeShapeItem sse_decode_bridge_shape_item(SseDeserializer deserializer);

  @protected
  BridgeSharedFrameInfo sse_decode_bridge_shared_frame_info(
      SseDeserializer deserializer);

  @protected
  BridgeSharedFrameInfoLinux sse_decode_bridge_shared_frame_info_linux(
      SseDeserializer deserializer);

  @protected
  BridgeSideInterp sse_decode_bridge_side_interp(SseDeserializer deserializer);

  @protected
  BridgeSolidDef sse_decode_bridge_solid_def(SseDeserializer deserializer);

  @protected
  BridgeSpan sse_decode_bridge_span(SseDeserializer deserializer);

  @protected
  BridgeStroke sse_decode_bridge_stroke(SseDeserializer deserializer);

  @protected
  BridgeStrokePoint sse_decode_bridge_stroke_point(
      SseDeserializer deserializer);

  @protected
  BridgeTextDocument sse_decode_bridge_text_document(
      SseDeserializer deserializer);

  @protected
  BridgeTrackFailure sse_decode_bridge_track_failure(
      SseDeserializer deserializer);

  @protected
  BridgeTrackPoint sse_decode_bridge_track_point(SseDeserializer deserializer);

  @protected
  BridgeTrackStage sse_decode_bridge_track_stage(SseDeserializer deserializer);

  @protected
  BridgeTrackStatus sse_decode_bridge_track_status(
      SseDeserializer deserializer);

  @protected
  BridgeTransform sse_decode_bridge_transform(SseDeserializer deserializer);

  @protected
  BridgeTransformProp sse_decode_bridge_transform_prop(
      SseDeserializer deserializer);

  @protected
  BridgeUnit sse_decode_bridge_unit(SseDeserializer deserializer);

  @protected
  BridgeVertex sse_decode_bridge_vertex(SseDeserializer deserializer);

  @protected
  BridgeViewerTransport sse_decode_bridge_viewer_transport(
      SseDeserializer deserializer);

  @protected
  BridgeVramCacheStats sse_decode_bridge_vram_cache_stats(
      SseDeserializer deserializer);

  @protected
  CompositionReference sse_decode_composition_reference(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  F32Array4 sse_decode_f_32_array_4(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FolderReference sse_decode_folder_reference(SseDeserializer deserializer);

  @protected
  FootageReference sse_decode_footage_reference(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ItemReference sse_decode_item_reference(SseDeserializer deserializer);

  @protected
  LayerReference sse_decode_layer_reference(SseDeserializer deserializer);

  @protected
  List<BridgeEffectInstance>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<UuidValue> sse_decode_list_Uuid(SseDeserializer deserializer);

  @protected
  List<BridgeAnimatedMaskPath> sse_decode_list_bridge_animated_mask_path(
      SseDeserializer deserializer);

  @protected
  List<BridgeAutosave> sse_decode_list_bridge_autosave(
      SseDeserializer deserializer);

  @protected
  List<BridgeClip> sse_decode_list_bridge_clip(SseDeserializer deserializer);

  @protected
  List<BridgeEffectInfo> sse_decode_list_bridge_effect_info(
      SseDeserializer deserializer);

  @protected
  List<BridgeEffectInstanceInfo> sse_decode_list_bridge_effect_instance_info(
      SseDeserializer deserializer);

  @protected
  List<BridgeEffectTiming> sse_decode_list_bridge_effect_timing(
      SseDeserializer deserializer);

  @protected
  List<BridgeEnabledWhen> sse_decode_list_bridge_enabled_when(
      SseDeserializer deserializer);

  @protected
  List<BridgeExportPresetEntry> sse_decode_list_bridge_export_preset_entry(
      SseDeserializer deserializer);

  @protected
  List<BridgeExportQueueItem> sse_decode_list_bridge_export_queue_item(
      SseDeserializer deserializer);

  @protected
  List<BridgeGraphEdge> sse_decode_list_bridge_graph_edge(
      SseDeserializer deserializer);

  @protected
  List<BridgeGraphNode> sse_decode_list_bridge_graph_node(
      SseDeserializer deserializer);

  @protected
  List<BridgeImportArg> sse_decode_list_bridge_import_arg(
      SseDeserializer deserializer);

  @protected
  List<BridgeImportRow> sse_decode_list_bridge_import_row(
      SseDeserializer deserializer);

  @protected
  List<BridgeKeyBinding> sse_decode_list_bridge_key_binding(
      SseDeserializer deserializer);

  @protected
  List<BridgeKeyConflict> sse_decode_list_bridge_key_conflict(
      SseDeserializer deserializer);

  @protected
  List<BridgeKeyShadow> sse_decode_list_bridge_key_shadow(
      SseDeserializer deserializer);

  @protected
  List<BridgeKeyframe> sse_decode_list_bridge_keyframe(
      SseDeserializer deserializer);

  @protected
  List<BridgeKeymapGroup> sse_decode_list_bridge_keymap_group(
      SseDeserializer deserializer);

  @protected
  List<BridgeLayerEntry> sse_decode_list_bridge_layer_entry(
      SseDeserializer deserializer);

  @protected
  List<BridgeLayerMarker> sse_decode_list_bridge_layer_marker(
      SseDeserializer deserializer);

  @protected
  List<BridgeLayerTiming> sse_decode_list_bridge_layer_timing(
      SseDeserializer deserializer);

  @protected
  List<BridgeMarker> sse_decode_list_bridge_marker(
      SseDeserializer deserializer);

  @protected
  List<BridgeMask> sse_decode_list_bridge_mask(SseDeserializer deserializer);

  @protected
  List<BridgeMetadataField> sse_decode_list_bridge_metadata_field(
      SseDeserializer deserializer);

  @protected
  List<BridgeNodePosition> sse_decode_list_bridge_node_position(
      SseDeserializer deserializer);

  @protected
  List<BridgeNodeRef> sse_decode_list_bridge_node_ref(
      SseDeserializer deserializer);

  @protected
  List<BridgeParamGroup> sse_decode_list_bridge_param_group(
      SseDeserializer deserializer);

  @protected
  List<BridgeParamInfo> sse_decode_list_bridge_param_info(
      SseDeserializer deserializer);

  @protected
  List<BridgeParamPair> sse_decode_list_bridge_param_pair(
      SseDeserializer deserializer);

  @protected
  List<BridgeParamValue> sse_decode_list_bridge_param_value(
      SseDeserializer deserializer);

  @protected
  List<BridgePort> sse_decode_list_bridge_port(SseDeserializer deserializer);

  @protected
  List<BridgePresetInfo> sse_decode_list_bridge_preset_info(
      SseDeserializer deserializer);

  @protected
  List<BridgeScalar> sse_decode_list_bridge_scalar(
      SseDeserializer deserializer);

  @protected
  List<BridgeShapeItem> sse_decode_list_bridge_shape_item(
      SseDeserializer deserializer);

  @protected
  List<BridgeStroke> sse_decode_list_bridge_stroke(
      SseDeserializer deserializer);

  @protected
  List<BridgeStrokePoint> sse_decode_list_bridge_stroke_point(
      SseDeserializer deserializer);

  @protected
  List<BridgeTrackPoint> sse_decode_list_bridge_track_point(
      SseDeserializer deserializer);

  @protected
  List<BridgeTransformProp> sse_decode_list_bridge_transform_prop(
      SseDeserializer deserializer);

  @protected
  List<BridgeVertex> sse_decode_list_bridge_vertex(
      SseDeserializer deserializer);

  @protected
  List<ItemReference> sse_decode_list_item_reference(
      SseDeserializer deserializer);

  @protected
  List<LayerReference> sse_decode_list_layer_reference(
      SseDeserializer deserializer);

  @protected
  List<Float32List> sse_decode_list_list_prim_f_32_strict(
      SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LumitMediaStatus sse_decode_lumit_media_status(SseDeserializer deserializer);

  @protected
  RustStreamSink<ScopedChange>? sse_decode_opt_StreamSink_scoped_change_Sse(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  UuidValue? sse_decode_opt_Uuid(SseDeserializer deserializer);

  @protected
  BridgeColourRgba? sse_decode_opt_box_autoadd_bridge_colour_rgba(
      SseDeserializer deserializer);

  @protected
  BridgeCompSettings? sse_decode_opt_box_autoadd_bridge_comp_settings(
      SseDeserializer deserializer);

  @protected
  BridgeExportSpec? sse_decode_opt_box_autoadd_bridge_export_spec(
      SseDeserializer deserializer);

  @protected
  BridgeImportedProject? sse_decode_opt_box_autoadd_bridge_imported_project(
      SseDeserializer deserializer);

  @protected
  BridgeMatte? sse_decode_opt_box_autoadd_bridge_matte(
      SseDeserializer deserializer);

  @protected
  BridgeMediaInfo? sse_decode_opt_box_autoadd_bridge_media_info(
      SseDeserializer deserializer);

  @protected
  BridgeProjectCacheLocation?
      sse_decode_opt_box_autoadd_bridge_project_cache_location(
          SseDeserializer deserializer);

  @protected
  BridgeRational? sse_decode_opt_box_autoadd_bridge_rational(
      SseDeserializer deserializer);

  @protected
  BridgeRenderedFrame? sse_decode_opt_box_autoadd_bridge_rendered_frame(
      SseDeserializer deserializer);

  @protected
  BridgeScalar? sse_decode_opt_box_autoadd_bridge_scalar(
      SseDeserializer deserializer);

  @protected
  BridgeSpan? sse_decode_opt_box_autoadd_bridge_span(
      SseDeserializer deserializer);

  @protected
  BridgeTextDocument? sse_decode_opt_box_autoadd_bridge_text_document(
      SseDeserializer deserializer);

  @protected
  BridgeTrackFailure? sse_decode_opt_box_autoadd_bridge_track_failure(
      SseDeserializer deserializer);

  @protected
  BridgeTransform? sse_decode_opt_box_autoadd_bridge_transform(
      SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ItemReference? sse_decode_opt_box_autoadd_item_reference(
      SseDeserializer deserializer);

  @protected
  LayerReference? sse_decode_opt_box_autoadd_layer_reference(
      SseDeserializer deserializer);

  @protected
  ProjectReference? sse_decode_opt_box_autoadd_project_reference(
      SseDeserializer deserializer);

  @protected
  Float32List? sse_decode_opt_list_prim_f_32_strict(
      SseDeserializer deserializer);

  @protected
  ProjectReference sse_decode_project_reference(SseDeserializer deserializer);

  @protected
  ScopedChange sse_decode_scoped_change(SseDeserializer deserializer);

  @protected
  SolidReference sse_decode_solid_reference(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WorkerResponse sse_decode_worker_response(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          BridgeError self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions(
          Expressions self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          LumitBridgeState self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          BridgeError self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions(
          Expressions self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          LumitBridgeState self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_scoped_change_Sse(
      RustStreamSink<ScopedChange> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_worker_response_Sse(
      RustStreamSink<WorkerResponse> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_bezier_side(
      BridgeBezierSide self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_colour(
      BridgeColour self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_colour_rgba(
      BridgeColourRgba self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_comp_settings(
      BridgeCompSettings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_effect_value(
      BridgeEffectValue self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_export_spec(
      BridgeExportSpec self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_file_param(
      BridgeFileParam self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_flow_params(
      BridgeFlowParams self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_frame_profile(
      BridgeFrameProfile self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_graph_wiring(
      BridgeGraphWiring self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_imported_project(
      BridgeImportedProject self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_mask(
      BridgeMask self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_matte(
      BridgeMatte self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_media_info(
      BridgeMediaInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_node_ref(
      BridgeNodeRef self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_point(
      BridgePoint self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_project_cache_location(
      BridgeProjectCacheLocation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_rational(
      BridgeRational self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_render_progress(
      BridgeRenderProgress self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_rendered_frame(
      BridgeRenderedFrame self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_sampled_pixels(
      BridgeSampledPixels self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_scalar(
      BridgeScalar self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_scope_trace(
      BridgeScopeTrace self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_shape_item(
      BridgeShapeItem self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_shared_frame_info(
      BridgeSharedFrameInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_shared_frame_info_linux(
      BridgeSharedFrameInfoLinux self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_solid_def(
      BridgeSolidDef self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_span(
      BridgeSpan self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_stroke(
      BridgeStroke self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_text_document(
      BridgeTextDocument self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_track_failure(
      BridgeTrackFailure self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_transform(
      BridgeTransform self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_composition_reference(
      CompositionReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_folder_reference(
      FolderReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_footage_reference(
      FootageReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_item_reference(
      ItemReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_layer_reference(
      LayerReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_project_reference(
      ProjectReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_solid_reference(
      SolidReference self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_animated_mask_path(
      BridgeAnimatedMaskPath self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_audio_clock(
      BridgeAudioClock self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_audio_peaks(
      BridgeAudioPeaks self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_autosave(
      BridgeAutosave self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_bezier_side(
      BridgeBezierSide self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_cache_location(
      BridgeCacheLocation self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_cache_stats(
      BridgeCacheStats self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_camera_link(
      BridgeCameraLink self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_clip(BridgeClip self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_colour(BridgeColour self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_colour_rgba(
      BridgeColourRgba self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_comp_model(
      BridgeCompModel self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_comp_settings(
      BridgeCompSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_comp_size(
      BridgeCompSize self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_crop(BridgeCrop self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_disk_cache_stats(
      BridgeDiskCacheStats self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_effect_info(
      BridgeEffectInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_effect_instance_info(
      BridgeEffectInstanceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_effect_timing(
      BridgeEffectTiming self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_effect_value(
      BridgeEffectValue self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_enabled_cond(
      BridgeEnabledCond self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_enabled_when(
      BridgeEnabledWhen self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_export_preset(
      BridgeExportPreset self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_export_preset_entry(
      BridgeExportPresetEntry self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_export_queue_item(
      BridgeExportQueueItem self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_export_queue_state(
      BridgeExportQueueState self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_export_spec(
      BridgeExportSpec self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_export_state(
      BridgeExportState self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_file_param(
      BridgeFileParam self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_flow_params(
      BridgeFlowParams self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_format_caps(
      BridgeFormatCaps self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_frame_profile(
      BridgeFrameProfile self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_graph_edge(
      BridgeGraphEdge self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_graph_node(
      BridgeGraphNode self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_graph_wiring(
      BridgeGraphWiring self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_history(BridgeHistory self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_import_arg(
      BridgeImportArg self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_import_outcome(
      BridgeImportOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_import_report(
      BridgeImportReport self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_import_row(
      BridgeImportRow self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_imported_project(
      BridgeImportedProject self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_input_ref(
      BridgeInputRef self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_key_binding(
      BridgeKeyBinding self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_key_conflict(
      BridgeKeyConflict self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_key_context(
      BridgeKeyContext self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_key_shadow(
      BridgeKeyShadow self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_keyframe(
      BridgeKeyframe self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_keymap_group(
      BridgeKeymapGroup self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_keymap_preset(
      BridgeKeymapPreset self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_entry(
      BridgeLayerEntry self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_graph(
      BridgeLayerGraph self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_info(
      BridgeLayerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_kind(
      BridgeLayerKind self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_marker(
      BridgeLayerMarker self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_switch(
      BridgeLayerSwitch self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_switches(
      BridgeLayerSwitches self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_timing(
      BridgeLayerTiming self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_link_state(
      BridgeLinkState self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_marker(BridgeMarker self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_mask(BridgeMask self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_mask_mode(
      BridgeMaskMode self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_matte(BridgeMatte self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_media_info(
      BridgeMediaInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_memory_report(
      BridgeMemoryReport self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_metadata_field(
      BridgeMetadataField self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_node_position(
      BridgeNodePosition self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_node_ref(BridgeNodeRef self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_output_ref(
      BridgeOutputRef self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_paint_mode(
      BridgePaintMode self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_param_group(
      BridgeParamGroup self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_param_info(
      BridgeParamInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_param_kind(
      BridgeParamKind self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_param_pair(
      BridgeParamPair self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_param_value(
      BridgeParamValue self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_playback_mode(
      BridgePlaybackMode self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_playback_tier(
      BridgePlaybackTier self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_point(BridgePoint self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_port(BridgePort self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_port_type(
      BridgePortType self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_preset_info(
      BridgePresetInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_project_cache_location(
      BridgeProjectCacheLocation self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_rational(
      BridgeRational self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_recovery(
      BridgeRecovery self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_render_progress(
      BridgeRenderProgress self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_rendered_frame(
      BridgeRenderedFrame self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_retime_interp(
      BridgeRetimeInterp self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_reveal_groups(
      BridgeRevealGroups self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_reveal_kind(
      BridgeRevealKind self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_sampled_pixels(
      BridgeSampledPixels self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_scalar(BridgeScalar self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_scope_trace(
      BridgeScopeTrace self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_shape_item(
      BridgeShapeItem self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_shared_frame_info(
      BridgeSharedFrameInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_shared_frame_info_linux(
      BridgeSharedFrameInfoLinux self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_side_interp(
      BridgeSideInterp self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_solid_def(
      BridgeSolidDef self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_span(BridgeSpan self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_stroke(BridgeStroke self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_stroke_point(
      BridgeStrokePoint self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_text_document(
      BridgeTextDocument self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_track_failure(
      BridgeTrackFailure self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_track_point(
      BridgeTrackPoint self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_track_stage(
      BridgeTrackStage self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_track_status(
      BridgeTrackStatus self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_transform(
      BridgeTransform self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_transform_prop(
      BridgeTransformProp self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_unit(BridgeUnit self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_vertex(BridgeVertex self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_viewer_transport(
      BridgeViewerTransport self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_vram_cache_stats(
      BridgeVramCacheStats self, SseSerializer serializer);

  @protected
  void sse_encode_composition_reference(
      CompositionReference self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_32_array_4(F32Array4 self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_folder_reference(
      FolderReference self, SseSerializer serializer);

  @protected
  void sse_encode_footage_reference(
      FootageReference self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_item_reference(ItemReference self, SseSerializer serializer);

  @protected
  void sse_encode_layer_reference(
      LayerReference self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          List<BridgeEffectInstance> self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_Uuid(List<UuidValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_animated_mask_path(
      List<BridgeAnimatedMaskPath> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_autosave(
      List<BridgeAutosave> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_clip(
      List<BridgeClip> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_effect_info(
      List<BridgeEffectInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_effect_instance_info(
      List<BridgeEffectInstanceInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_effect_timing(
      List<BridgeEffectTiming> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_enabled_when(
      List<BridgeEnabledWhen> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_export_preset_entry(
      List<BridgeExportPresetEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_export_queue_item(
      List<BridgeExportQueueItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_graph_edge(
      List<BridgeGraphEdge> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_graph_node(
      List<BridgeGraphNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_import_arg(
      List<BridgeImportArg> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_import_row(
      List<BridgeImportRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_key_binding(
      List<BridgeKeyBinding> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_key_conflict(
      List<BridgeKeyConflict> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_key_shadow(
      List<BridgeKeyShadow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_keyframe(
      List<BridgeKeyframe> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_keymap_group(
      List<BridgeKeymapGroup> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_layer_entry(
      List<BridgeLayerEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_layer_marker(
      List<BridgeLayerMarker> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_layer_timing(
      List<BridgeLayerTiming> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_marker(
      List<BridgeMarker> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_mask(
      List<BridgeMask> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_metadata_field(
      List<BridgeMetadataField> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_node_position(
      List<BridgeNodePosition> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_node_ref(
      List<BridgeNodeRef> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_param_group(
      List<BridgeParamGroup> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_param_info(
      List<BridgeParamInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_param_pair(
      List<BridgeParamPair> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_param_value(
      List<BridgeParamValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_port(
      List<BridgePort> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_preset_info(
      List<BridgePresetInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_scalar(
      List<BridgeScalar> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_shape_item(
      List<BridgeShapeItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_stroke(
      List<BridgeStroke> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_stroke_point(
      List<BridgeStrokePoint> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_track_point(
      List<BridgeTrackPoint> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_transform_prop(
      List<BridgeTransformProp> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_vertex(
      List<BridgeVertex> self, SseSerializer serializer);

  @protected
  void sse_encode_list_item_reference(
      List<ItemReference> self, SseSerializer serializer);

  @protected
  void sse_encode_list_layer_reference(
      List<LayerReference> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_f_32_strict(
      List<Float32List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_loose(
      List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_lumit_media_status(
      LumitMediaStatus self, SseSerializer serializer);

  @protected
  void sse_encode_opt_StreamSink_scoped_change_Sse(
      RustStreamSink<ScopedChange>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Uuid(UuidValue? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_colour_rgba(
      BridgeColourRgba? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_comp_settings(
      BridgeCompSettings? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_export_spec(
      BridgeExportSpec? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_imported_project(
      BridgeImportedProject? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_matte(
      BridgeMatte? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_media_info(
      BridgeMediaInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_project_cache_location(
      BridgeProjectCacheLocation? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_rational(
      BridgeRational? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_rendered_frame(
      BridgeRenderedFrame? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_scalar(
      BridgeScalar? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_span(
      BridgeSpan? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_text_document(
      BridgeTextDocument? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_track_failure(
      BridgeTrackFailure? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_transform(
      BridgeTransform? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_item_reference(
      ItemReference? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_layer_reference(
      LayerReference? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_project_reference(
      ProjectReference? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_f_32_strict(
      Float32List? self, SseSerializer serializer);

  @protected
  void sse_encode_project_reference(
      ProjectReference self, SseSerializer serializer);

  @protected
  void sse_encode_scoped_change(ScopedChange self, SseSerializer serializer);

  @protected
  void sse_encode_solid_reference(
      SolidReference self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_worker_response(
      WorkerResponse self, SseSerializer serializer);
}

// Section: wire_class

class BridgeLibWire implements BaseWire {
  factory BridgeLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      BridgeLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BridgeLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstancePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_lumit_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstancePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstancePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_lumit_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstancePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_lumit_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_lumit_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressionsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_lumit_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressionsPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressionsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_lumit_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressions =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerExpressionsPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeStatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_lumit_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeStatePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeStatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_lumit_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeStatePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
